import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import test from "node:test";
import { GENERATOR_V2_OUTCOME_REGISTRY, WAVE_E_ENGINE_VERSION, WAVE_E_OUTCOME_CONTRACTS, generateQuestion, isWaveEImplementedByNewEngine, publicQuestionOnly, validateStudentResponse } from "../lib/generation-v2/index.ts";

const matrix = JSON.parse(readFileSync("artifacts/generator-v2-wave-e/outcome-matrix.json", "utf8")); const diversity = JSON.parse(readFileSync("artifacts/generator-v2-wave-e/diversity.json", "utf8")); const report = JSON.parse(readFileSync("artifacts/generator-v2-wave-e/report.json", "utf8"));
test("Wave E locks 86 explicit contracts and 48 mathematical capabilities", () => { assert.equal(WAVE_E_OUTCOME_CONTRACTS.length, 86); assert.equal(new Set(WAVE_E_OUTCOME_CONTRACTS.map((contract) => contract.outcomeId)).size, 86); assert.equal(new Set(WAVE_E_OUTCOME_CONTRACTS.map((contract) => contract.canonicalVariantId)).size, 48); assert.equal(WAVE_E_OUTCOME_CONTRACTS.filter(isWaveEImplementedByNewEngine).length, 84); assert.equal(WAVE_E_OUTCOME_CONTRACTS.filter((contract) => contract.engineVersion === "PROVEN_V2_BASELINE").length, 2); assert.equal(matrix.count, 86); assert.equal(matrix.inventoryRecordedBeforeImplementation, true); });
test("Wave E generates, validates, and keeps private fields outside public snapshots", () => { for (const [index, contract] of WAVE_E_OUTCOME_CONTRACTS.entries()) { const q = generateQuestion({ outcomeId: contract.outcomeId, grade: contract.grade, difficulty: "HARD", seed: `wave-e-unit-${index}`, locale: "vi-VN" }); assert.equal(q.validation.ok, true); assert.equal(q.provenance.questionSource, "GENERATED_V2"); assert.equal(JSON.stringify(publicQuestionOnly(q)).includes("correctResponse"), false); assert.equal(validateStudentResponse(q, q.privateSolution.correctResponse).isCorrect, true); } });
test("Wave E new engine remains deterministic after Wave F integration", () => { const contract = WAVE_E_OUTCOME_CONTRACTS.find(isWaveEImplementedByNewEngine)!; const input = { outcomeId: contract.outcomeId, grade: contract.grade, difficulty: "MEDIUM" as const, seed: "wave-e-deterministic", locale: "vi-VN" as const }; assert.equal(contract.engineVersion, WAVE_E_ENGINE_VERSION); assert.deepEqual(generateQuestion(input), generateQuestion(input)); });
test("Wave E certainty-language choices do not contain synonymous distractors", () => { const contract = WAVE_E_OUTCOME_CONTRACTS.find((item) => item.canonicalVariantId === "EVENT_CERTAINTY_LANGUAGE")!; for (let seed = 0; seed < 20; seed += 1) { const q = generateQuestion({ outcomeId: contract.outcomeId, grade: contract.grade, difficulty: "MEDIUM", seed: `certainty-language-${seed}`, locale: "vi-VN" }); const labels = q.publicSnapshot.interaction.options?.map((option) => option.label) ?? []; assert.equal(labels.includes("luôn luôn") && labels.includes("chắc chắn"), false); } });
test("Wave E audit records 5,160 validated samples and remains stable in the 546 registry", () => { assert.equal(diversity.result, "PASS"); assert.equal(diversity.audit.generatedSamples, 5160); assert.equal(diversity.summary.maximumExactDuplicateRate, 0); assert.ok(diversity.summary.maximumNearDuplicatePairRate <= 0.12); assert.equal(GENERATOR_V2_OUTCOME_REGISTRY.length, 546); assert.equal(report.coverage.claimsMilestone2Complete, false); });
