import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import test from "node:test";
import { GENERATOR_V2_OUTCOME_REGISTRY, WAVE_F_ENGINE_VERSION, WAVE_F_OUTCOME_CONTRACTS, GenerationV2Error, generateQuestion, publicQuestionOnly, validateStudentResponse } from "../lib/generation-v2/index.ts";

const matrix = JSON.parse(readFileSync("artifacts/generator-v2-wave-f/outcome-matrix.json", "utf8")); const diversity = JSON.parse(readFileSync("artifacts/generator-v2-wave-f/diversity.json", "utf8")); const report = JSON.parse(readFileSync("artifacts/generator-v2-wave-f/report.json", "utf8"));
test("Wave F locks the exact final 10 outcomes as eight explicit new capabilities", () => { assert.equal(WAVE_F_OUTCOME_CONTRACTS.length, 10); assert.equal(new Set(WAVE_F_OUTCOME_CONTRACTS.map((contract) => contract.outcomeId)).size, 10); assert.equal(new Set(WAVE_F_OUTCOME_CONTRACTS.map((contract) => contract.canonicalVariantId)).size, 8); assert.equal(WAVE_F_OUTCOME_CONTRACTS.every((contract) => contract.engineVersion === WAVE_F_ENGINE_VERSION), true); assert.equal(matrix.WAVE_F_OUTCOMES, 10); assert.equal(matrix.inventoryRecordedBeforeImplementation, true); });
test("Wave F generates deterministic validated questions without public private fields", () => { for (const [index, contract] of WAVE_F_OUTCOME_CONTRACTS.entries()) { const input = { outcomeId: contract.outcomeId, grade: contract.grade, difficulty: "HARD" as const, seed: `wave-f-unit-${index}`, locale: "vi-VN" as const }; const q = generateQuestion(input); assert.deepEqual(q, generateQuestion(input)); assert.equal(q.validation.ok, true); assert.equal(q.provenance.questionSource, "GENERATED_V2"); assert.equal(JSON.stringify(publicQuestionOnly(q)).includes("correctResponse"), false); assert.equal(validateStudentResponse(q, q.privateSolution.correctResponse).isCorrect, true); } });
test("Wave F audit records 600 validated samples and completes explicit technical coverage", () => { assert.equal(diversity.result, "PASS"); assert.equal(diversity.audit.generatedSamples, 600); assert.equal(diversity.summary.maximumExactDuplicateRate, 0); assert.ok(diversity.summary.maximumNearDuplicatePairRate <= 0.12); assert.equal(GENERATOR_V2_OUTCOME_REGISTRY.length, 546); assert.equal(report.coverage.overallGeneratorV2ImplementedOutcomes, 546); assert.equal(report.coverage.remainingUnimplementedOutcomes, 0); assert.equal(report.coverage.claimsOwnerApproved, false); });
test("unknown outcomes still fail closed", () => { let error: unknown; try { generateQuestion({ outcomeId: "MOET2018-G1-NUM-NOT-MAPPED", grade: 1, difficulty: "EASY", seed: "wave-f-fail-closed", locale: "vi-VN" }); } catch (caught) { error = caught; } assert.equal(error instanceof GenerationV2Error, true); assert.equal((error as GenerationV2Error).code, "GENERATOR_V2_OUTCOME_NOT_IMPLEMENTED"); });
