import { canonicalize, normalizedDefinition, sha256 } from "./canonical.ts";
import { gradeNineWaveAPack } from "./grade9-wave-a.ts"; import { gradeNineWaveBPack } from "./grade9-wave-b.ts"; import { gradeNineWaveCPack } from "./grade9-wave-c.ts"; import { gradeNineWaveDPack } from "./grade9-wave-d.ts"; import { gradeNineWaveEPack } from "./grade9-wave-e.ts"; import { gradeNineWaveFPack } from "./grade9-wave-f.ts"; import { gradeNineWaveGPack } from "./grade9-wave-g.ts";
import { evaluateExpression } from "./math.ts"; import { buildOfficialGradeSkeleton, officialSourceReferenceId } from "./official-source-map.ts"; import { requiredAutomatedEvidenceChecks } from "./review.ts"; import type { CandidateQuestion,DifficultyBand,ExplanationSpec,GradePack,MathExpression } from "./types.ts";

const grade=9 as const,sourceId=officialSourceReferenceId(grade),unitId="grade-9-applied-problem-solving",skillId="moet2018-g9-naa-p072-022";
const packId="grade-9-applied-quadratic-problems-wave-h",candidateId="g9-applied-quadratic-problems-wave-h-rc1",version="g9-applied-quadratic-problems-1.0.0-wave-h",policyVersion="g9-applied-quadratic-problems-policy-1.0.0-wave-h";
const sourceOutcomeIds=["MOET2018-G9-NAA-P072-022"] as const,prerequisiteOutcomeIds=[] as const;
const v=(n:number):MathExpression=>({op:"VALUE",numerator:n,denominator:1}),op=(kind:"ADD"|"SUBTRACT"|"MULTIPLY"|"DIVIDE",left:MathExpression,right:MathExpression):MathExpression=>({op:kind,left,right}),sqrt=(value:MathExpression):MathExpression=>({op:"SQRT",value}),square=(value:MathExpression)=>op("MULTIPLY",value,value);
type Structure="RECTANGLE_AREA"|"PYTHAGOREAN_LEG"|"POSITIVE_RETURN_TIME"|"BOUNDED_REVENUE_ROOT"|"ENLARGED_SQUARE"|"TRIANGULAR_ARRAY";
type Model=Readonly<{a:number;b:number;c:number;bound?:number}>;
type Fixture=Readonly<{prompt:string;unit:"m"|"giờ"|"sản phẩm"|"hàng";structure:Structure;publicTokens:readonly string[];root:number;model:Model;derivation:MathExpression;intermediates:readonly MathExpression[];steps:readonly string[]}>;
const exactInteger=(expression:MathExpression)=>{const result=evaluateExpression(expression);if(result.denominator!==1||result.numerator<=0)throw new Error("AUTOMATED_VERIFICATION_INSUFFICIENT:NON_POSITIVE_INTEGER_ROOT");return String(result.numerator);};
function satisfies(entry:Fixture,x:number){const {a,b}=entry.model;if(entry.structure==="RECTANGLE_AREA")return x*(x+a)===b;if(entry.structure==="PYTHAGOREAN_LEG")return x*x+(x+a)*(x+a)===b*b;if(entry.structure==="POSITIVE_RETURN_TIME")return -x*x+a*x===0;if(entry.structure==="BOUNDED_REVENUE_ROOT")return x*(a-x)===b&&x<(entry.model.bound??0);if(entry.structure==="ENLARGED_SQUARE")return (x+a)*(x+a)===b;return x*(x+1)/2===b;}
function admissibleRoots(entry:Fixture){const limit=Math.max(200,entry.model.a+entry.model.b+entry.model.c);return Array.from({length:limit},(_,index)=>index+1).filter(x=>satisfies(entry,x));}
function assertFixture(entry:Fixture){if(!entry.prompt.includes(entry.unit))throw new Error("AUTOMATED_VERIFICATION_INSUFFICIENT:UNIT_OR_CONTEXT_MISMATCH");if(entry.publicTokens.length<3||entry.publicTokens.some(token=>!entry.prompt.includes(token)))throw new Error("AUTOMATED_VERIFICATION_INSUFFICIENT:PUBLIC_DATA_INCOMPLETE");if(entry.intermediates.length<2||entry.intermediates.length>4||entry.steps.length<2)throw new Error("AUTOMATED_VERIFICATION_INSUFFICIENT:INTERMEDIATE_STRUCTURE_INVALID");if(entry.root<=0||exactInteger(entry.derivation)!==String(entry.root))throw new Error("AUTOMATED_VERIFICATION_INSUFFICIENT:ANSWER_DERIVATION_MISMATCH");const roots=admissibleRoots(entry);if(roots.length!==1||roots[0]!==entry.root)throw new Error("AUTOMATED_VERIFICATION_INSUFFICIENT:NON_UNIQUE_OR_INVALID_DOMAIN_ROOT");entry.intermediates.forEach(expression=>evaluateExpression(expression));}
function fixture(prompt:string,unit:Fixture["unit"],structure:Structure,publicTokens:readonly string[],root:number,model:Model,derivation:MathExpression,intermediates:readonly MathExpression[],steps:readonly string[]):Fixture{const result={prompt:prompt.normalize("NFC"),unit,structure,publicTokens,root,model,derivation,intermediates,steps:steps.map(step=>step.normalize("NFC"))} as const;assertFixture(result);return result;}
const positiveRoot=(k:number,area:number)=>{const discriminant=op("ADD",square(v(k)),op("MULTIPLY",v(4),v(area)));return op("DIVIDE",op("SUBTRACT",sqrt(discriminant),v(k)),v(2));};
function buildFixtures():readonly Fixture[]{const out:Fixture[]=[];
  ([[6,4],[8,5],[10,6],[12,7]] as const).forEach(([root,gap])=>{const area=root*(root+gap),disc=gap*gap+4*area,answer=positiveRoot(gap,area);out.push(fixture(`Một hình chữ nhật có chiều rộng x m, chiều dài hơn chiều rộng ${gap} m và diện tích ${area} m vuông. Biết x > 0. Chiều rộng bằng bao nhiêu m?`,"m","RECTANGLE_AREA",[String(gap),String(area),"x > 0"],root,{a:gap,b:area,c:0},answer,[v(disc),sqrt(v(disc)),answer],[`Lập phương trình x(x + ${gap}) = ${area}.`,`Biệt thức thích hợp là ${disc}, căn bậc hai là ${Math.sqrt(disc)}.`,`Chọn nghiệm dương x = ${root} m.`]));});
  ([[3,1,5],[5,7,13],[8,7,17],[7,17,25]] as const).forEach(([root,gap,hyp])=>{const first=square(v(root)),second=square(v(root+gap)),sum=op("ADD",first,second);out.push(fixture(`Một tam giác vuông có hai cạnh góc vuông dài x m và (x + ${gap}) m, cạnh huyền dài ${hyp} m. Biết x > 0. Tìm x theo mét.`,"m","PYTHAGOREAN_LEG",[String(gap),String(hyp),"x > 0"],root,{a:gap,b:hyp,c:0},v(root),[first,second,sum],[`Lập phương trình x² + (x + ${gap})² = ${hyp}².`,`Thử nghiệm dương ${root}: ${root}² + ${root+gap}² = ${hyp*hyp}.`,`Nghiệm dương duy nhất là x = ${root} m.`]));});
  ([6,8,10,12] as const).forEach(root=>{const product=op("MULTIPLY",v(root),v(root)),zero=op("SUBTRACT",product,product);out.push(fixture(`Độ cao của một vật sau t giờ được mô hình hóa bởi h(t) = -t² + ${root}t. Sau thời điểm t = 0, vật trở lại độ cao 0 sau bao nhiêu giờ?`,"giờ","POSITIVE_RETURN_TIME",[String(root),"t = 0","0"],root,{a:root,b:0,c:0},v(root),[product,zero],[`Giải -t² + ${root}t = 0 bằng cách đặt t làm nhân tử.`,`Hai nghiệm là 0 và ${root}; điều kiện sau t = 0 loại nghiệm 0.`,`Thời gian cần tìm là ${root} giờ.`]));});
  ([[8,24],[10,30],[12,36],[14,42]] as const).forEach(([root,p])=>{const revenue=root*(p-root),disc=p*p-4*revenue,answer=op("DIVIDE",op("SUBTRACT",v(p),sqrt(v(disc))),v(2)),bound=p/2;out.push(fixture(`Một mô hình doanh thu là R = x(${p} - x), với x là số sản phẩm và 0 < x < ${bound}. Khi R = ${revenue}, x bằng bao nhiêu sản phẩm?`,"sản phẩm","BOUNDED_REVENUE_ROOT",[String(p),String(bound),String(revenue)],root,{a:p,b:revenue,c:0,bound},answer,[v(disc),sqrt(v(disc)),answer],[`Lập phương trình x(${p} - x) = ${revenue}.`,`Hai nghiệm đại số đối xứng; điều kiện x < ${bound} chọn nghiệm nhỏ.`,`Nghiệm phù hợp là ${root} sản phẩm.`]));});
  ([[5,3],[7,4],[9,5],[11,6]] as const).forEach(([root,extra])=>{const area=(root+extra)**2,side=sqrt(v(area)),answer=op("SUBTRACT",side,v(extra));out.push(fixture(`Một sân hình vuông có cạnh x m. Sau khi tăng mỗi cạnh thêm ${extra} m, diện tích là ${area} m vuông. Biết x > 0. Cạnh ban đầu dài bao nhiêu m?`,"m","ENLARGED_SQUARE",[String(extra),String(area),"x > 0"],root,{a:extra,b:area,c:0},answer,[side,answer],[`Lập phương trình (x + ${extra})² = ${area}.`,`Độ dài dương x + ${extra} = ${Math.sqrt(area)}.`,`Suy ra x = ${root} m.`]));});
  ([8,10,12,15] as const).forEach(root=>{const total=root*(root+1)/2,disc=1+8*total,answer=op("DIVIDE",op("SUBTRACT",sqrt(v(disc)),v(1)),v(2));out.push(fixture(`Các vật được xếp thành x hàng; hàng thứ nhất có 1 sản phẩm, hàng thứ hai có 2, tiếp tục đến hàng x. Tổng cộng có ${total} sản phẩm và x > 0. Có bao nhiêu hàng?`,"hàng","TRIANGULAR_ARRAY",[String(total),"x > 0","sản phẩm"],root,{a:0,b:total,c:0},answer,[v(disc),sqrt(v(disc)),answer],[`Tổng là x(x + 1)/2 = ${total}.`,`Từ phương trình bậc hai, căn biệt thức là ${Math.sqrt(disc)}.`,`Nghiệm dương là x = ${root} hàng.`]));});return out;}
const fixtures=buildFixtures();
export function verifyGradeNineWaveHIndependentOracle(){return fixtures.flatMap((entry,index)=>{const roots=admissibleRoots(entry);try{return roots.length===1&&roots[0]===entry.root&&exactInteger(entry.derivation)===String(entry.root)?[]:[`g9-wave-h-${index+1}:INDEPENDENT_ORACLE_MISMATCH`];}catch{return[`g9-wave-h-${index+1}:INDEPENDENT_ORACLE_ERROR`];}});}
export function verifyGradeNineWaveHMalformedFixtures(){const base=fixtures[0]!,bad:readonly Fixture[]=[{...base,prompt:"Thiếu dữ liệu công khai."},{...base,unit:"kg" as Fixture["unit"]},{...base,root:0,derivation:v(0)},{...base,model:{...base.model,b:base.model.b+1}}];return bad.flatMap((entry,index)=>{try{assertFixture(entry);return[`g9-wave-h-malformed-${index+1}:ACCEPTED`];}catch(error){return error instanceof Error&&error.message.startsWith("AUTOMATED_VERIFICATION_INSUFFICIENT")?[]:[`g9-wave-h-malformed-${index+1}:WRONG_ERROR`];}});}
const independentOracleErrors=verifyGradeNineWaveHIndependentOracle(),malformedFixtureErrors=verifyGradeNineWaveHMalformedFixtures();if(independentOracleErrors.length||malformedFixtureErrors.length)throw new Error(`GRADE_9_WAVE_H_ORACLE_FAILED:${[...independentOracleErrors,...malformedFixtureErrors]}`);
const purposes=["FOUNDATION","STANDARD_APPLICATION","MISCONCEPTION_TARGETING","REMEDIATION","TRANSFER_APPLICATION"] as const,difficulty=(index:number):DifficultyBand=>index%3===0?"FOUNDATIONAL":index%3===1?"CORE":"EXTENSION",skeleton=buildOfficialGradeSkeleton(grade),receiptIds=requiredAutomatedEvidenceChecks.map(check=>`${packId}-${check.toLowerCase().replaceAll("_","-")}`);
const questions:CandidateQuestion[]=fixtures.map((entry,index)=>{const id=`g9-wave-h-${String(index+1).padStart(2,"0")}`;return{id,grade,unitId,blueprintId:`g9-wave-h-${difficulty(index).toLowerCase()}`,skillId,prompt:entry.prompt,options:null,answer:{type:"INTEGER_INPUT",exactValue:exactInteger(entry.derivation),unit:entry.unit,derivation:entry.derivation},explanationId:`${id}-explanation`,difficulty:difficulty(index),provenance:{kind:"DETERMINISTIC_TEMPLATE",templateVersion:"g9-applied-quadratic-wave-h-1.0.0",seed:`g9-wave-h-${entry.structure.toLowerCase()}-${index+1}`,sourceReferenceIds:[sourceId]},reviewStatus:"BUNDLED",published:false,pilotEligible:false,fixtureOnly:false,duplicateFingerprint:sha256(normalizedDefinition(`${entry.prompt}|`).toLocaleLowerCase("vi")),validationReceiptIds:receiptIds,instructionalPurpose:purposes[index%purposes.length]!};});
const explanations:ExplanationSpec[]=questions.map((question,index)=>({id:question.explanationId,questionId:question.id,steps:fixtures[index]!.steps,finalAnswer:question.answer.exactValue!,evidenceReceiptIds:[`${packId}-explanation-consistency`]})),blueprints=(["FOUNDATIONAL","CORE","EXTENSION"] as const).map(band=>({id:`g9-wave-h-${band.toLowerCase()}`,grade,skillId,difficulty:band,questionType:"INTEGER_INPUT" as const,templateId:"g9-applied-quadratic-wave-h-1.0.0",targetCount:8,sourceReferenceIds:[sourceId]}));
const evidenceReceipts=requiredAutomatedEvidenceChecks.map(check=>({id:`${packId}-${check.toLowerCase().replaceAll("_","-")}`,entityId:packId,check,status:"PASSED" as const,evidence:check==="SOURCE_MAPPING"?"Retained EXACT source outcome MOET2018-G9-NAA-P072-022, page 72.":check==="MATHEMATICAL_ANSWER"?`Independent admissible-domain quadratic oracle verified 24 questions across 6 structures; errors ${independentOracleErrors.length}; malformed errors ${malformedFixtureErrors.length}.`:`Deterministic Grade 9 Wave H ${check}.`}));const candidateCore={format:"plave-wave-h-candidate-v1",grade,candidateId,version,policyVersion,sourceOutcomeIds,blueprints,questions,explanations},bundleHash=sha256(canonicalize(candidateCore));
export const gradeNineWaveHPack:GradePack={schemaVersion:"content-factory-grade-pack-v1",grade,packId,packVersion:version,immutableReference:false,testOnly:false,locale:"vi-VN",unicodeNormalization:"NFC",sources:[skeleton.source],domains:skeleton.domains,units:skeleton.units,knowledgeNodes:skeleton.knowledgeNodes,skills:skeleton.skills,objectives:skeleton.objectives,prerequisites:[{fromSkillId:"moet2018-g9-sta-p076-008",toSkillId:skillId,evidence:"HYPOTHESIS_REQUIRES_EVIDENCE",sourceReferenceIds:[]}],blueprints,questions,quarantinedQuestions:[],explanations,evidenceReceipts,candidate:{candidateId,version,bundleHash,policyVersion},adaptivePolicy:{version:policyVersion,status:"VALIDATED"},release:{publication:"DRAFT",visibility:"HIDDEN",pilotEnabled:false,runtimeEnabled:false,retentionEnabled:false},production:{wave:"H",selectedSliceId:"g9-applied-quadratic-problems",selectionBasis:["SOURCE_VERIFIED","PAGE_72_EXACT_ROW","PUBLIC_DATA_COMPLETE","DOMAIN_ISOLATES_ONE_ROOT","INDEPENDENT_ADMISSIBLE_ROOT_ORACLE","SIX_REASONING_STRUCTURES"],generated:24,repaired:0,evidenceGatePassed:24,verificationInsufficient:0,rejected:0,duplicate:0,candidateEligible:24},legacyAsset:null};
export const gradeNineWaveHMetadata=Object.freeze({schemaVersion:"plave-wave-h-metadata-v1",wave:"H",grade,title:"Bài toán thực tiễn dùng phương trình bậc hai",sourceClassification:"EXACT",sourcePages:[72] as const,sourceOutcomeIds,prerequisiteOutcomeIds,prerequisiteEvidence:"NOT_SPECIFIED_BY_SOURCE_INVENTORY",progressionHypothesis:{fromOutcomeId:"MOET2018-G9-STA-P076-008",toOutcomeId:sourceOutcomeIds[0],evidence:"HYPOTHESIS_REQUIRES_EVIDENCE"},reasoningStructures:[...new Set(fixtures.map(entry=>entry.structure))],deferredOutcomeIds:["MOET2018-G9-EXP-P078-001","MOET2018-G9-EXP-P078-004"] as const,deferredReason:"AUTOMATED_VERIFICATION_INSUFFICIENT",independentOracleErrors,malformedFixtureErrors,production:gradeNineWaveHPack.production,candidate:gradeNineWaveHPack.candidate,release:gradeNineWaveHPack.release});
export const gradeNineWavesABCDEFGH=Object.freeze({grade,packs:[gradeNineWaveAPack,gradeNineWaveBPack,gradeNineWaveCPack,gradeNineWaveDPack,gradeNineWaveEPack,gradeNineWaveFPack,gradeNineWaveGPack,gradeNineWaveHPack] as const,questions:[...gradeNineWaveAPack.questions,...gradeNineWaveBPack.questions,...gradeNineWaveCPack.questions,...gradeNineWaveDPack.questions,...gradeNineWaveEPack.questions,...gradeNineWaveFPack.questions,...gradeNineWaveGPack.questions,...gradeNineWaveHPack.questions],candidateBindings:[gradeNineWaveAPack.candidate,gradeNineWaveBPack.candidate,gradeNineWaveCPack.candidate,gradeNineWaveDPack.candidate,gradeNineWaveEPack.candidate,gradeNineWaveFPack.candidate,gradeNineWaveGPack.candidate,gradeNineWaveHPack.candidate],release:gradeNineWaveHPack.release});
