import { canonicalize, normalizedDefinition, sha256 } from "./canonical.ts";
import { gradeSevenWaveAPack } from "./grade7-wave-a.ts"; import { gradeSevenWaveBPack } from "./grade7-wave-b.ts"; import { gradeSevenWaveCPack } from "./grade7-wave-c.ts"; import { gradeSevenWaveDPack } from "./grade7-wave-d.ts"; import { gradeSevenWaveEPack } from "./grade7-wave-e.ts"; import { gradeSevenWaveFPack } from "./grade7-wave-f.ts"; import { gradeSevenWaveGPack } from "./grade7-wave-g.ts";
import { evaluateExpression } from "./math.ts"; import { buildOfficialGradeSkeleton, officialSourceReferenceId } from "./official-source-map.ts"; import { requiredAutomatedEvidenceChecks } from "./review.ts"; import type { CandidateQuestion,DifficultyBand,ExplanationSpec,GradePack,MathExpression } from "./types.ts";

const grade=7 as const,sourceId=officialSourceReferenceId(grade),unitId="grade-7-applied-problem-solving",skillId="moet2018-g7-naa-p056-005";
const packId="grade-7-applied-rational-problems-wave-h",candidateId="g7-applied-rational-problems-wave-h-rc1",version="g7-applied-rational-problems-1.0.0-wave-h",policyVersion="g7-applied-rational-problems-policy-1.0.0-wave-h";
const sourceOutcomeIds=["MOET2018-G7-NAA-P056-005"] as const,prerequisiteOutcomeIds=[] as const;
const v=(n:number,d=1):MathExpression=>({op:"VALUE",numerator:n,denominator:d}),op=(kind:"ADD"|"SUBTRACT"|"MULTIPLY"|"DIVIDE",left:MathExpression,right:MathExpression):MathExpression=>({op:kind,left,right});
type Structure="MOTION_DISTANCE"|"MOTION_REMAINDER"|"THREE_SEGMENT_TOTAL"|"TWO_USE_REMAINDER"|"RATE_PLUS_OFFSET"|"RESERVE_THEN_SHARE";
type Fixture=Readonly<{prompt:string;unit:"km"|"m";structure:Structure;publicTokens:readonly string[];derivation:MathExpression;intermediates:readonly MathExpression[];steps:readonly string[]}>;
const allowedUnits=new Set(["km","m"]);
const exact=(expression:MathExpression)=>{const result=evaluateExpression(expression);if(result.denominator<=0)throw new Error("AUTOMATED_VERIFICATION_INSUFFICIENT:INVALID_RATIONAL");return result.denominator===1?String(result.numerator):`${result.numerator}/${result.denominator}`;};
function assertFixture(entry:Fixture){if(!allowedUnits.has(entry.unit)||!entry.prompt.includes(entry.unit))throw new Error("AUTOMATED_VERIFICATION_INSUFFICIENT:UNIT_OR_CONTEXT_MISMATCH");if(entry.publicTokens.length<2||entry.publicTokens.some(token=>!entry.prompt.includes(token)))throw new Error("AUTOMATED_VERIFICATION_INSUFFICIENT:PUBLIC_DATA_INCOMPLETE");if(entry.intermediates.length<2||entry.intermediates.length>4||entry.steps.length<2)throw new Error("AUTOMATED_VERIFICATION_INSUFFICIENT:INTERMEDIATE_STRUCTURE_INVALID");entry.intermediates.forEach(exact);exact(entry.derivation);}
function fixture(prompt:string,unit:Fixture["unit"],structure:Structure,publicTokens:readonly string[],derivation:MathExpression,intermediates:readonly MathExpression[],steps:readonly string[]):Fixture{const result={prompt:prompt.normalize("NFC"),unit,structure,publicTokens,derivation,intermediates,steps:steps.map(step=>step.normalize("NFC"))} as const;assertFixture(result);return result;}
function buildFixtures():readonly Fixture[]{const out:Fixture[]=[];
  ([[12,1,3,2],[15,2,4,3],[18,1,5,4],[21,2,6,5]] as const).forEach(([a,b,c,d])=>{const speed=v(a,b),time=v(c,d),distance=op("MULTIPLY",speed,time);out.push(fixture(`Một vật chuyển động đều với vận tốc ${a}/${b} km/giờ trong ${c}/${d} giờ. Quãng đường đi được là bao nhiêu km?`,"km","MOTION_DISTANCE",[`${a}/${b}`,`${c}/${d}`],distance,[speed,distance],["Xác định vận tốc và thời gian cùng hệ đơn vị.",`Nhân vận tốc với thời gian, được ${exact(distance)} km.`]));});
  ([[30,1,8,1,5,2],[45,1,9,1,7,2],[60,1,12,1,11,3],[75,1,15,2,8,3]] as const).forEach(([t,td,s,sd,a,b])=>{const travelled=op("MULTIPLY",v(s,sd),v(a,b)),remain=op("SUBTRACT",v(t,td),travelled);out.push(fixture(`Một tuyến dài ${t}/${td} km. Một xe đã đi ${a}/${b} giờ với vận tốc ${s}/${sd} km/giờ. Tuyến còn lại bao nhiêu km?`,"km","MOTION_REMAINDER",[`${t}/${td}`,`${a}/${b}`,`${s}/${sd}`],remain,[travelled,remain],[`Quãng đã đi là ${exact(travelled)} km.`,`Lấy độ dài tuyến trừ quãng đã đi, còn ${exact(remain)} km.`]));});
  ([[3,2,5,3,7,4],[7,4,9,5,11,6],[5,3,13,6,8,3],[9,4,7,3,10,3]] as const).forEach(([a,b,c,d,e,f])=>{const first=op("ADD",v(a,b),v(c,d)),total=op("ADD",first,v(e,f));out.push(fixture(`Một tuyến đo gồm ba đoạn dài ${a}/${b} m, ${c}/${d} m và ${e}/${f} m. Tổng chiều dài là bao nhiêu m?`,"m","THREE_SEGMENT_TOTAL",[`${a}/${b}`,`${c}/${d}`,`${e}/${f}`],total,[first,total],[`Cộng hai đoạn đầu được ${exact(first)} m.`,`Cộng đoạn thứ ba, tổng là ${exact(total)} m.`]));});
  ([[20,1,7,3,5,2],[25,1,11,4,13,6],[30,1,17,5,19,4],[35,1,23,6,29,5]] as const).forEach(([a,b,c,d,e,f])=>{const afterFirst=op("SUBTRACT",v(a,b),v(c,d)),remain=op("SUBTRACT",afterFirst,v(e,f));out.push(fixture(`Một cuộn dây dài ${a}/${b} m, dùng lần lượt ${c}/${d} m và ${e}/${f} m. Còn lại bao nhiêu m?`,"m","TWO_USE_REMAINDER",[`${a}/${b}`,`${c}/${d}`,`${e}/${f}`],remain,[afterFirst,remain],[`Sau lần dùng thứ nhất còn ${exact(afterFirst)} m.`,`Trừ tiếp lần dùng thứ hai, còn ${exact(remain)} m.`]));});
  ([[5,2,6,1,3,4],[7,3,9,2,5,6],[11,4,8,3,7,5],[13,5,10,3,9,4]] as const).forEach(([r,rd,count,cd,o,od])=>{const repeated=op("MULTIPLY",v(r,rd),v(count,cd)),total=op("ADD",repeated,v(o,od));out.push(fixture(`Một phép đo có ${count}/${cd} phần bằng nhau, mỗi phần dài ${r}/${rd} m, rồi cộng thêm đoạn ${o}/${od} m. Tổng độ dài là bao nhiêu m?`,"m","RATE_PLUS_OFFSET",[`${count}/${cd}`,`${r}/${rd}`,`${o}/${od}`],total,[repeated,total],[`Các phần bằng nhau dài tổng cộng ${exact(repeated)} m.`,`Cộng đoạn bổ sung, được ${exact(total)} m.`]));});
  ([[18,1,3,1,4,1],[25,1,5,1,6,1],[32,1,8,1,5,1],[40,1,10,1,7,1]] as const).forEach(([a,b,r,rd,g,gd])=>{const available=op("SUBTRACT",v(a,b),v(r,rd)),share=op("DIVIDE",available,v(g,gd));out.push(fixture(`Có ${a}/${b} m dây, giữ lại ${r}/${rd} m, phần còn lại chia đều thành ${g}/${gd} đoạn. Mỗi đoạn dài bao nhiêu m?`,"m","RESERVE_THEN_SHARE",[`${a}/${b}`,`${r}/${rd}`,`${g}/${gd}`],share,[available,share],[`Sau khi giữ lại còn ${exact(available)} m.`,`Chia đều phần còn lại, mỗi đoạn dài ${exact(share)} m.`]));});return out;}
const fixtures=buildFixtures();
type BigFraction=Readonly<{n:bigint;d:bigint}>;const gcd=(a:bigint,b:bigint):bigint=>b===0n?(a<0n?-a:a):gcd(b,a%b),frac=(n:bigint,d:bigint):BigFraction=>{if(d===0n)throw new Error("DIVISION_BY_ZERO");const sign=d<0n?-1n:1n,g=gcd(n,d);return{n:sign*n/g,d:sign*d/g};};
function independent(expression:MathExpression):BigFraction{if(expression.op==="VALUE")return frac(BigInt(expression.numerator),BigInt(expression.denominator));if(expression.op==="SQRT")throw new Error("UNSUPPORTED_ROOT");const l=independent(expression.left),r=independent(expression.right);if(expression.op==="ADD")return frac(l.n*r.d+r.n*l.d,l.d*r.d);if(expression.op==="SUBTRACT")return frac(l.n*r.d-r.n*l.d,l.d*r.d);if(expression.op==="MULTIPLY")return frac(l.n*r.n,l.d*r.d);return frac(l.n*r.d,l.d*r.n);}
export function verifyGradeSevenWaveHIndependentOracle(){return fixtures.flatMap((entry,index)=>{try{const result=independent(entry.derivation),expected=result.d===1n?String(result.n):`${result.n}/${result.d}`;return expected===exact(entry.derivation)?[]:[`g7-wave-h-${index+1}:INDEPENDENT_ORACLE_MISMATCH`];}catch{return[`g7-wave-h-${index+1}:INDEPENDENT_ORACLE_ERROR`];}});}
export function verifyGradeSevenWaveHMalformedFixtures(){const base=fixtures[0]!,bad:readonly Fixture[]=[{...base,prompt:"Thiếu dữ liệu công khai."},{...base,unit:"kg" as Fixture["unit"]},{...base,intermediates:[base.derivation]},{...base,derivation:op("DIVIDE",v(1),v(0))}];return bad.flatMap((entry,index)=>{try{assertFixture(entry);return[`g7-wave-h-malformed-${index+1}:ACCEPTED`];}catch(error){return error instanceof Error&&(error.message.startsWith("AUTOMATED_VERIFICATION_INSUFFICIENT")||error.message==="DIVISION_BY_ZERO"||error.message==="UNDEFINED_EXPRESSION")?[]:[`g7-wave-h-malformed-${index+1}:WRONG_ERROR`];}});}
const independentOracleErrors=verifyGradeSevenWaveHIndependentOracle(),malformedFixtureErrors=verifyGradeSevenWaveHMalformedFixtures();if(independentOracleErrors.length||malformedFixtureErrors.length)throw new Error(`GRADE_7_WAVE_H_ORACLE_FAILED:${[...independentOracleErrors,...malformedFixtureErrors]}`);
const purposes=["FOUNDATION","STANDARD_APPLICATION","MISCONCEPTION_TARGETING","REMEDIATION","TRANSFER_APPLICATION"] as const,difficulty=(index:number):DifficultyBand=>index%3===0?"FOUNDATIONAL":index%3===1?"CORE":"EXTENSION";const skeleton=buildOfficialGradeSkeleton(grade),receiptIds=requiredAutomatedEvidenceChecks.map(check=>`${packId}-${check.toLowerCase().replaceAll("_","-")}`);
const questions:CandidateQuestion[]=fixtures.map((entry,index)=>{const id=`g7-wave-h-${String(index+1).padStart(2,"0")}`;return{id,grade,unitId,blueprintId:`g7-wave-h-${difficulty(index).toLowerCase()}`,skillId,prompt:entry.prompt,options:null,answer:{type:"RATIONAL_INPUT",exactValue:exact(entry.derivation),unit:entry.unit,derivation:entry.derivation},explanationId:`${id}-explanation`,difficulty:difficulty(index),provenance:{kind:"DETERMINISTIC_TEMPLATE",templateVersion:"g7-applied-rational-wave-h-1.0.0",seed:`g7-wave-h-${entry.structure.toLowerCase()}-${index+1}`,sourceReferenceIds:[sourceId]},reviewStatus:"BUNDLED",published:false,pilotEligible:false,fixtureOnly:false,duplicateFingerprint:sha256(normalizedDefinition(`${entry.prompt}|`).toLocaleLowerCase("vi")),validationReceiptIds:receiptIds,instructionalPurpose:purposes[index%purposes.length]!};});
const explanations:ExplanationSpec[]=questions.map((question,index)=>({id:question.explanationId,questionId:question.id,steps:fixtures[index]!.steps,finalAnswer:question.answer.exactValue!,evidenceReceiptIds:[`${packId}-explanation-consistency`]}));const blueprints=(["FOUNDATIONAL","CORE","EXTENSION"] as const).map(band=>({id:`g7-wave-h-${band.toLowerCase()}`,grade,skillId,difficulty:band,questionType:"RATIONAL_INPUT" as const,templateId:"g7-applied-rational-wave-h-1.0.0",targetCount:8,sourceReferenceIds:[sourceId]}));
const evidenceReceipts=requiredAutomatedEvidenceChecks.map(check=>({id:`${packId}-${check.toLowerCase().replaceAll("_","-")}`,entityId:packId,check,status:"PASSED" as const,evidence:check==="SOURCE_MAPPING"?"Retained EXACT source outcome MOET2018-G7-NAA-P056-005, page 56.":check==="MATHEMATICAL_ANSWER"?`Independent BigInt rational oracle verified 24 questions across 6 structures; errors ${independentOracleErrors.length}; malformed errors ${malformedFixtureErrors.length}.`:`Deterministic Grade 7 Wave H ${check}.`}));const candidateCore={format:"plave-wave-h-candidate-v1",grade,candidateId,version,policyVersion,sourceOutcomeIds,blueprints,questions,explanations},bundleHash=sha256(canonicalize(candidateCore));
export const gradeSevenWaveHPack:GradePack={schemaVersion:"content-factory-grade-pack-v1",grade,packId,packVersion:version,immutableReference:false,testOnly:false,locale:"vi-VN",unicodeNormalization:"NFC",sources:[skeleton.source],domains:skeleton.domains,units:skeleton.units,knowledgeNodes:skeleton.knowledgeNodes,skills:skeleton.skills,objectives:skeleton.objectives,prerequisites:[{fromSkillId:"moet2018-g7-sta-p061-007",toSkillId:skillId,evidence:"HYPOTHESIS_REQUIRES_EVIDENCE",sourceReferenceIds:[]}],blueprints,questions,quarantinedQuestions:[],explanations,evidenceReceipts,candidate:{candidateId,version,bundleHash,policyVersion},adaptivePolicy:{version:policyVersion,status:"VALIDATED"},release:{publication:"DRAFT",visibility:"HIDDEN",pilotEnabled:false,runtimeEnabled:false,retentionEnabled:false},production:{wave:"H",selectedSliceId:"g7-applied-rational-problems",selectionBasis:["SOURCE_VERIFIED","PAGE_56_EXACT_ROW","PUBLIC_DATA_COMPLETE","UNIT_CONSISTENT","INDEPENDENT_BIGINT_RATIONAL_ORACLE","SIX_REASONING_STRUCTURES"],generated:24,repaired:0,evidenceGatePassed:24,verificationInsufficient:0,rejected:0,duplicate:0,candidateEligible:24},legacyAsset:null};
export const gradeSevenWaveHMetadata=Object.freeze({schemaVersion:"plave-wave-h-metadata-v1",wave:"H",grade,title:"Bài toán thực tiễn với số hữu tỉ",sourceClassification:"EXACT",sourcePages:[56] as const,sourceOutcomeIds,prerequisiteOutcomeIds,prerequisiteEvidence:"NOT_SPECIFIED_BY_SOURCE_INVENTORY",progressionHypothesis:{fromOutcomeId:"MOET2018-G7-STA-P061-007",toOutcomeId:sourceOutcomeIds[0],evidence:"HYPOTHESIS_REQUIRES_EVIDENCE"},reasoningStructures:[...new Set(fixtures.map(entry=>entry.structure))],deferredOutcomeIds:["MOET2018-G7-EXP-P062-002"] as const,deferredReason:"AUTOMATED_VERIFICATION_INSUFFICIENT",independentOracleErrors,malformedFixtureErrors,production:gradeSevenWaveHPack.production,candidate:gradeSevenWaveHPack.candidate,release:gradeSevenWaveHPack.release});
export const gradeSevenWavesABCDEFGH=Object.freeze({grade,packs:[gradeSevenWaveAPack,gradeSevenWaveBPack,gradeSevenWaveCPack,gradeSevenWaveDPack,gradeSevenWaveEPack,gradeSevenWaveFPack,gradeSevenWaveGPack,gradeSevenWaveHPack] as const,questions:[...gradeSevenWaveAPack.questions,...gradeSevenWaveBPack.questions,...gradeSevenWaveCPack.questions,...gradeSevenWaveDPack.questions,...gradeSevenWaveEPack.questions,...gradeSevenWaveFPack.questions,...gradeSevenWaveGPack.questions,...gradeSevenWaveHPack.questions],candidateBindings:[gradeSevenWaveAPack.candidate,gradeSevenWaveBPack.candidate,gradeSevenWaveCPack.candidate,gradeSevenWaveDPack.candidate,gradeSevenWaveEPack.candidate,gradeSevenWaveFPack.candidate,gradeSevenWaveGPack.candidate,gradeSevenWaveHPack.candidate],release:gradeSevenWaveHPack.release});
