import { canonicalize, normalizedDefinition, sha256 } from "./canonical.ts";
import { evaluateExpression } from "./math.ts";
import { buildOfficialGradeSkeleton, officialSkillId, officialSourceReferenceId } from "./official-source-map.ts";
import { requiredAutomatedEvidenceChecks } from "./review.ts";
import type { CandidateQuestion, DifficultyBand, ExplanationSpec, GradePack, MathExpression } from "./types.ts";

const grade=5 as const,sourceId=officialSourceReferenceId(grade),unitId="grade-5-applied-problem-solving";
const packId="grade-5-wave-h-multistep-natural-applications",candidateId="g5-multistep-natural-applications-wave-h",version="g5-multistep-natural-applications-1.0.0-wave-h",policyVersion="g5-applied-natural-policy-1.0.0-wave-h";
const sliceOutcomes=["MOET2018-G5-NUM-P040-002"] as const,prerequisiteOutcomeIds=["MOET2018-G5-NUM-P040-003"] as const,nextTargetOutcomeIds=["MOET2018-G5-NUM-P042-015"] as const;
const value=(numerator:number,denominator=1):MathExpression=>({op:"VALUE",numerator,denominator});
const operation=(op:"ADD"|"SUBTRACT"|"MULTIPLY"|"DIVIDE",left:MathExpression,right:MathExpression):MathExpression=>({op,left,right});
const purposes=["FOUNDATION","STANDARD_APPLICATION","MISCONCEPTION_TARGETING","REMEDIATION","TRANSFER_APPLICATION"] as const;
const receiptIds=requiredAutomatedEvidenceChecks.map((check)=>`${packId}-${check.toLowerCase().replaceAll("_","-")}`);
type Context="INVENTORY"|"BUDGET"|"PRODUCTION"|"DISTANCE"|"DISTRIBUTION"|"PACKING";
type Structure="MULTIPLY_SUBTRACT"|"BUDGET_CHANGE"|"PRODUCTION_ADJUSTMENT"|"DISTANCE_REMAINDER"|"RESERVE_THEN_SHARE"|"COMBINE_RESERVE_PACK";
type Fixture=Readonly<{prompt:string;unit:string;context:Context;structure:Structure;publicTokens:readonly string[];derivation:MathExpression;intermediates:readonly Readonly<{expression:MathExpression;exactValue:string}>[];steps:readonly string[]}>;
type GeneratedItem=Readonly<{question:CandidateQuestion;explanation:ExplanationSpec}>;
const allowedUnits=new Set(["sản phẩm","nghìn đồng","m","quyển","thùng"]);

function exactInteger(expression:MathExpression){try{const result=evaluateExpression(expression);if(result.denominator!==1||result.numerator<0)throw new Error("AUTOMATED_VERIFICATION_INSUFFICIENT:NON_INTEGER_OR_NEGATIVE_RESULT");return String(result.numerator);}catch(error){if(error instanceof Error&&error.message.startsWith("AUTOMATED_VERIFICATION_INSUFFICIENT"))throw error;throw new Error("AUTOMATED_VERIFICATION_INSUFFICIENT:INVALID_EXPRESSION");}}
function assertFixture(entry:Fixture){
  if(!allowedUnits.has(entry.unit)||!entry.prompt.includes(entry.unit))throw new Error("AUTOMATED_VERIFICATION_INSUFFICIENT:UNIT_OR_CONTEXT_MISMATCH");
  if(!entry.context||!entry.structure||entry.publicTokens.length===0||entry.publicTokens.some((token)=>!entry.prompt.includes(token)))throw new Error("AUTOMATED_VERIFICATION_INSUFFICIENT:PUBLIC_DATA_INCOMPLETE");
  if(entry.intermediates.length<2||entry.intermediates.length>4||entry.steps.length<2)throw new Error("AUTOMATED_VERIFICATION_INSUFFICIENT:INTERMEDIATE_STRUCTURE_INVALID");
  for(const intermediate of entry.intermediates)if(exactInteger(intermediate.expression)!==intermediate.exactValue)throw new Error("AUTOMATED_VERIFICATION_INSUFFICIENT:INTERMEDIATE_OPERATION_MISMATCH");
  exactInteger(entry.derivation);
}
function fixture(prompt:string,unit:string,context:Context,structure:Structure,publicTokens:readonly string[],derivation:MathExpression,intermediates:Fixture["intermediates"],steps:readonly string[]):Fixture{const result={prompt:prompt.normalize("NFC"),unit,context,structure,publicTokens,derivation,intermediates,steps:steps.map((step)=>step.normalize("NFC"))} as const;assertFixture(result);return result;}

function buildFixtures():readonly Fixture[]{const fixtures:Fixture[]=[];
  const inventory=[[8,45,37],[12,32,54],[15,28,65],[9,56,73]] as const;
  inventory.forEach(([groups,each,used])=>{const total=operation("MULTIPLY",value(groups),value(each)),answer=operation("SUBTRACT",total,value(used));fixtures.push(fixture(`Kho nhận ${groups} lô, mỗi lô ${each} sản phẩm, rồi xuất ${used} sản phẩm. Kho còn bao nhiêu sản phẩm?`,"sản phẩm","INVENTORY","MULTIPLY_SUBTRACT",[String(groups),String(each),String(used)],answer,[{expression:total,exactValue:exactInteger(total)},{expression:answer,exactValue:exactInteger(answer)}],[`Tổng nhập là ${groups} × ${each} = ${exactInteger(total)} sản phẩm.`,`Trừ ${used} sản phẩm đã xuất.`,`Kho còn ${exactInteger(answer)} sản phẩm.`]));});
  const budgets=[[500,6,55,20],[800,8,75,35],[1000,12,65,40],[1500,15,80,75]] as const;
  budgets.forEach(([budget,quantity,price,fee])=>{const itemCost=operation("MULTIPLY",value(quantity),value(price)),totalCost=operation("ADD",itemCost,value(fee)),answer=operation("SUBTRACT",value(budget),totalCost);fixtures.push(fixture(`Có ${budget} nghìn đồng, mua ${quantity} món giá ${price} nghìn đồng mỗi món và trả thêm ${fee} nghìn đồng phí. Còn bao nhiêu nghìn đồng?`,"nghìn đồng","BUDGET","BUDGET_CHANGE",[String(budget),String(quantity),String(price),String(fee)],answer,[{expression:itemCost,exactValue:exactInteger(itemCost)},{expression:totalCost,exactValue:exactInteger(totalCost)},{expression:answer,exactValue:exactInteger(answer)}],[`Tiền hàng là ${exactInteger(itemCost)} nghìn đồng.`,`Cộng phí được ${exactInteger(totalCost)} nghìn đồng.`,`Còn ${exactInteger(answer)} nghìn đồng.`]));});
  const production=[[5,120,35,18],[6,95,42,27],[7,88,50,34],[8,75,64,29]] as const;
  production.forEach(([days,daily,extra,defective])=>{const regular=operation("MULTIPLY",value(days),value(daily)),beforeCheck=operation("ADD",regular,value(extra)),answer=operation("SUBTRACT",beforeCheck,value(defective));fixtures.push(fixture(`Xưởng làm ${days} ngày, mỗi ngày ${daily} sản phẩm, làm thêm ${extra} sản phẩm rồi loại ${defective} sản phẩm lỗi. Còn bao nhiêu sản phẩm đạt yêu cầu?`,"sản phẩm","PRODUCTION","PRODUCTION_ADJUSTMENT",[String(days),String(daily),String(extra),String(defective)],answer,[{expression:regular,exactValue:exactInteger(regular)},{expression:beforeCheck,exactValue:exactInteger(beforeCheck)},{expression:answer,exactValue:exactInteger(answer)}],[`Sản lượng thường là ${exactInteger(regular)} sản phẩm.`,`Cộng phần thêm được ${exactInteger(beforeCheck)}, rồi loại hàng lỗi.`,`Còn ${exactInteger(answer)} sản phẩm.`]));});
  const distances=[[1000,6,120,85],[1500,8,140,120],[2000,9,180,155],[2500,12,175,190]] as const;
  distances.forEach(([goal,segments,length,extra])=>{const segmentDistance=operation("MULTIPLY",value(segments),value(length)),travelled=operation("ADD",segmentDistance,value(extra)),answer=operation("SUBTRACT",value(goal),travelled);fixtures.push(fixture(`Quãng đường dài ${goal} m. Đã đi ${segments} chặng, mỗi chặng ${length} m, rồi đi thêm ${extra} m. Còn bao nhiêu m?`,"m","DISTANCE","DISTANCE_REMAINDER",[String(goal),String(segments),String(length),String(extra)],answer,[{expression:segmentDistance,exactValue:exactInteger(segmentDistance)},{expression:travelled,exactValue:exactInteger(travelled)},{expression:answer,exactValue:exactInteger(answer)}],[`Các chặng dài ${exactInteger(segmentDistance)} m.`,`Cộng đoạn thêm được ${exactInteger(travelled)} m.`,`Còn ${exactInteger(answer)} m.`]));});
  const distributions=[[480,80,10],[750,150,12],[960,120,14],[1320,120,15]] as const;
  distributions.forEach(([total,reserve,groups])=>{const available=operation("SUBTRACT",value(total),value(reserve)),answer=operation("DIVIDE",available,value(groups));fixtures.push(fixture(`Có ${total} quyển, giữ lại ${reserve} quyển, số còn lại chia đều cho ${groups} lớp. Mỗi lớp nhận bao nhiêu quyển?`,"quyển","DISTRIBUTION","RESERVE_THEN_SHARE",[String(total),String(reserve),String(groups)],answer,[{expression:available,exactValue:exactInteger(available)},{expression:answer,exactValue:exactInteger(answer)}],[`Sau khi giữ lại còn ${exactInteger(available)} quyển.`,`Chia đều cho ${groups} lớp.`,`Mỗi lớp nhận ${exactInteger(answer)} quyển.`]));});
  const packing=[[4,60,3,40,40,20],[5,72,4,48,72,24],[6,80,5,50,70,30],[8,75,6,50,100,40]] as const;
  packing.forEach(([aGroups,aEach,bGroups,bEach,reserve,perBox])=>{const first=operation("MULTIPLY",value(aGroups),value(aEach)),second=operation("MULTIPLY",value(bGroups),value(bEach)),combined=operation("ADD",first,second),available=operation("SUBTRACT",combined,value(reserve)),answer=operation("DIVIDE",available,value(perBox));fixtures.push(fixture(`Đợt một có ${aGroups} nhóm, mỗi nhóm ${aEach} sản phẩm; đợt hai có ${bGroups} nhóm, mỗi nhóm ${bEach} sản phẩm. Giữ lại ${reserve} sản phẩm, đóng ${perBox} sản phẩm mỗi thùng. Được bao nhiêu thùng?`,"thùng","PACKING","COMBINE_RESERVE_PACK",[String(aGroups),String(aEach),String(bGroups),String(bEach),String(reserve),String(perBox)],answer,[{expression:first,exactValue:exactInteger(first)},{expression:second,exactValue:exactInteger(second)},{expression:available,exactValue:exactInteger(available)},{expression:answer,exactValue:exactInteger(answer)}],[`Hai đợt có ${exactInteger(first)} và ${exactInteger(second)} sản phẩm.`,`Gộp rồi giữ lại ${reserve}, còn ${exactInteger(available)} sản phẩm.`,`Đóng được ${exactInteger(answer)} thùng.`]));});
  return fixtures;}
const fixtures=buildFixtures();

export function verifyGradeFiveWaveHMalformedFixtures(){const base=fixtures[0]!;const malformed:readonly Fixture[]=[{...base,prompt:"Thiếu số lượng công khai.",publicTokens:["8"]},{...base,unit:"USD"},{...base,intermediates:[{...base.intermediates[0]!,exactValue:"999"},...base.intermediates.slice(1)]},{...base,derivation:operation("DIVIDE",value(1),value(0))}];return malformed.flatMap((entry,index)=>{try{assertFixture(entry);return[`g5-wave-h-malformed-${index+1}:ACCEPTED`];}catch(error){return error instanceof Error&&error.message.startsWith("AUTOMATED_VERIFICATION_INSUFFICIENT")?[]:[`g5-wave-h-malformed-${index+1}:WRONG_ERROR`];}});}
const malformedFixtureErrors=verifyGradeFiveWaveHMalformedFixtures();if(malformedFixtureErrors.length)throw new Error(`GRADE_5_WAVE_H_MALFORMED_FIXTURE_FAILURE:${malformedFixtureErrors.join(",")}`);
function difficulty(index:number):DifficultyBand{const position=index%6;return position<2?"FOUNDATIONAL":position<4?"CORE":"EXTENSION";}
const generated:readonly GeneratedItem[]=fixtures.map((entry,index)=>{assertFixture(entry);const suffix=String(index+1).padStart(2,"0"),id=`g5-wave-h-${suffix}`,explanationId=`${id}-explanation`,answer=exactInteger(entry.derivation);return{question:{id,grade,unitId,blueprintId:`g5-wave-h-blueprint-${sliceOutcomes[0].toLowerCase()}-${difficulty(index).toLowerCase()}`,skillId:officialSkillId(sliceOutcomes[0]),prompt:entry.prompt,options:null,answer:{type:"INTEGER_INPUT",exactValue:answer,unit:entry.unit,derivation:entry.derivation},explanationId,difficulty:difficulty(index),provenance:{kind:"DETERMINISTIC_TEMPLATE",templateVersion:"g5-multistep-natural-wave-h-template-1.0.0",seed:`g5-wave-h-${entry.structure.toLowerCase()}-${suffix}`,sourceReferenceIds:[sourceId]},reviewStatus:"BUNDLED",published:false,pilotEligible:false,fixtureOnly:false,duplicateFingerprint:sha256(normalizedDefinition(`${entry.prompt}|`).toLocaleLowerCase("vi")),validationReceiptIds:receiptIds,instructionalPurpose:purposes[index%purposes.length]!},explanation:{id:explanationId,questionId:id,steps:entry.steps,finalAnswer:answer,evidenceReceiptIds:[`${packId}-explanation-consistency`]}};});
const questions=generated.map((entry)=>entry.question),explanations=generated.map((entry)=>entry.explanation);

type BigFraction=Readonly<{numerator:bigint;denominator:bigint}>;const bgcd=(a:bigint,b:bigint):bigint=>b===0n?(a<0n?-a:a):bgcd(b,a%b);const bf=(n:bigint,d:bigint):BigFraction=>{if(d===0n)throw new Error("DIVISION_BY_ZERO");const sign=d<0n?-1n:1n,divisor=bgcd(n,d);return{numerator:sign*n/divisor,denominator:sign*d/divisor};};
function independentlyEvaluate(expression:MathExpression):BigFraction{if(expression.op==="VALUE")return bf(BigInt(expression.numerator),BigInt(expression.denominator));if(expression.op==="SQRT")throw new Error("UNSUPPORTED_ROOT");const l=independentlyEvaluate(expression.left),r=independentlyEvaluate(expression.right);if(expression.op==="ADD")return bf(l.numerator*r.denominator+r.numerator*l.denominator,l.denominator*r.denominator);if(expression.op==="SUBTRACT")return bf(l.numerator*r.denominator-r.numerator*l.denominator,l.denominator*r.denominator);if(expression.op==="MULTIPLY")return bf(l.numerator*r.numerator,l.denominator*r.denominator);return bf(l.numerator*r.denominator,l.denominator*r.numerator);}
export function verifyGradeFiveWaveHIndependentOracle(){return questions.flatMap((question)=>{const expression=question.answer.derivation;if(!expression)return[`${question.id}:MISSING_DERIVATION`];try{const result=independentlyEvaluate(expression);return result.denominator===1n&&String(result.numerator)===question.answer.exactValue?[]:[`${question.id}:INDEPENDENT_ORACLE_MISMATCH`];}catch{return[`${question.id}:INDEPENDENT_ORACLE_ERROR`];}});}
const independentOracleErrors=verifyGradeFiveWaveHIndependentOracle();if(independentOracleErrors.length)throw new Error(`GRADE_5_WAVE_H_ORACLE_FAILURE:${independentOracleErrors.join(",")}`);
const skeleton=buildOfficialGradeSkeleton(grade),evidenceReceipts=requiredAutomatedEvidenceChecks.map((check)=>({id:`${packId}-${check.toLowerCase().replaceAll("_","-")}`,entityId:packId,check,status:"PASSED" as const,evidence:check==="SOURCE_MAPPING"?`Retained source-locked outcome ${sliceOutcomes[0]} on pages 40–41.`:check==="MATHEMATICAL_ANSWER"?`Independent BigInt oracle verifies ${questions.length} exact answers across ${new Set(fixtures.map((entry)=>entry.structure)).size} structures; oracle errors ${independentOracleErrors.length}, malformed errors ${malformedFixtureErrors.length}.`:`Deterministic Grade 5 Wave H ${check.toLowerCase().replaceAll("_"," ")} receipt.`}));
const blueprints=(["FOUNDATIONAL","CORE","EXTENSION"] as const).map((band)=>({id:`g5-wave-h-blueprint-${sliceOutcomes[0].toLowerCase()}-${band.toLowerCase()}`,grade,skillId:officialSkillId(sliceOutcomes[0]),difficulty:band,questionType:"INTEGER_INPUT" as const,templateId:`g5-wave-h-template-${sliceOutcomes[0].toLowerCase()}`,targetCount:8,sourceReferenceIds:[sourceId]}));
const candidateCore={format:"plave-wave-h-candidate-v1",candidateId,version,policyVersion,sourceOutcomeIds:sliceOutcomes,blueprints,questions,explanations} as const;export const gradeFiveWaveHBundleHash=sha256(canonicalize(candidateCore));
export function createGradeFiveWaveHPack():GradePack{return{schemaVersion:"content-factory-grade-pack-v1",grade,packId,packVersion:version,immutableReference:false,testOnly:false,locale:"vi-VN",unicodeNormalization:"NFC",sources:[skeleton.source],domains:skeleton.domains,units:skeleton.units,knowledgeNodes:skeleton.knowledgeNodes,skills:skeleton.skills,objectives:skeleton.objectives,prerequisites:[{fromSkillId:officialSkillId(prerequisiteOutcomeIds[0]),toSkillId:officialSkillId(sliceOutcomes[0]),evidence:"HYPOTHESIS_REQUIRES_EVIDENCE",sourceReferenceIds:[]},{fromSkillId:officialSkillId(sliceOutcomes[0]),toSkillId:officialSkillId(nextTargetOutcomeIds[0]),evidence:"HYPOTHESIS_REQUIRES_EVIDENCE",sourceReferenceIds:[]}],blueprints,questions,quarantinedQuestions:[],explanations,evidenceReceipts,candidate:{candidateId,version,bundleHash:gradeFiveWaveHBundleHash,policyVersion},adaptivePolicy:{version:policyVersion,status:"VALIDATED"},release:{publication:"DRAFT",visibility:"HIDDEN",pilotEnabled:false,runtimeEnabled:false,retentionEnabled:false},production:{wave:"H",selectedSliceId:"g5-multistep-natural-applications",selectionBasis:["SOURCE_VERIFIED","UNCOVERED_BY_WAVES_A_TO_G","PUBLIC_DATA_COMPLETE","UP_TO_FOUR_INTERMEDIATE_OPERATIONS","INDEPENDENT_BIGINT_ORACLE","SIX_REASONING_STRUCTURES"],generated:24,repaired:0,evidenceGatePassed:24,verificationInsufficient:0,rejected:0,duplicate:0,candidateEligible:24},legacyAsset:null};}
export const gradeFiveWaveHPack=createGradeFiveWaveHPack();
export const gradeFiveWaveHMetadata={schemaVersion:"plave-wave-h-metadata-v1",wave:"H",grade,title:"Bài toán số tự nhiên nhiều bước",sourceClassification:"SOURCE_VERIFIED",sourcePages:[40,41],sourceOutcomeIds:sliceOutcomes,prerequisiteOutcomeIds,prerequisiteEvidence:"HYPOTHESIS_REQUIRES_EVIDENCE",nextTargetOutcomeIds,nextTargetEvidence:"HYPOTHESIS_REQUIRES_EVIDENCE",reasoningStructures:[...new Set(fixtures.map((entry)=>entry.structure))],independentOracleErrors,malformedFixtureErrors,production:gradeFiveWaveHPack.production,candidate:gradeFiveWaveHPack.candidate,release:gradeFiveWaveHPack.release} as const;
