import { canonicalize, normalizedDefinition, sha256 } from "./canonical.ts";
import { gradeEightWaveAPack } from "./grade8-wave-a.ts"; import { gradeEightWaveBPack } from "./grade8-wave-b.ts"; import { gradeEightWaveCPack } from "./grade8-wave-c.ts"; import { gradeEightWaveDPack } from "./grade8-wave-d.ts"; import { gradeEightWaveEPack } from "./grade8-wave-e.ts"; import { gradeEightWaveFPack } from "./grade8-wave-f.ts"; import { gradeEightWaveGPack } from "./grade8-wave-g.ts";
import { evaluateExpression } from "./math.ts"; import { buildOfficialGradeSkeleton, officialSourceReferenceId } from "./official-source-map.ts"; import { requiredAutomatedEvidenceChecks } from "./review.ts"; import type { CandidateQuestion,DifficultyBand,ExplanationSpec,GradePack,MathExpression } from "./types.ts";

const grade=8 as const,sourceId=officialSourceReferenceId(grade),unitId="grade-8-secondary-naa-p1-5",skillId="moet2018-g8-naa-p065-025";
const packId="grade-8-applied-linear-motion-wave-h",candidateId="g8-applied-linear-motion-wave-h-rc1",version="g8-applied-linear-motion-1.0.0-wave-h",policyVersion="g8-applied-linear-motion-policy-1.0.0-wave-h";
const sourceOutcomeIds=["MOET2018-G8-NAA-P065-025"] as const,prerequisiteOutcomeIds=[] as const;
const v=(n:number):MathExpression=>({op:"VALUE",numerator:n,denominator:1}),op=(kind:"ADD"|"SUBTRACT"|"MULTIPLY"|"DIVIDE",left:MathExpression,right:MathExpression):MathExpression=>({op:kind,left,right});
type Structure="AFFINE_POSITION"|"INVERSE_ELAPSED_TIME"|"TWO_STAGE_DISTANCE"|"OPPOSITE_DIRECTION_MEETING"|"SAME_DIRECTION_CATCH_UP"|"POSITION_DIFFERENCE";
type Fixture=Readonly<{prompt:string;unit:"km"|"giờ";structure:Structure;publicTokens:readonly string[];derivation:MathExpression;intermediates:readonly MathExpression[];steps:readonly string[];positiveInputs:readonly number[]}>;
const exactInteger=(expression:MathExpression)=>{const result=evaluateExpression(expression);if(result.denominator!==1||result.numerator<0)throw new Error("AUTOMATED_VERIFICATION_INSUFFICIENT:NON_INTEGER_OR_NEGATIVE_RESULT");return String(result.numerator);};
function assertFixture(entry:Fixture){if(!entry.prompt.includes(entry.unit))throw new Error("AUTOMATED_VERIFICATION_INSUFFICIENT:UNIT_OR_CONTEXT_MISMATCH");if(entry.positiveInputs.some(value=>value<=0))throw new Error("AUTOMATED_VERIFICATION_INSUFFICIENT:DOMAIN_VIOLATION");if(entry.publicTokens.length<3||entry.publicTokens.some(token=>!entry.prompt.includes(token)))throw new Error("AUTOMATED_VERIFICATION_INSUFFICIENT:PUBLIC_DATA_INCOMPLETE");if(entry.intermediates.length<2||entry.intermediates.length>4||entry.steps.length<2)throw new Error("AUTOMATED_VERIFICATION_INSUFFICIENT:INTERMEDIATE_STRUCTURE_INVALID");entry.intermediates.forEach(exactInteger);exactInteger(entry.derivation);}
function fixture(prompt:string,unit:Fixture["unit"],structure:Structure,publicTokens:readonly string[],derivation:MathExpression,intermediates:readonly MathExpression[],steps:readonly string[],positiveInputs:readonly number[]):Fixture{const result={prompt:prompt.normalize("NFC"),unit,structure,publicTokens,derivation,intermediates,steps:steps.map(step=>step.normalize("NFC")),positiveInputs} as const;assertFixture(result);return result;}
function buildFixtures():readonly Fixture[]{const out:Fixture[]=[];
  ([[42,3,8],[48,4,6],[55,2,10],[60,5,7]] as const).forEach(([speed,time,offset])=>{const travelled=op("MULTIPLY",v(speed),v(time)),position=op("ADD",v(offset),travelled);out.push(fixture(`Vị trí ban đầu của xe là mốc ${offset} km. Xe đi đều với vận tốc ${speed} km/giờ trong ${time} giờ. Vị trí mới ở mốc bao nhiêu km?`,"km","AFFINE_POSITION",[String(offset),String(speed),String(time)],position,[travelled,position],[`Quãng đường tăng thêm là ${exactInteger(travelled)} km.`,`Cộng mốc ban đầu, vị trí mới là ${exactInteger(position)} km.`],[speed,time,offset]));});
  ([[45,10,190],[50,20,220],[60,15,255],[72,24,312]] as const).forEach(([speed,offset,target])=>{const change=op("SUBTRACT",v(target),v(offset)),time=op("DIVIDE",change,v(speed));out.push(fixture(`Một xe xuất phát tại mốc ${offset} km, đi đều ${speed} km/giờ và cần tới mốc ${target} km. Xe đi trong bao nhiêu giờ?`,"giờ","INVERSE_ELAPSED_TIME",[String(offset),String(speed),String(target)],time,[change,time],[`Quãng đường cần đi là ${exactInteger(change)} km.`,`Chia quãng đường cho vận tốc, thời gian là ${exactInteger(time)} giờ.`],[speed,offset,target]));});
  ([[40,2,55,3],[36,4,48,2],[50,3,65,2],[45,2,60,4]] as const).forEach(([v1,t1,v2,t2])=>{const first=op("MULTIPLY",v(v1),v(t1)),second=op("MULTIPLY",v(v2),v(t2)),total=op("ADD",first,second);out.push(fixture(`Một hành trình gồm ${t1} giờ đi với ${v1} km/giờ rồi ${t2} giờ đi với ${v2} km/giờ. Tổng quãng đường là bao nhiêu km?`,"km","TWO_STAGE_DISTANCE",[String(t1),String(v1),String(t2),String(v2)],total,[first,second,total],[`Hai chặng dài ${exactInteger(first)} km và ${exactInteger(second)} km.`,`Cộng hai chặng, được ${exactInteger(total)} km.`],[v1,t1,v2,t2]));});
  ([[200,40,60],[250,50,75],[360,55,65],[420,60,80]] as const).forEach(([gap,v1,v2])=>{const closing=op("ADD",v(v1),v(v2)),time=op("DIVIDE",v(gap),closing);out.push(fixture(`Hai xe cách nhau ${gap} km, cùng khởi hành đi ngược chiều để gặp nhau với vận tốc ${v1} km/giờ và ${v2} km/giờ. Sau bao nhiêu giờ hai xe gặp nhau?`,"giờ","OPPOSITE_DIRECTION_MEETING",[String(gap),String(v1),String(v2)],time,[closing,time],[`Tốc độ khép khoảng cách là ${exactInteger(closing)} km/giờ.`,`Lấy khoảng cách chia tốc độ khép, được ${exactInteger(time)} giờ.`],[gap,v1,v2]));});
  ([[90,70,100],[120,65,95],[150,60,90],[180,75,105]] as const).forEach(([lead,slow,fast])=>{const relative=op("SUBTRACT",v(fast),v(slow)),time=op("DIVIDE",v(lead),relative);out.push(fixture(`Xe chậm đi trước ${lead} km với vận tốc ${slow} km/giờ. Xe nhanh đi sau cùng hướng với vận tốc ${fast} km/giờ. Xe nhanh đuổi kịp sau bao nhiêu giờ?`,"giờ","SAME_DIRECTION_CATCH_UP",[String(lead),String(slow),String(fast)],time,[relative,time],[`Vận tốc tương đối là ${exactInteger(relative)} km/giờ.`,`Lấy khoảng cách đi trước chia vận tốc tương đối, được ${exactInteger(time)} giờ.`],[lead,slow,fast]));});
  ([[80,50,65,20,4],[90,30,70,10,3],[75,40,55,10,5],[100,60,80,20,4]] as const).forEach(([v1,b1,v2,b2,t])=>{const p1=op("ADD",v(b1),op("MULTIPLY",v(v1),v(t))),p2=op("ADD",v(b2),op("MULTIPLY",v(v2),v(t))),difference=op("SUBTRACT",p1,p2);out.push(fixture(`Xe A ở mốc ${b1} km và đi ${v1} km/giờ; xe B ở mốc ${b2} km và đi ${v2} km/giờ cùng chiều. Sau ${t} giờ, vị trí A hơn vị trí B bao nhiêu km?`,"km","POSITION_DIFFERENCE",[String(b1),String(v1),String(b2),String(v2),String(t)],difference,[p1,p2,difference],[`Vị trí A và B lần lượt là ${exactInteger(p1)} km và ${exactInteger(p2)} km.`,`Lấy vị trí A trừ vị trí B, được ${exactInteger(difference)} km.`],[v1,b1,v2,b2,t]));});return out;}
const fixtures=buildFixtures();
type BigFraction=Readonly<{n:bigint;d:bigint}>;const gcd=(a:bigint,b:bigint):bigint=>b===0n?(a<0n?-a:a):gcd(b,a%b),frac=(n:bigint,d:bigint):BigFraction=>{if(d===0n)throw new Error("DIVISION_BY_ZERO");const sign=d<0n?-1n:1n,g=gcd(n,d);return{n:sign*n/g,d:sign*d/g};};function independent(expression:MathExpression):BigFraction{if(expression.op==="VALUE")return frac(BigInt(expression.numerator),BigInt(expression.denominator));if(expression.op==="SQRT")throw new Error("UNSUPPORTED_ROOT");const l=independent(expression.left),r=independent(expression.right);if(expression.op==="ADD")return frac(l.n*r.d+r.n*l.d,l.d*r.d);if(expression.op==="SUBTRACT")return frac(l.n*r.d-r.n*l.d,l.d*r.d);if(expression.op==="MULTIPLY")return frac(l.n*r.n,l.d*r.d);return frac(l.n*r.d,l.d*r.n);}
export function verifyGradeEightWaveHIndependentOracle(){return fixtures.flatMap((entry,index)=>{try{const result=independent(entry.derivation);return result.d===1n&&result.n>=0n&&String(result.n)===exactInteger(entry.derivation)?[]:[`g8-wave-h-${index+1}:INDEPENDENT_ORACLE_MISMATCH`];}catch{return[`g8-wave-h-${index+1}:INDEPENDENT_ORACLE_ERROR`];}});}
export function verifyGradeEightWaveHMalformedFixtures(){const base=fixtures[0]!,bad:readonly Fixture[]=[{...base,prompt:"Thiếu dữ liệu công khai."},{...base,unit:"kg" as Fixture["unit"]},{...base,positiveInputs:[0,...base.positiveInputs.slice(1)]},{...base,intermediates:[base.derivation]}];return bad.flatMap((entry,index)=>{try{assertFixture(entry);return[`g8-wave-h-malformed-${index+1}:ACCEPTED`];}catch(error){return error instanceof Error&&error.message.startsWith("AUTOMATED_VERIFICATION_INSUFFICIENT")?[]:[`g8-wave-h-malformed-${index+1}:WRONG_ERROR`];}});}
const independentOracleErrors=verifyGradeEightWaveHIndependentOracle(),malformedFixtureErrors=verifyGradeEightWaveHMalformedFixtures();if(independentOracleErrors.length||malformedFixtureErrors.length)throw new Error(`GRADE_8_WAVE_H_ORACLE_FAILED:${[...independentOracleErrors,...malformedFixtureErrors]}`);
const purposes=["FOUNDATION","STANDARD_APPLICATION","MISCONCEPTION_TARGETING","REMEDIATION","TRANSFER_APPLICATION"] as const,difficulty=(index:number):DifficultyBand=>index%3===0?"FOUNDATIONAL":index%3===1?"CORE":"EXTENSION",skeleton=buildOfficialGradeSkeleton(grade),receiptIds=requiredAutomatedEvidenceChecks.map(check=>`${packId}-${check.toLowerCase().replaceAll("_","-")}`);
const questions:CandidateQuestion[]=fixtures.map((entry,index)=>{const id=`g8-wave-h-${String(index+1).padStart(2,"0")}`;return{id,grade,unitId,blueprintId:`g8-wave-h-${difficulty(index).toLowerCase()}`,skillId,prompt:entry.prompt,options:null,answer:{type:"INTEGER_INPUT",exactValue:exactInteger(entry.derivation),unit:entry.unit,derivation:entry.derivation},explanationId:`${id}-explanation`,difficulty:difficulty(index),provenance:{kind:"DETERMINISTIC_TEMPLATE",templateVersion:"g8-applied-linear-motion-wave-h-1.0.0",seed:`g8-wave-h-${entry.structure.toLowerCase()}-${index+1}`,sourceReferenceIds:[sourceId]},reviewStatus:"BUNDLED",published:false,pilotEligible:false,fixtureOnly:false,duplicateFingerprint:sha256(normalizedDefinition(`${entry.prompt}|`).toLocaleLowerCase("vi")),validationReceiptIds:receiptIds,instructionalPurpose:purposes[index%purposes.length]!};});
const explanations:ExplanationSpec[]=questions.map((question,index)=>({id:question.explanationId,questionId:question.id,steps:fixtures[index]!.steps,finalAnswer:question.answer.exactValue!,evidenceReceiptIds:[`${packId}-explanation-consistency`]})),blueprints=(["FOUNDATIONAL","CORE","EXTENSION"] as const).map(band=>({id:`g8-wave-h-${band.toLowerCase()}`,grade,skillId,difficulty:band,questionType:"INTEGER_INPUT" as const,templateId:"g8-applied-linear-motion-wave-h-1.0.0",targetCount:8,sourceReferenceIds:[sourceId]}));
const evidenceReceipts=requiredAutomatedEvidenceChecks.map(check=>({id:`${packId}-${check.toLowerCase().replaceAll("_","-")}`,entityId:packId,check,status:"PASSED" as const,evidence:check==="SOURCE_MAPPING"?"Retained EXACT source outcome MOET2018-G8-NAA-P065-025, page 65.":check==="MATHEMATICAL_ANSWER"?`Independent BigInt oracle verified 24 applied linear-motion questions across 6 structures; errors ${independentOracleErrors.length}; malformed errors ${malformedFixtureErrors.length}.`:`Deterministic Grade 8 Wave H ${check}.`}));const candidateCore={format:"plave-wave-h-candidate-v1",grade,candidateId,version,policyVersion,sourceOutcomeIds,blueprints,questions,explanations},bundleHash=sha256(canonicalize(candidateCore));
export const gradeEightWaveHPack:GradePack={schemaVersion:"content-factory-grade-pack-v1",grade,packId,packVersion:version,immutableReference:false,testOnly:false,locale:"vi-VN",unicodeNormalization:"NFC",sources:[skeleton.source],domains:skeleton.domains,units:skeleton.units,knowledgeNodes:skeleton.knowledgeNodes,skills:skeleton.skills,objectives:skeleton.objectives,prerequisites:[{fromSkillId:"moet2018-g8-sta-p069-014",toSkillId:skillId,evidence:"HYPOTHESIS_REQUIRES_EVIDENCE",sourceReferenceIds:[]}],blueprints,questions,quarantinedQuestions:[],explanations,evidenceReceipts,candidate:{candidateId,version,bundleHash,policyVersion},adaptivePolicy:{version:policyVersion,status:"VALIDATED"},release:{publication:"DRAFT",visibility:"HIDDEN",pilotEnabled:false,runtimeEnabled:false,retentionEnabled:false},production:{wave:"H",selectedSliceId:"g8-applied-linear-motion",selectionBasis:["SOURCE_VERIFIED","PAGE_65_EXACT_ROW","PUBLIC_DATA_COMPLETE","UNIT_AND_DOMAIN_VALIDATED","INDEPENDENT_BIGINT_ORACLE","SIX_REASONING_STRUCTURES"],generated:24,repaired:0,evidenceGatePassed:24,verificationInsufficient:0,rejected:0,duplicate:0,candidateEligible:24},legacyAsset:null};
export const gradeEightWaveHMetadata=Object.freeze({schemaVersion:"plave-wave-h-metadata-v1",wave:"H",grade,title:"Vận dụng hàm số bậc nhất vào chuyển động",sourceClassification:"EXACT",sourcePages:[65] as const,sourceOutcomeIds,prerequisiteOutcomeIds,prerequisiteEvidence:"NOT_SPECIFIED_BY_SOURCE_INVENTORY",progressionHypothesis:{fromOutcomeId:"MOET2018-G8-STA-P069-014",toOutcomeId:sourceOutcomeIds[0],evidence:"HYPOTHESIS_REQUIRES_EVIDENCE"},reasoningStructures:[...new Set(fixtures.map(entry=>entry.structure))],deferredOutcomeIds:["MOET2018-G8-EXP-P070-008"] as const,deferredReason:"AUTOMATED_VERIFICATION_INSUFFICIENT",independentOracleErrors,malformedFixtureErrors,production:gradeEightWaveHPack.production,candidate:gradeEightWaveHPack.candidate,release:gradeEightWaveHPack.release});
export const gradeEightWavesABCDEFGH=Object.freeze({grade,packs:[gradeEightWaveAPack,gradeEightWaveBPack,gradeEightWaveCPack,gradeEightWaveDPack,gradeEightWaveEPack,gradeEightWaveFPack,gradeEightWaveGPack,gradeEightWaveHPack] as const,questions:[...gradeEightWaveAPack.questions,...gradeEightWaveBPack.questions,...gradeEightWaveCPack.questions,...gradeEightWaveDPack.questions,...gradeEightWaveEPack.questions,...gradeEightWaveFPack.questions,...gradeEightWaveGPack.questions,...gradeEightWaveHPack.questions],candidateBindings:[gradeEightWaveAPack.candidate,gradeEightWaveBPack.candidate,gradeEightWaveCPack.candidate,gradeEightWaveDPack.candidate,gradeEightWaveEPack.candidate,gradeEightWaveFPack.candidate,gradeEightWaveGPack.candidate,gradeEightWaveHPack.candidate],release:gradeEightWaveHPack.release});
