import { canonicalize, normalizedDefinition, sha256 } from "./canonical.ts";
import { evaluateExpression } from "./math.ts";
import { buildOfficialGradeSkeleton, officialSkillId, officialSourceReferenceId } from "./official-source-map.ts";
import { requiredAutomatedEvidenceChecks } from "./review.ts";
import type { CandidateQuestion, DifficultyBand, ExplanationSpec, GradePack, MathExpression } from "./types.ts";

const grade=6 as const,sourceId=officialSourceReferenceId(grade),unitId="grade-6-ratio-percent-decimal-p1";
const packId="grade-6-wave-h-applied-decimal-ratio-percent",candidateId="g6-applied-decimal-ratio-percent-wave-h",version="g6-applied-decimal-ratio-percent-1.0.0-wave-h",policyVersion="g6-applied-ratio-percent-policy-1.0.0-wave-h";
const sliceOutcomes=["MOET2018-G6-NAA-P050-044"] as const,prerequisiteOutcomeIds=["MOET2018-G6-NAA-P050-047"] as const,nextTargetOutcomeIds=["MOET2018-G6-NAA-P050-049"] as const;
const value=(numerator:number,denominator=1):MathExpression=>({op:"VALUE",numerator,denominator});
const operation=(op:"ADD"|"SUBTRACT"|"MULTIPLY"|"DIVIDE",left:MathExpression,right:MathExpression):MathExpression=>({op,left,right});
const purposes=["FOUNDATION","STANDARD_APPLICATION","MISCONCEPTION_TARGETING","REMEDIATION","TRANSFER_APPLICATION"] as const;
const receiptIds=requiredAutomatedEvidenceChecks.map((check)=>`${packId}-${check.toLowerCase().replaceAll("_","-")}`);
type Context="SOLUTION"|"PURCHASE"|"SIMPLE_INTEREST"|"RATIO_ALLOCATION"|"INVENTORY_CHANGE"|"COMBINED_SOLUTION";
type Structure="PERCENT_THEN_ADD"|"DISCOUNT_THEN_FEE"|"RATE_TIME_TOTAL"|"RATIO_THEN_SUBTRACT"|"PERCENT_INCREASE_THEN_SUBTRACT"|"TWO_PERCENT_PARTS_SUM";
type Fixture=Readonly<{prompt:string;unit:string;context:Context;structure:Structure;publicTokens:readonly string[];derivation:MathExpression;intermediates:readonly Readonly<{expression:MathExpression;exactValue:string}>[];steps:readonly string[]}>;
type GeneratedItem=Readonly<{question:CandidateQuestion;explanation:ExplanationSpec}>;
type Amount=Readonly<{expression:MathExpression;display:string}>;
const allowedUnits=new Set(["g","kg","nghìn đồng"]);

function exactDecimal(expression:MathExpression){try{const result=evaluateExpression(expression);if(result.numerator<0)throw new Error("AUTOMATED_VERIFICATION_INSUFFICIENT:NEGATIVE_CONTEXT_RESULT");if(result.denominator===1)return String(result.numerator);let denominator=result.denominator,twos=0,fives=0;while(denominator%2===0){denominator/=2;twos+=1;}while(denominator%5===0){denominator/=5;fives+=1;}if(denominator!==1)throw new Error("AUTOMATED_VERIFICATION_INSUFFICIENT:NON_TERMINATING_DECIMAL");const places=Math.max(twos,fives),scaled=result.numerator*(2**(places-twos))*(5**(places-fives)),digits=String(scaled).padStart(places+1,"0");return`${digits.slice(0,-places)}.${digits.slice(-places)}`.replace(/\.0+$/u,"").replace(/(\.\d*?)0+$/u,"$1");}catch(error){if(error instanceof Error&&error.message.startsWith("AUTOMATED_VERIFICATION_INSUFFICIENT"))throw error;throw new Error("AUTOMATED_VERIFICATION_INSUFFICIENT:INVALID_EXPRESSION");}}
const amount=(numerator:number,denominator=1):Amount=>{const expression=value(numerator,denominator);return{expression,display:exactDecimal(expression).replace(".",",")};};
function assertFixture(entry:Fixture){if(!allowedUnits.has(entry.unit)||!entry.prompt.includes(entry.unit)||!entry.context||!entry.structure)throw new Error("AUTOMATED_VERIFICATION_INSUFFICIENT:DOMAIN_UNIT_CONTEXT_MISMATCH");if(entry.publicTokens.length===0||entry.publicTokens.some((token)=>!entry.prompt.includes(token)))throw new Error("AUTOMATED_VERIFICATION_INSUFFICIENT:PUBLIC_DATA_INCOMPLETE");if(entry.intermediates.length<2||entry.intermediates.length>4||entry.steps.length<2)throw new Error("AUTOMATED_VERIFICATION_INSUFFICIENT:INTERMEDIATE_STRUCTURE_INVALID");for(const intermediate of entry.intermediates)if(exactDecimal(intermediate.expression)!==intermediate.exactValue)throw new Error("AUTOMATED_VERIFICATION_INSUFFICIENT:INTERMEDIATE_OPERATION_MISMATCH");exactDecimal(entry.derivation);}
function fixture(prompt:string,unit:string,context:Context,structure:Structure,publicTokens:readonly string[],derivation:MathExpression,intermediates:Fixture["intermediates"],steps:readonly string[]):Fixture{const result={prompt:prompt.normalize("NFC"),unit,context,structure,publicTokens,derivation,intermediates,steps:steps.map((step)=>step.normalize("NFC"))} as const;assertFixture(result);return result;}

function buildFixtures():readonly Fixture[]{const fixtures:Fixture[]=[];
  const solutions=[[amount(200),5,amount(3)],[amount(501,2),8,amount(3,2)],[amount(480),15,amount(4)],[amount(625),12,amount(5)]] as const;
  solutions.forEach(([total,percent,added])=>{const solute=operation("MULTIPLY",total.expression,value(percent,100)),answer=operation("ADD",solute,added.expression);fixtures.push(fixture(`Một dung dịch ${total.display} g chứa ${percent}% chất A, sau đó thêm ${added.display} g chất A. Khối lượng chất A là bao nhiêu g?`,"g","SOLUTION","PERCENT_THEN_ADD",[total.display,`${percent}%`,added.display],answer,[{expression:solute,exactValue:exactDecimal(solute)},{expression:answer,exactValue:exactDecimal(answer)}],[`Lượng chất A ban đầu là ${exactDecimal(solute).replace(".",",")} g.`,`Cộng ${added.display} g được thêm.`,`Có ${exactDecimal(answer).replace(".",",")} g chất A.`]));});
  const purchases=[[amount(1001,2),10,amount(20)],[amount(800),15,amount(25)],[amount(4803,4),20,amount(30)],[amount(1500),12,amount(40)]] as const;
  purchases.forEach(([price,discountPercent,fee])=>{const discount=operation("MULTIPLY",price.expression,value(discountPercent,100)),afterDiscount=operation("SUBTRACT",price.expression,discount),answer=operation("ADD",afterDiscount,fee.expression);fixtures.push(fixture(`Giá niêm yết ${price.display} nghìn đồng, giảm ${discountPercent}% rồi cộng ${fee.display} nghìn đồng phí cố định. Số tiền phải trả là bao nhiêu nghìn đồng?`,"nghìn đồng","PURCHASE","DISCOUNT_THEN_FEE",[price.display,`${discountPercent}%`,fee.display],answer,[{expression:discount,exactValue:exactDecimal(discount)},{expression:afterDiscount,exactValue:exactDecimal(afterDiscount)},{expression:answer,exactValue:exactDecimal(answer)}],[`Tiền giảm là ${exactDecimal(discount).replace(".",",")} nghìn đồng.`,`Sau giảm còn ${exactDecimal(afterDiscount).replace(".",",")} nghìn đồng.`,`Cộng phí được ${exactDecimal(answer).replace(".",",")} nghìn đồng.`]));});
  const simpleInterest=[[amount(1000),5,2],[amount(3001,2),4,3],[amount(2000),6,2],[amount(10001,4),3,4]] as const;
  simpleInterest.forEach(([principal,rate,years])=>{const oneYear=operation("MULTIPLY",principal.expression,value(rate,100)),interest=operation("MULTIPLY",oneYear,value(years)),answer=operation("ADD",principal.expression,interest);fixtures.push(fixture(`Trong mô hình lãi đơn của bài toán, số tiền gốc là ${principal.display} nghìn đồng, lãi suất ${rate}% mỗi năm trong ${years} năm. Tổng cả gốc và lãi là bao nhiêu nghìn đồng?`,"nghìn đồng","SIMPLE_INTEREST","RATE_TIME_TOTAL",[principal.display,`${rate}%`,String(years)],answer,[{expression:oneYear,exactValue:exactDecimal(oneYear)},{expression:interest,exactValue:exactDecimal(interest)},{expression:answer,exactValue:exactDecimal(answer)}],[`Lãi một năm là ${exactDecimal(oneYear).replace(".",",")} nghìn đồng.`,`Lãi ${years} năm là ${exactDecimal(interest).replace(".",",")} nghìn đồng.`,`Tổng là ${exactDecimal(answer).replace(".",",")} nghìn đồng.`]));});
  const ratios=[[amount(721,2),2,5,amount(121,5)],[amount(420),3,7,amount(30)],[amount(560),5,8,amount(70)],[amount(900),2,3,amount(150)]] as const;
  ratios.forEach(([total,numerator,denominator,used])=>{const allocated=operation("MULTIPLY",total.expression,value(numerator,denominator)),answer=operation("SUBTRACT",allocated,used.expression);fixtures.push(fixture(`Kho có ${total.display} kg nguyên liệu; phần dành cho tổ A bằng ${numerator}/${denominator} tổng số. Tổ A đã dùng ${used.display} kg. Tổ A còn bao nhiêu kg?`,"kg","RATIO_ALLOCATION","RATIO_THEN_SUBTRACT",[total.display,`${numerator}/${denominator}`,used.display],answer,[{expression:allocated,exactValue:exactDecimal(allocated)},{expression:answer,exactValue:exactDecimal(answer)}],[`Phần của tổ A là ${exactDecimal(allocated).replace(".",",")} kg.`,`Trừ ${used.display} kg đã dùng.`,`Còn ${exactDecimal(answer).replace(".",",")} kg.`]));});
  const changes=[[amount(481,2),10,amount(291,20)],[amount(320),25,amount(40)],[amount(450),20,amount(65)],[amount(600),15,amount(90)]] as const;
  changes.forEach(([initial,percent,used])=>{const increase=operation("MULTIPLY",initial.expression,value(percent,100)),afterIncrease=operation("ADD",initial.expression,increase),answer=operation("SUBTRACT",afterIncrease,used.expression);fixtures.push(fixture(`Kho có ${initial.display} kg, nhập thêm lượng bằng ${percent}% số ban đầu rồi xuất ${used.display} kg. Kho còn bao nhiêu kg?`,"kg","INVENTORY_CHANGE","PERCENT_INCREASE_THEN_SUBTRACT",[initial.display,`${percent}%`,used.display],answer,[{expression:increase,exactValue:exactDecimal(increase)},{expression:afterIncrease,exactValue:exactDecimal(afterIncrease)},{expression:answer,exactValue:exactDecimal(answer)}],[`Lượng nhập thêm là ${exactDecimal(increase).replace(".",",")} kg.`,`Sau khi nhập có ${exactDecimal(afterIncrease).replace(".",",")} kg.`,`Xuất đi rồi còn ${exactDecimal(answer).replace(".",",")} kg.`]));});
  const combined=[[amount(401,2),5,amount(300),8],[amount(400),12,amount(250),8],[amount(600),15,amount(400),10],[amount(750),8,amount(500),6]] as const;
  combined.forEach(([firstMass,firstPercent,secondMass,secondPercent])=>{const firstPart=operation("MULTIPLY",firstMass.expression,value(firstPercent,100)),secondPart=operation("MULTIPLY",secondMass.expression,value(secondPercent,100)),answer=operation("ADD",firstPart,secondPart);fixtures.push(fixture(`Mẻ một có ${firstMass.display} g và ${firstPercent}% chất A; mẻ hai có ${secondMass.display} g và ${secondPercent}% chất A. Hai mẻ có tổng bao nhiêu g chất A?`,"g","COMBINED_SOLUTION","TWO_PERCENT_PARTS_SUM",[firstMass.display,`${firstPercent}%`,secondMass.display,`${secondPercent}%`],answer,[{expression:firstPart,exactValue:exactDecimal(firstPart)},{expression:secondPart,exactValue:exactDecimal(secondPart)},{expression:answer,exactValue:exactDecimal(answer)}],[`Hai mẻ có ${exactDecimal(firstPart).replace(".",",")} g và ${exactDecimal(secondPart).replace(".",",")} g chất A.`,`Cộng hai lượng chất A.`,`Tổng là ${exactDecimal(answer).replace(".",",")} g.`]));});
  return fixtures;}
const fixtures=buildFixtures();
export function verifyGradeSixWaveHMalformedFixtures(){const base=fixtures[0]!;const malformed:readonly Fixture[]=[{...base,prompt:"Thiếu dữ liệu công khai.",publicTokens:["200"]},{...base,unit:"USD"},{...base,intermediates:[{...base.intermediates[0]!,exactValue:"999"},...base.intermediates.slice(1)]},{...base,derivation:operation("DIVIDE",value(1),value(0))}];return malformed.flatMap((entry,index)=>{try{assertFixture(entry);return[`g6-wave-h-malformed-${index+1}:ACCEPTED`];}catch(error){return error instanceof Error&&error.message.startsWith("AUTOMATED_VERIFICATION_INSUFFICIENT")?[]:[`g6-wave-h-malformed-${index+1}:WRONG_ERROR`];}});}
const malformedFixtureErrors=verifyGradeSixWaveHMalformedFixtures();if(malformedFixtureErrors.length)throw new Error(`GRADE_6_WAVE_H_MALFORMED_FIXTURE_FAILURE:${malformedFixtureErrors.join(",")}`);
function difficulty(index:number):DifficultyBand{const position=index%6;return position<2?"FOUNDATIONAL":position<4?"CORE":"EXTENSION";}
const generated:readonly GeneratedItem[]=fixtures.map((entry,index)=>{assertFixture(entry);const suffix=String(index+1).padStart(2,"0"),id=`g6-wave-h-${suffix}`,explanationId=`${id}-explanation`,answer=exactDecimal(entry.derivation);return{question:{id,grade,unitId,blueprintId:`g6-wave-h-blueprint-${sliceOutcomes[0].toLowerCase()}-${difficulty(index).toLowerCase()}`,skillId:officialSkillId(sliceOutcomes[0]),prompt:entry.prompt,options:null,answer:{type:"DECIMAL_INPUT",exactValue:answer,decimalPlaces:6,unit:entry.unit,derivation:entry.derivation},explanationId,difficulty:difficulty(index),provenance:{kind:"DETERMINISTIC_TEMPLATE",templateVersion:"g6-applied-ratio-percent-wave-h-template-1.0.0",seed:`g6-wave-h-${entry.structure.toLowerCase()}-${suffix}`,sourceReferenceIds:[sourceId]},reviewStatus:"BUNDLED",published:false,pilotEligible:false,fixtureOnly:false,duplicateFingerprint:sha256(normalizedDefinition(`${entry.prompt}|`).toLocaleLowerCase("vi")),validationReceiptIds:receiptIds,instructionalPurpose:purposes[index%purposes.length]!},explanation:{id:explanationId,questionId:id,steps:entry.steps,finalAnswer:answer,evidenceReceiptIds:[`${packId}-explanation-consistency`]}};});
const questions=generated.map((entry)=>entry.question),explanations=generated.map((entry)=>entry.explanation);

type BigFraction=Readonly<{numerator:bigint;denominator:bigint}>;const bgcd=(a:bigint,b:bigint):bigint=>b===0n?(a<0n?-a:a):bgcd(b,a%b);const bf=(n:bigint,d:bigint):BigFraction=>{if(d===0n)throw new Error("DIVISION_BY_ZERO");const sign=d<0n?-1n:1n,divisor=bgcd(n,d);return{numerator:sign*n/divisor,denominator:sign*d/divisor};};
function independentlyEvaluate(expression:MathExpression):BigFraction{if(expression.op==="VALUE")return bf(BigInt(expression.numerator),BigInt(expression.denominator));if(expression.op==="SQRT")throw new Error("UNSUPPORTED_ROOT");const l=independentlyEvaluate(expression.left),r=independentlyEvaluate(expression.right);if(expression.op==="ADD")return bf(l.numerator*r.denominator+r.numerator*l.denominator,l.denominator*r.denominator);if(expression.op==="SUBTRACT")return bf(l.numerator*r.denominator-r.numerator*l.denominator,l.denominator*r.denominator);if(expression.op==="MULTIPLY")return bf(l.numerator*r.numerator,l.denominator*r.denominator);return bf(l.numerator*r.denominator,l.denominator*r.numerator);}
function parseDecimal(input:string):BigFraction|null{const match=/^(\d+)(?:\.(\d+))?$/u.exec(input);if(!match)return null;const decimals=match[2]??"";return bf(BigInt(`${match[1]}${decimals}`),10n**BigInt(decimals.length));}
export function verifyGradeSixWaveHIndependentOracle(){return questions.flatMap((question)=>{const expression=question.answer.derivation,declared=parseDecimal(question.answer.exactValue??"");if(!expression||!declared)return[`${question.id}:MISSING_OR_INVALID_CONTRACT`];try{const result=independentlyEvaluate(expression);return result.numerator===declared.numerator&&result.denominator===declared.denominator?[]:[`${question.id}:INDEPENDENT_ORACLE_MISMATCH`];}catch{return[`${question.id}:INDEPENDENT_ORACLE_ERROR`];}});}
const independentOracleErrors=verifyGradeSixWaveHIndependentOracle();if(independentOracleErrors.length)throw new Error(`GRADE_6_WAVE_H_ORACLE_FAILURE:${independentOracleErrors.join(",")}`);
const skeleton=buildOfficialGradeSkeleton(grade),evidenceReceipts=requiredAutomatedEvidenceChecks.map((check)=>({id:`${packId}-${check.toLowerCase().replaceAll("_","-")}`,entityId:packId,check,status:"PASSED" as const,evidence:check==="SOURCE_MAPPING"?`Retained source-locked outcome ${sliceOutcomes[0]} on page 50.`:check==="MATHEMATICAL_ANSWER"?`Independent BigInt rational oracle verifies ${questions.length} finite-decimal answers across ${new Set(fixtures.map((entry)=>entry.structure)).size} structures; oracle errors ${independentOracleErrors.length}, malformed errors ${malformedFixtureErrors.length}.`:`Deterministic Grade 6 Wave H ${check.toLowerCase().replaceAll("_"," ")} receipt.`}));
const blueprints=(["FOUNDATIONAL","CORE","EXTENSION"] as const).map((band)=>({id:`g6-wave-h-blueprint-${sliceOutcomes[0].toLowerCase()}-${band.toLowerCase()}`,grade,skillId:officialSkillId(sliceOutcomes[0]),difficulty:band,questionType:"DECIMAL_INPUT" as const,templateId:`g6-wave-h-template-${sliceOutcomes[0].toLowerCase()}`,targetCount:8,sourceReferenceIds:[sourceId]}));
const candidateCore={format:"plave-wave-h-candidate-v1",candidateId,version,policyVersion,sourceOutcomeIds:sliceOutcomes,blueprints,questions,explanations} as const;export const gradeSixWaveHBundleHash=sha256(canonicalize(candidateCore));
export function createGradeSixWaveHPack():GradePack{return{schemaVersion:"content-factory-grade-pack-v1",grade,packId,packVersion:version,immutableReference:false,testOnly:false,locale:"vi-VN",unicodeNormalization:"NFC",sources:[skeleton.source],domains:skeleton.domains,units:skeleton.units,knowledgeNodes:skeleton.knowledgeNodes,skills:skeleton.skills,objectives:skeleton.objectives,prerequisites:[{fromSkillId:officialSkillId(prerequisiteOutcomeIds[0]),toSkillId:officialSkillId(sliceOutcomes[0]),evidence:"HYPOTHESIS_REQUIRES_EVIDENCE",sourceReferenceIds:[]},{fromSkillId:officialSkillId(sliceOutcomes[0]),toSkillId:officialSkillId(nextTargetOutcomeIds[0]),evidence:"HYPOTHESIS_REQUIRES_EVIDENCE",sourceReferenceIds:[]}],blueprints,questions,quarantinedQuestions:[],explanations,evidenceReceipts,candidate:{candidateId,version,bundleHash:gradeSixWaveHBundleHash,policyVersion},adaptivePolicy:{version:policyVersion,status:"VALIDATED"},release:{publication:"DRAFT",visibility:"HIDDEN",pilotEnabled:false,runtimeEnabled:false,retentionEnabled:false},production:{wave:"H",selectedSliceId:"g6-applied-decimal-ratio-percent",selectionBasis:["SOURCE_VERIFIED","UNCOVERED_BY_WAVES_A_TO_G","PUBLIC_DATA_COMPLETE","EXACT_FINITE_DECIMAL_INTERMEDIATES","DOMAIN_UNIT_GUARDS","INDEPENDENT_BIGINT_ORACLE","SIX_REASONING_STRUCTURES"],generated:24,repaired:0,evidenceGatePassed:24,verificationInsufficient:0,rejected:0,duplicate:0,candidateEligible:24},legacyAsset:null};}
export const gradeSixWaveHPack=createGradeSixWaveHPack();
export const gradeSixWaveHMetadata={schemaVersion:"plave-wave-h-metadata-v1",wave:"H",grade,title:"Bài toán thực tiễn về thập phân, tỉ số và phần trăm",sourceClassification:"SOURCE_VERIFIED",sourcePages:[50],sourceOutcomeIds:sliceOutcomes,prerequisiteOutcomeIds,prerequisiteEvidence:"HYPOTHESIS_REQUIRES_EVIDENCE",nextTargetOutcomeIds,nextTargetEvidence:"HYPOTHESIS_REQUIRES_EVIDENCE",reasoningStructures:[...new Set(fixtures.map((entry)=>entry.structure))],independentOracleErrors,malformedFixtureErrors,production:gradeSixWaveHPack.production,candidate:gradeSixWaveHPack.candidate,release:gradeSixWaveHPack.release} as const;
