import type { WaveKClassificationDecision, WaveKOutcomeClassification } from "./wave-k-types.ts";

type ProductionGrade = 7 | 8 | 9;

function decisions(
  grade: ProductionGrade,
  classification: WaveKOutcomeClassification,
  reason: string,
  templateFamily: string | null,
  outcomeIds: readonly string[],
  semanticAliasTargetSkillId: string | null = null,
): readonly WaveKClassificationDecision[] {
  return outcomeIds.map((outcomeId) => ({
    outcomeId,
    grade,
    classification,
    reason,
    templateFamily,
    semanticAliasTargetSkillId,
  }));
}

const g7Producible = [
  ...decisions(7, "PRODUCIBLE_DETERMINISTIC", "Exact rational location can be verified from a reduced fraction and an explicitly encoded number-line interval.", "rational-number-line", ["MOET2018-G7-NAA-P055-001"]),
  ...decisions(7, "PRODUCIBLE_DETERMINISTIC", "The additive inverse is uniquely determined by exact rational arithmetic.", "rational-opposite", ["MOET2018-G7-NAA-P055-002"]),
  ...decisions(7, "PRODUCIBLE_DETERMINISTIC", "Rational membership and set notation have exact symbolic truth conditions.", "rational-membership-and-set", ["MOET2018-G7-NAA-P055-003", "MOET2018-G7-NAA-P055-004"]),
  ...decisions(7, "PRODUCIBLE_DETERMINISTIC", "Operation order, brackets and transposition can be checked by independent reduced-rational evaluation.", "rational-operation-order", ["MOET2018-G7-NAA-P056-007"]),
  ...decisions(7, "PRODUCIBLE_DETERMINISTIC", "Natural powers of rational numbers have an exact BigInt-rational oracle.", "rational-power-definition", ["MOET2018-G7-NAA-P056-008"]),
  ...decisions(7, "PRODUCIBLE_DETERMINISTIC", "Explicit public data constraints permit a unique mathematical consistency verdict.", "data-reasonableness", ["MOET2018-G7-STA-P061-003"]),
  ...decisions(7, "PRODUCIBLE_DETERMINISTIC", "A fully public dataset and stated communication goal determine a bounded table or chart choice.", "data-representation-selection", ["MOET2018-G7-STA-P061-004"]),
  ...decisions(7, "PRODUCIBLE_DETERMINISTIC", "Fictional, fully specified cross-subject datasets permit source-safe recognition without external factual claims.", "statistics-cross-context", ["MOET2018-G7-STA-P061-005"]),
  ...decisions(7, "PRODUCIBLE_DETERMINISTIC", "Two text-serialized representations can be compared against the same public dataset exactly.", "data-representation-equivalence", ["MOET2018-G7-STA-P061-006"]),
  ...decisions(7, "PRODUCIBLE_DETERMINISTIC", "Angle equality and ray-incidence constraints provide a text-only angle-bisector oracle.", "angle-bisector-identification", ["MOET2018-G7-GEO-P059-018"]),
  ...decisions(7, "PRODUCIBLE_DETERMINISTIC", "Euclid's parallel axiom has bounded symbolic consequences with one exact answer.", "euclid-parallel-axiom", ["MOET2018-G7-GEO-P059-019"]),
  ...decisions(7, "PRODUCIBLE_DETERMINISTIC", "A complete symbolic fixture can expose assumptions and admit one valid proof step.", "geometry-proof-step", ["MOET2018-G7-GEO-P060-020"]),
  ...decisions(7, "PRODUCIBLE_DETERMINISTIC", "Equal-distance and midpoint-perpendicular constraints admit exact coordinate or length checks.", "perpendicular-bisector", ["MOET2018-G7-GEO-P060-022"]),
  ...decisions(7, "PRODUCIBLE_DETERMINISTIC", "Named triangle lines and their concurrency properties have exact definition-based checks.", "triangle-special-lines", ["MOET2018-G7-GEO-P060-023"]),
  ...decisions(7, "PRODUCIBLE_DETERMINISTIC", "Public dimensions make cuboid and cube surface-area or volume applications exact.", "rectangular-solid-applied-measurement", ["MOET2018-G7-GEO-P058-002"]),
  ...decisions(7, "PRODUCIBLE_DETERMINISTIC", "Counts and incidences of cuboid or cube elements are finite and independently enumerable.", "rectangular-solid-elements", ["MOET2018-G7-GEO-P058-004"]),
  ...decisions(7, "PRODUCIBLE_DETERMINISTIC", "Side and angle tuples permit exact congruence-criterion validation.", "triangle-congruence-criteria", ["MOET2018-G7-GEO-P059-006"]),
  ...decisions(7, "PRODUCIBLE_DETERMINISTIC", "Explicit side and angle orderings admit exact triangle inequality comparisons.", "triangle-side-angle-relation", ["MOET2018-G7-GEO-P059-008"]),
  ...decisions(7, "PRODUCIBLE_DETERMINISTIC", "Corresponding and alternate-interior angle constraints exactly determine parallelism.", "parallel-line-angle-criteria", ["MOET2018-G7-GEO-P059-009"]),
  ...decisions(7, "PRODUCIBLE_DETERMINISTIC", "Parallel-line angle properties can be checked from complete symbolic angle data.", "parallel-line-properties", ["MOET2018-G7-GEO-P059-010"]),
  ...decisions(7, "PRODUCIBLE_DETERMINISTIC", "A bounded statement-assumption-conclusion fixture permits exact theorem/proof recognition.", "theorem-proof-recognition", ["MOET2018-G7-GEO-P059-012"]),
  ...decisions(7, "PRODUCIBLE_DETERMINISTIC", "Supplementary and vertical angle relations have exact arithmetic oracles.", "special-angle-relations", ["MOET2018-G7-GEO-P059-013"]),
  ...decisions(7, "PRODUCIBLE_DETERMINISTIC", "The valid compass-and-straightedge construction sequence can be assessed as a bounded ordered procedure.", "angle-bisector-construction-sequence", ["MOET2018-G7-GEO-P059-014"]),
  ...decisions(7, "PRODUCIBLE_DETERMINISTIC", "Coordinates and orthogonality make perpendicular, oblique and point-to-line distance cases exact.", "perpendicular-oblique-distance", ["MOET2018-G7-GEO-P059-016"]),
  ...decisions(7, "PRODUCIBLE_DETERMINISTIC", "The strict three-side triangle inequality has an exact integer or rational oracle.", "triangle-inequality", ["MOET2018-G7-GEO-P059-017"]),
  ...decisions(7, "PRODUCIBLE_DETERMINISTIC", "Power product, quotient and power-of-power laws are exactly checkable over reduced rationals.", "rational-power-laws", ["MOET2018-G7-NAA-P056-006"]),
  ...decisions(7, "PRODUCIBLE_DETERMINISTIC", "Arithmetic square-root membership and principal-root values are exact on perfect-square fixtures.", "arithmetic-square-root-concept", ["MOET2018-G7-NAA-P056-009"]),
  ...decisions(7, "PRODUCIBLE_DETERMINISTIC", "The additive inverse of a represented real number is uniquely determined.", "real-opposite", ["MOET2018-G7-NAA-P056-010"]),
  ...decisions(7, "PRODUCIBLE_DETERMINISTIC", "Reduced-denominator factorization distinguishes terminating from repeating decimals exactly.", "decimal-expansion-classification", ["MOET2018-G7-NAA-P056-011"]),
  ...decisions(7, "PRODUCIBLE_DETERMINISTIC", "Finite symbolic examples have exact rational, irrational and real-set membership.", "real-number-sets", ["MOET2018-G7-NAA-P056-012"]),
  ...decisions(7, "PRODUCIBLE_DETERMINISTIC", "Rational order statements have exact common-denominator or cross-product verification.", "rational-order-concept", ["MOET2018-G7-NAA-P056-013"]),
  ...decisions(7, "PRODUCIBLE_DETERMINISTIC", "Favourable exact real values can be located on a text-encoded number line.", "real-number-line", ["MOET2018-G7-NAA-P056-014"]),
  ...decisions(7, "PRODUCIBLE_DETERMINISTIC", "Two reduced rationals can be compared exactly by signed cross multiplication.", "rational-comparison", ["MOET2018-G7-NAA-P056-015"]),
  ...decisions(7, "PRODUCIBLE_DETERMINISTIC", "Equivalent rational expressions verify commutative, associative, distributive and bracket transformations.", "rational-properties-computation", ["MOET2018-G7-NAA-P056-018"]),
  ...decisions(7, "PRODUCIBLE_DETERMINISTIC", "Algebraic expressions can be recognized from explicit variable and operation syntax.", "algebraic-expression-recognition", ["MOET2018-G7-NAA-P057-021"]),
  ...decisions(7, "PRODUCIBLE_DETERMINISTIC", "Numeric expressions can be recognized from fully public constant-only syntax.", "numeric-expression-recognition", ["MOET2018-G7-NAA-P057-022"]),
  ...decisions(7, "PRODUCIBLE_DETERMINISTIC", "Canonical coefficients determine one-variable polynomial form and degree exactly.", "polynomial-representation-degree", ["MOET2018-G7-NAA-P057-023"]),
  ...decisions(7, "PRODUCIBLE_DETERMINISTIC", "Finite symbolic forms permit exact one-variable polynomial membership checks.", "polynomial-definition", ["MOET2018-G7-NAA-P057-025"]),
  ...decisions(7, "PRODUCIBLE_DETERMINISTIC", "Absolute value is exactly determined for rational values and exact radicals used in bounded fixtures.", "real-absolute-value", ["MOET2018-G7-NAA-P057-026"]),
  ...decisions(7, "PRODUCIBLE_DETERMINISTIC", "Exact rational and favourable radical values admit deterministic real-order comparison.", "real-order", ["MOET2018-G7-NAA-P057-027"]),
  ...decisions(7, "PRODUCIBLE_DETERMINISTIC", "A declared accuracy unit uniquely determines the required rounding interval and result.", "rounding-by-accuracy", ["MOET2018-G7-NAA-P057-029"]),
  ...decisions(7, "PRODUCIBLE_DETERMINISTIC", "Three public angle measures and the 180-degree invariant provide an exact oracle.", "triangle-angle-sum", ["MOET2018-G7-GEO-P059-007"]),
  ...decisions(7, "PRODUCIBLE_DETERMINISTIC", "Equal-side and equal-base-angle implications are exact on symbolic triangle fixtures.", "isosceles-triangle-properties", ["MOET2018-G7-GEO-P059-011"]),
  ...decisions(7, "PRODUCIBLE_DETERMINISTIC", "Explicit vertex correspondence and side-angle tuples permit exact congruent-triangle recognition.", "congruent-triangle-concept", ["MOET2018-G7-GEO-P059-015"]),
] as const;

const g7Excluded = [
  ...decisions(7, "VISUAL_EVIDENCE_REQUIRED", "The conjunctive outcome requires creating a triangular or quadrilateral right prism; the retained answer contract cannot verify the constructed object.", null, ["MOET2018-G7-GEO-P058-003"]),
  ...decisions(7, "AUTOMATED_VERIFICATION_INSUFFICIENT", "A numeric answer cannot prove the required calculator-use process, and no deterministic interaction trace is retained.", null, ["MOET2018-G7-NAA-P056-017"]),
  ...decisions(7, "OPEN_ENDED_OR_EXPERIENTIAL", "The outcome requires practical measuring, drawing or constructing rather than a uniquely scorable candidate response.", null, ["MOET2018-G7-GEO-P060-021"]),
  ...decisions(7, "OPEN_ENDED_OR_EXPERIENTIAL", "The outcome requires observed geometry-software use or software drawing and cannot be inferred from a final answer.", null, ["MOET2018-G7-GEO-P060-024", "MOET2018-G7-GEO-P060-025"]),
  ...decisions(7, "OPEN_ENDED_OR_EXPERIENTIAL", "The retained source classifies this as practical/experiential activity without a complete deterministic assessment contract.", null, [
    "MOET2018-G7-EXP-P062-001", "MOET2018-G7-EXP-P062-002", "MOET2018-G7-EXP-P062-003",
    "MOET2018-G7-EXP-P062-004", "MOET2018-G7-EXP-P062-005", "MOET2018-G7-EXP-P062-006",
    "MOET2018-G7-EXP-P063-001",
  ]),
] as const;

const g8Producible = [
  ...decisions(8, "PRODUCIBLE_DETERMINISTIC", "Complete public numeric relations permit an exact inconsistent-datum oracle.", "data-inconsistency-detection", ["MOET2018-G8-STA-P068-004"]),
  ...decisions(8, "PRODUCIBLE_DETERMINISTIC", "A fully public finite dataset permits exact pattern or issue detection.", "data-pattern-analysis", ["MOET2018-G8-STA-P069-012"]),
  ...decisions(8, "PRODUCIBLE_DETERMINISTIC", "Substitution into y=ax+b produces an exact value table.", "linear-function-value-table", ["MOET2018-G8-NAA-P064-015"]),
  ...decisions(8, "PRODUCIBLE_DETERMINISTIC", "The Pythagorean identity can be checked through exact side-square equality and proof-step fixtures.", "pythagorean-theorem-explanation", ["MOET2018-G8-GEO-P065-002"]),
  ...decisions(8, "PRODUCIBLE_DETERMINISTIC", "Midsegment parallelism and half-length relations admit exact ratio and proof-step checks.", "triangle-midsegment-properties", ["MOET2018-G8-GEO-P067-024"]),
  ...decisions(8, "PRODUCIBLE_DETERMINISTIC", "Explicit proportional side tuples and correspondence give exact triangle-similarity recognition.", "similar-triangle-definition", ["MOET2018-G8-GEO-P067-025"]),
  ...decisions(8, "PRODUCIBLE_DETERMINISTIC", "Endpoint and parallelism constraints give a deterministic triangle-midsegment definition check.", "triangle-midsegment-definition", ["MOET2018-G8-GEO-P067-026"]),
  ...decisions(8, "PRODUCIBLE_DETERMINISTIC", "Complete segment ratios admit exact Thales length calculations.", "thales-length-calculation", ["MOET2018-G8-GEO-P067-029"]),
  ...decisions(8, "PRODUCIBLE_DETERMINISTIC", "The 360-degree invariant supplies an exact convex-quadrilateral angle oracle.", "quadrilateral-angle-sum", ["MOET2018-G8-GEO-P066-008"]),
  ...decisions(8, "PRODUCIBLE_DETERMINISTIC", "Side, angle and diagonal invariants of a parallelogram are finite and exact.", "parallelogram-properties", ["MOET2018-G8-GEO-P066-009"]),
  ...decisions(8, "PRODUCIBLE_DETERMINISTIC", "Rhombus diagonal properties are checkable from explicit lengths, bisection and perpendicularity constraints.", "rhombus-diagonal-properties", ["MOET2018-G8-GEO-P066-010"]),
  ...decisions(8, "PRODUCIBLE_DETERMINISTIC", "Isosceles-trapezoid base-angle, leg and diagonal relations are exact on symbolic fixtures.", "isosceles-trapezoid-properties", ["MOET2018-G8-GEO-P066-011"]),
  ...decisions(8, "PRODUCIBLE_DETERMINISTIC", "Rectangle diagonal equality and bisection constraints admit exact checks.", "rectangle-diagonal-properties", ["MOET2018-G8-GEO-P066-012"]),
  ...decisions(8, "PRODUCIBLE_DETERMINISTIC", "Square diagonal equality, perpendicularity and bisection constraints admit exact checks.", "square-diagonal-properties", ["MOET2018-G8-GEO-P066-013"]),
  ...decisions(8, "PRODUCIBLE_DETERMINISTIC", "A four-segment incidence fixture determines quadrilateral and convexity membership exactly.", "convex-quadrilateral-definition", ["MOET2018-G8-GEO-P066-014"]),
  ...decisions(8, "PRODUCIBLE_DETERMINISTIC", "Parallelogram plus equal-diagonal conditions exactly imply rectangle membership.", "rectangle-recognition-criteria", ["MOET2018-G8-GEO-P066-015"]),
  ...decisions(8, "PRODUCIBLE_DETERMINISTIC", "Parallelogram plus perpendicular-diagonal conditions exactly imply rhombus membership.", "rhombus-recognition-criteria", ["MOET2018-G8-GEO-P066-016"]),
  ...decisions(8, "PRODUCIBLE_DETERMINISTIC", "Trapezoid plus equal-diagonal conditions exactly imply isosceles-trapezoid membership.", "isosceles-trapezoid-recognition-criteria", ["MOET2018-G8-GEO-P066-017"]),
  ...decisions(8, "PRODUCIBLE_DETERMINISTIC", "Diagonal-midpoint or opposite-side conditions exactly imply parallelogram membership.", "parallelogram-recognition-criteria", ["MOET2018-G8-GEO-P066-018"]),
  ...decisions(8, "PRODUCIBLE_DETERMINISTIC", "A fully specified proportional-distance context yields one exact Thales result.", "applied-thales-problems", ["MOET2018-G8-GEO-P067-019"]),
  ...decisions(8, "PRODUCIBLE_DETERMINISTIC", "A fully specified indirect-measurement context yields one exact similarity result.", "applied-similar-triangle-problems", ["MOET2018-G8-GEO-P067-020"]),
  ...decisions(8, "PRODUCIBLE_DETERMINISTIC", "Complete side and angle tuples permit exact similarity-criterion validation.", "triangle-similarity-criteria", ["MOET2018-G8-GEO-P067-021"]),
  ...decisions(8, "PRODUCIBLE_DETERMINISTIC", "Explicit ratios and parallelism permit exact direct and converse Thales proof-step checks.", "thales-theorem-reasoning", ["MOET2018-G8-GEO-P067-022"]),
  ...decisions(8, "PRODUCIBLE_DETERMINISTIC", "The internal angle-bisector side-ratio relation admits exact rational verification.", "triangle-angle-bisector-theorem", ["MOET2018-G8-GEO-P067-023"]),
  ...decisions(8, "PRODUCIBLE_DETERMINISTIC", "Canonical term structure permits exact monomial and multivariate-polynomial membership.", "multivariate-polynomial-concepts", ["MOET2018-G8-NAA-P063-002"]),
  ...decisions(8, "PRODUCIBLE_DETERMINISTIC", "Coefficient maps provide an independent exact oracle for multivariate polynomial addition, subtraction and multiplication.", "multivariate-polynomial-operations", ["MOET2018-G8-NAA-P063-004"]),
  ...decisions(8, "PRODUCIBLE_DETERMINISTIC", "Divisibility and coefficient/exponent subtraction give an exact polynomial-by-monomial quotient.", "polynomial-by-monomial-division", ["MOET2018-G8-NAA-P063-005"]),
  ...decisions(8, "PRODUCIBLE_DETERMINISTIC", "Coefficient and exponent arithmetic exactly verifies monomial multiplication/division and distribution.", "monomial-polynomial-operations", ["MOET2018-G8-NAA-P063-006"]),
  ...decisions(8, "PRODUCIBLE_DETERMINISTIC", "Canonical coefficient maps exactly verify collection of like terms.", "polynomial-simplification", ["MOET2018-G8-NAA-P063-007"]),
  ...decisions(8, "PRODUCIBLE_DETERMINISTIC", "Exact integer or rational substitution verifies multivariate polynomial values.", "multivariate-polynomial-evaluation", ["MOET2018-G8-NAA-P063-008"]),
  ...decisions(8, "PRODUCIBLE_DETERMINISTIC", "Finite tables, formulas and ordered pairs permit exact graph-concept recognition without requiring drawing.", "function-graph-concept", ["MOET2018-G8-NAA-P064-012"]),
  ...decisions(8, "PRODUCIBLE_DETERMINISTIC", "Fully specified fictional input-output situations permit exact function-model recognition.", "real-model-function-recognition", ["MOET2018-G8-NAA-P064-014"]),
  ...decisions(8, "PRODUCIBLE_DETERMINISTIC", "Reduced symbolic numerator/denominator forms provide an exact rational-expression operation oracle with domain guards.", "rational-expression-operations", ["MOET2018-G8-NAA-P064-016"]),
  ...decisions(8, "PRODUCIBLE_DETERMINISTIC", "Formula substitution with an explicit domain yields one exact function value.", "function-formula-evaluation", ["MOET2018-G8-NAA-P064-018"]),
  ...decisions(8, "PRODUCIBLE_DETERMINISTIC", "Canonical rational expressions verify commutative, associative, distributive and bracket transformations exactly.", "rational-expression-properties", ["MOET2018-G8-NAA-P064-020"]),
  ...decisions(8, "PRODUCIBLE_DETERMINISTIC", "Complete public data constraints permit an exact mathematical reasonableness proof.", "data-reasonableness", ["MOET2018-G8-STA-P068-001"]),
  ...decisions(8, "PRODUCIBLE_DETERMINISTIC", "A public finite dataset and communication target determine a bounded table or chart representation.", "data-representation-selection", ["MOET2018-G8-STA-P068-002"]),
  ...decisions(8, "PRODUCIBLE_DETERMINISTIC", "Explicit values permit exact detection of mathematical relationships.", "data-relationship-recognition", ["MOET2018-G8-STA-P068-003"]),
  ...decisions(8, "PRODUCIBLE_DETERMINISTIC", "A fully public finite dataset permits exact computations and one-answer data applications.", "data-application-problems", ["MOET2018-G8-STA-P069-008"]),
  ...decisions(8, "PRODUCIBLE_DETERMINISTIC", "Text-serialized tables and chart mappings permit an exact representation-conversion explanation check.", "data-representation-conversion", ["MOET2018-G8-STA-P069-009"]),
  ...decisions(8, "PRODUCIBLE_DETERMINISTIC", "Fictional, fully specified cross-subject datasets permit source-safe recognition without external factual claims.", "statistics-cross-context", ["MOET2018-G8-STA-P069-010"]),
  ...decisions(8, "PRODUCIBLE_DETERMINISTIC", "Two text-serialized representations can be compared against the same public dataset exactly.", "data-representation-comparison", ["MOET2018-G8-STA-P069-013"]),
] as const;

const g8Excluded = [
  ...decisions(8, "VISUAL_EVIDENCE_REQUIRED", "The outcome explicitly requires drawing a linear-function graph; the retained answer contract cannot verify the produced graph.", null, ["MOET2018-G8-NAA-P064-021"]),
  ...decisions(8, "VISUAL_EVIDENCE_REQUIRED", "The conjunctive outcome requires creating a regular pyramid; a text answer cannot prove the constructed object.", null, ["MOET2018-G8-GEO-P065-003"]),
  ...decisions(8, "VISUAL_EVIDENCE_REQUIRED", "The outcome explicitly requires recognition through concrete images, which are not represented in the candidate contract.", null, ["MOET2018-G8-GEO-P067-027"]),
  ...decisions(8, "VISUAL_EVIDENCE_REQUIRED", "Both locating a point and recovering coordinates from a coordinate plane require a public visual/coordinate interaction not retained by the answer contract.", null, ["MOET2018-G8-NAA-P064-022"]),
  ...decisions(8, "OPEN_ENDED_OR_EXPERIENTIAL", "Recognition of beauty in natural, artistic or architectural similarity is subjective and has no unique deterministic answer.", null, ["MOET2018-G8-GEO-P067-028"]),
  ...decisions(8, "OPEN_ENDED_OR_EXPERIENTIAL", "Observed geometry-software use or software drawing cannot be inferred from a final answer.", null, ["MOET2018-G8-GEO-P068-001", "MOET2018-G8-GEO-P068-002"]),
  ...decisions(8, "OPEN_ENDED_OR_EXPERIENTIAL", "The outcome requires authentic collection and classification across interviews, media, Internet or practice rather than a closed supplied dataset.", null, ["MOET2018-G8-STA-P068-007"]),
  ...decisions(8, "OPEN_ENDED_OR_EXPERIENTIAL", "The retained source classifies this as practical/experiential activity without a complete deterministic assessment contract.", null, [
    "MOET2018-G8-EXP-P070-001", "MOET2018-G8-EXP-P070-002", "MOET2018-G8-EXP-P070-003",
    "MOET2018-G8-EXP-P070-004", "MOET2018-G8-EXP-P070-005", "MOET2018-G8-EXP-P070-006",
    "MOET2018-G8-EXP-P070-007", "MOET2018-G8-EXP-P070-008", "MOET2018-G8-EXP-P070-009",
  ]),
] as const;

const g9Producible = [
  ...decisions(9, "PRODUCIBLE_DETERMINISTIC", "A complete frequency table gives an exact relative-frequency interpretation.", "relative-frequency-meaning", ["MOET2018-G9-STA-P077-013"]),
  ...decisions(9, "PRODUCIBLE_DETERMINISTIC", "Coefficient structure and ordered-pair substitution permit exact linear-equation/system concept checks.", "two-variable-linear-system-concept", ["MOET2018-G9-NAA-P072-019"]),
  ...decisions(9, "PRODUCIBLE_DETERMINISTIC", "The axis x=0 for y=ax^2 and symmetric value pairs admit exact symbolic verification.", "quadratic-axis-symmetry", ["MOET2018-G9-NAA-P071-004"]),
  ...decisions(9, "PRODUCIBLE_DETERMINISTIC", "Fully specified right-triangle contexts admit exact or declared-precision trigonometric results.", "applied-right-triangle-trigonometry", ["MOET2018-G9-GEO-P074-008"]),
  ...decisions(9, "PRODUCIBLE_DETERMINISTIC", "Public right-triangle sides and angles verify the sine, cosine, tangent and cotangent side relations.", "right-triangle-side-angle-relations", ["MOET2018-G9-GEO-P074-010"]),
  ...decisions(9, "PRODUCIBLE_DETERMINISTIC", "Definitions of triangle circumcircles and incircles have exact center/equidistance truth conditions.", "triangle-circle-definitions", ["MOET2018-G9-GEO-P075-022", "MOET2018-G9-GEO-P075-023"]),
  ...decisions(9, "PRODUCIBLE_DETERMINISTIC", "Public center, vertex and arc constraints permit exact central/inscribed-angle recognition.", "central-inscribed-angle-recognition", ["MOET2018-G9-GEO-P075-024"]),
  ...decisions(9, "PRODUCIBLE_DETERMINISTIC", "Opposite-angle sums provide an exact cyclic-quadrilateral oracle.", "cyclic-quadrilateral-properties", ["MOET2018-G9-GEO-P075-025"]),
  ...decisions(9, "PRODUCIBLE_DETERMINISTIC", "Arc, sector and annulus formulas admit exact rational-multiple-of-pi or declared-pi arithmetic.", "circle-arc-sector-annulus", ["MOET2018-G9-GEO-P075-026"]),
  ...decisions(9, "PRODUCIBLE_DETERMINISTIC", "Rectangle and square diagonals determine circumcenter and radius exactly.", "quadrilateral-circumcircle", ["MOET2018-G9-GEO-P075-027"]),
  ...decisions(9, "PRODUCIBLE_DETERMINISTIC", "Right and equilateral triangle fixtures determine circumcenter and radius exactly.", "triangle-circumcircle", ["MOET2018-G9-GEO-P075-028"]),
  ...decisions(9, "PRODUCIBLE_DETERMINISTIC", "Equilateral and coordinate triangle fixtures determine incenter and inradius exactly.", "triangle-incircle", ["MOET2018-G9-GEO-P075-029"]),
  ...decisions(9, "PRODUCIBLE_DETERMINISTIC", "Rotational symmetries of a regular n-gon are exactly the multiples of 360/n degrees.", "regular-polygon-rotational-symmetry", ["MOET2018-G9-GEO-P076-001"]),
  ...decisions(9, "PRODUCIBLE_DETERMINISTIC", "A fully specified coordinate transformation permits exact rotation recognition.", "rotation-transformation-concept", ["MOET2018-G9-GEO-P076-003"]),
  ...decisions(9, "PRODUCIBLE_DETERMINISTIC", "Equal-side/equal-angle and rotational-symmetry constraints permit exact regular-polygon recognition.", "regular-polygon-recognition", ["MOET2018-G9-GEO-P076-005"]),
  ...decisions(9, "PRODUCIBLE_DETERMINISTIC", "Plane-to-sphere distance relative to radius exactly determines the intersection type.", "plane-sphere-intersection", ["MOET2018-G9-GEO-P073-005"]),
  ...decisions(9, "PRODUCIBLE_DETERMINISTIC", "Radius-to-line distance and tangent-length relations provide an exact tangent oracle.", "circle-tangent-properties", ["MOET2018-G9-GEO-P074-009"]),
  ...decisions(9, "PRODUCIBLE_DETERMINISTIC", "Special-angle and complementary-angle trigonometric values have exact radical/rational forms.", "special-angle-trigonometry", ["MOET2018-G9-GEO-P074-011"]),
  ...decisions(9, "PRODUCIBLE_DETERMINISTIC", "Center-to-line distance compared with radius exactly determines line-circle position.", "line-circle-relative-position", ["MOET2018-G9-GEO-P074-012"]),
  ...decisions(9, "PRODUCIBLE_DETERMINISTIC", "Center distance compared with sum and difference of radii exactly determines two-circle position.", "two-circle-relative-position", ["MOET2018-G9-GEO-P074-013"]),
  ...decisions(9, "PRODUCIBLE_DETERMINISTIC", "Explicit right-triangle side ratios uniquely determine sine, cosine, tangent and cotangent.", "acute-angle-trigonometric-ratios", ["MOET2018-G9-GEO-P074-014"]),
  ...decisions(9, "PRODUCIBLE_DETERMINISTIC", "A circle has exact center and infinitely many reflection axes through the center.", "circle-symmetry", ["MOET2018-G9-GEO-P074-015"]),
  ...decisions(9, "PRODUCIBLE_DETERMINISTIC", "Every chord length is at most the diameter, with equality characterized exactly.", "diameter-chord-comparison", ["MOET2018-G9-GEO-P074-017"]),
  ...decisions(9, "PRODUCIBLE_DETERMINISTIC", "Fully specified circular-motion or composite-circle contexts admit exact or declared-pi arithmetic.", "applied-circle-problems", ["MOET2018-G9-GEO-P075-019"]),
  ...decisions(9, "PRODUCIBLE_DETERMINISTIC", "A fully specified fictional quadratic context and exact model yield one deterministic answer.", "applied-quadratic-function", ["MOET2018-G9-NAA-P071-001"]),
  ...decisions(9, "PRODUCIBLE_DETERMINISTIC", "Perfect-power fixtures permit exact square-root/cube-root concept recognition.", "square-cube-root-concepts", ["MOET2018-G9-NAA-P071-002"]),
  ...decisions(9, "PRODUCIBLE_DETERMINISTIC", "Explicit radicands and domain conditions permit exact algebraic-radical concept checks.", "algebraic-radical-concepts", ["MOET2018-G9-NAA-P071-003"]),
  ...decisions(9, "PRODUCIBLE_DETERMINISTIC", "Canonical radical forms and domain guards permit exact product, quotient, square and rationalization transformations.", "algebraic-radical-transformations", ["MOET2018-G9-NAA-P071-006"]),
  ...decisions(9, "PRODUCIBLE_DETERMINISTIC", "Perfect-square factors and positive rational radicands admit exact simplified radical arithmetic.", "numeric-radical-operations", ["MOET2018-G9-NAA-P071-007"]),
  ...decisions(9, "PRODUCIBLE_DETERMINISTIC", "Integer-coefficient quadratics with exact rational roots admit an independent discriminant oracle.", "quadratic-equation-solving", ["MOET2018-G9-NAA-P072-011"]),
  ...decisions(9, "PRODUCIBLE_DETERMINISTIC", "Explicit nonzero denominator guards and cross multiplication reduce the equation to an exact linear solution.", "rational-equation-to-linear", ["MOET2018-G9-NAA-P072-012"]),
  ...decisions(9, "PRODUCIBLE_DETERMINISTIC", "Each linear factor supplies an exact root with zero-product verification.", "factored-equation-solving", ["MOET2018-G9-NAA-P072-013"]),
  ...decisions(9, "PRODUCIBLE_DETERMINISTIC", "Root sum/product and coefficient identities give an exact Viete oracle.", "viete-theorem-applications", ["MOET2018-G9-NAA-P072-015"]),
  ...decisions(9, "PRODUCIBLE_DETERMINISTIC", "Explicit real-number comparisons permit exact basic inequality property checks.", "inequality-concepts", ["MOET2018-G9-NAA-P072-016"]),
  ...decisions(9, "PRODUCIBLE_DETERMINISTIC", "Substitution into both public equations exactly determines system-solution membership.", "linear-system-solution-concept", ["MOET2018-G9-NAA-P072-017"]),
  ...decisions(9, "PRODUCIBLE_DETERMINISTIC", "Coefficient and degree constraints exactly determine quadratic-equation membership.", "quadratic-equation-concept", ["MOET2018-G9-NAA-P072-018"]),
  ...decisions(9, "PRODUCIBLE_DETERMINISTIC", "Transitivity and order-preserving/reversing operations are exactly checkable on rational fixtures.", "inequality-properties", ["MOET2018-G9-NAA-P073-024"]),
  ...decisions(9, "PRODUCIBLE_DETERMINISTIC", "A candidate value can be substituted into a linear inequality to verify solution membership exactly.", "linear-inequality-concept", ["MOET2018-G9-NAA-P073-025"]),
  ...decisions(9, "PRODUCIBLE_DETERMINISTIC", "A public finite dataset and stated communication goal determine a bounded serialized table/chart answer.", "data-representation-selection", ["MOET2018-G9-STA-P076-001"]),
  ...decisions(9, "PRODUCIBLE_DETERMINISTIC", "Two text-serialized representations can be converted and compared against the same public dataset exactly.", "data-representation-conversion", ["MOET2018-G9-STA-P076-002"]),
  ...decisions(9, "PRODUCIBLE_DETERMINISTIC", "A public frequency table supports exact interpretation of frequency's role.", "frequency-meaning", ["MOET2018-G9-STA-P077-012"]),
  ...decisions(9, "PRODUCIBLE_DETERMINISTIC", "Fictional, fully specified cross-subject datasets permit source-safe recognition without external factual claims.", "statistics-cross-context", ["MOET2018-G9-STA-P077-014"]),
  ...decisions(9, "PRODUCIBLE_DETERMINISTIC", "A fully enumerated finite random trial permits exact sample-space recognition.", "random-experiment-sample-space", ["MOET2018-G9-STA-P077-015"]),
  ...decisions(9, "PRODUCIBLE_DETERMINISTIC", "Counts and sample size determine exact relative-frequency tables and serialized chart values.", "relative-frequency-table-chart", ["MOET2018-G9-STA-P077-017"]),
  ...decisions(9, "PRODUCIBLE_DETERMINISTIC", "Counts from a complete finite dataset determine exact frequency tables and serialized chart values.", "frequency-table-chart", ["MOET2018-G9-STA-P077-018"]),
] as const;

const g9Excluded = [
  ...decisions(9, "ALREADY_COVERED_SEMANTICALLY", "Same grade, page and scope: both outcomes require recognition of sine, cosine, tangent and cotangent of an acute angle; P074-014 is the more explicit canonical wording.", null, ["MOET2018-G9-GEO-P074-016"], "moet2018-g9-geo-p074-014"),
  ...decisions(9, "VISUAL_EVIDENCE_REQUIRED", "The outcome explicitly requires drawing a quadratic-function graph; the retained answer contract cannot verify the produced graph.", null, ["MOET2018-G9-NAA-P071-005", "MOET2018-G9-NAA-P071-009"]),
  ...decisions(9, "VISUAL_EVIDENCE_REQUIRED", "The conjunctive outcome requires creating the named solid; a text answer cannot prove the constructed object.", null, ["MOET2018-G9-GEO-P073-002", "MOET2018-G9-GEO-P073-003", "MOET2018-G9-GEO-P073-004"]),
  ...decisions(9, "VISUAL_EVIDENCE_REQUIRED", "The outcome explicitly depends on recognizing real-world regular forms through concrete visual evidence not present in the candidate.", null, ["MOET2018-G9-GEO-P076-002"]),
  ...decisions(9, "OPEN_ENDED_OR_EXPERIENTIAL", "Recognition of beauty in nature is subjective and has no unique deterministic answer.", null, ["MOET2018-G9-GEO-P076-004"]),
  ...decisions(9, "OPEN_ENDED_OR_EXPERIENTIAL", "Observed geometry-software use or software drawing cannot be inferred from a final answer.", null, ["MOET2018-G9-GEO-P076-006", "MOET2018-G9-GEO-P076-007"]),
  ...decisions(9, "AUTOMATED_VERIFICATION_INSUFFICIENT", "A numeric answer cannot prove the required calculator-use process, and no deterministic interaction trace is retained.", null, [
    "MOET2018-G9-NAA-P071-008", "MOET2018-G9-NAA-P072-020", "MOET2018-G9-NAA-P072-021", "MOET2018-G9-GEO-P074-018",
  ]),
  ...decisions(9, "OPEN_ENDED_OR_EXPERIENTIAL", "The retained source classifies this as practical/experiential activity without a complete deterministic assessment contract.", null, [
    "MOET2018-G9-EXP-P078-001", "MOET2018-G9-EXP-P078-002", "MOET2018-G9-EXP-P078-003",
    "MOET2018-G9-EXP-P078-004", "MOET2018-G9-EXP-P078-005", "MOET2018-G9-EXP-P078-006",
    "MOET2018-G9-EXP-P078-007", "MOET2018-G9-EXP-P078-008", "MOET2018-G9-EXP-P078-009",
  ]),
] as const;

const semanticallyVerifiedGeneratorOutcomeIds = new Set([
  // Grade 7: exact order/power/root/measurement/angle oracles.
  "MOET2018-G7-NAA-P056-008",
  "MOET2018-G7-NAA-P056-009",
  "MOET2018-G7-NAA-P056-013",
  "MOET2018-G7-NAA-P056-015",
  "MOET2018-G7-NAA-P057-027",
  "MOET2018-G7-GEO-P058-002",
  "MOET2018-G7-GEO-P059-007",
  // Grade 8: exact function, Pythagoras, angle and proportional-length oracles.
  "MOET2018-G8-NAA-P064-015",
  "MOET2018-G8-NAA-P064-018",
  "MOET2018-G8-GEO-P065-002",
  "MOET2018-G8-GEO-P066-008",
  "MOET2018-G8-GEO-P067-023",
  "MOET2018-G8-GEO-P067-029",
  // Grade 9: exact roots, trigonometry, circle relations/measurement and rotations.
  "MOET2018-G9-NAA-P071-002",
  "MOET2018-G9-GEO-P073-005",
  "MOET2018-G9-GEO-P074-008",
  "MOET2018-G9-GEO-P074-009",
  "MOET2018-G9-GEO-P074-010",
  "MOET2018-G9-GEO-P074-011",
  "MOET2018-G9-GEO-P074-012",
  "MOET2018-G9-GEO-P074-013",
  "MOET2018-G9-GEO-P074-014",
  "MOET2018-G9-GEO-P074-015",
  "MOET2018-G9-GEO-P074-017",
  "MOET2018-G9-GEO-P075-025",
  "MOET2018-G9-GEO-P075-026",
  "MOET2018-G9-GEO-P075-027",
  "MOET2018-G9-GEO-P075-028",
  "MOET2018-G9-GEO-P075-029",
  "MOET2018-G9-GEO-P076-001",
  "MOET2018-G9-GEO-P076-003",
]);

const auditedDecisions = [
  ...g7Producible,
  ...g7Excluded,
  ...g8Producible,
  ...g8Excluded,
  ...g9Producible,
  ...g9Excluded,
] satisfies readonly WaveKClassificationDecision[];

export const waveKClassificationDecisionsGrades7To9 = Object.freeze(auditedDecisions.map((decision) =>
  decision.classification === "PRODUCIBLE_DETERMINISTIC" && !semanticallyVerifiedGeneratorOutcomeIds.has(decision.outcomeId)
    ? {
      ...decision,
      classification: "AUTOMATED_VERIFICATION_INSUFFICIENT" as const,
      reason: "The retained source row is clear, but the repository has no family-specific independent semantic oracle and structurally diverse pool for the complete outcome; broad arithmetic surrogates are prohibited.",
      templateFamily: null,
      semanticAliasTargetSkillId: null,
    }
    : decision,
));

export const waveKClassificationsG7G9 = waveKClassificationDecisionsGrades7To9;
