import type { WaveKClassificationDecision } from "./wave-k-types.ts";

const producible = (
  outcomeId: string,
  grade: 2 | 3 | 4,
  templateFamily: string,
  reason: string,
): WaveKClassificationDecision => ({
  outcomeId,
  grade,
  classification: "PRODUCIBLE_DETERMINISTIC",
  reason,
  templateFamily,
  semanticAliasTargetSkillId: null,
});

const excluded = (
  outcomeId: string,
  grade: 2 | 3 | 4,
  classification: Exclude<WaveKClassificationDecision["classification"], "PRODUCIBLE_DETERMINISTIC" | "ALREADY_COVERED_SEMANTICALLY">,
  reason: string,
): WaveKClassificationDecision => ({
  outcomeId,
  grade,
  classification,
  reason,
  templateFamily: null,
  semanticAliasTargetSkillId: null,
});

export const waveKClassificationsG2G4 = [
  producible("MOET2018-G2-NUM-P025-005", 2, "G2_OPERATION_COMPONENT_LABELS", "A public addition or subtraction equation has exactly named operand and result positions; a parser and integer identity oracle determine the unique label or value."),
  excluded("MOET2018-G2-GEO-P027-018", 2, "AUTOMATED_VERIFICATION_INSUFFICIENT", "Real-world measurement estimates admit context-dependent tolerances that the source does not define, so an exact accepted answer cannot be derived independently."),
  excluded("MOET2018-G2-NUM-P025-016", 2, "AUTOMATED_VERIFICATION_INSUFFICIENT", "Estimating objects by groups of ten has no source-defined rounding or tolerance contract; Wave F explicitly excluded this approximate subpart."),
  producible("MOET2018-G2-STA-P028-002", 2, "G2_FINITE_EVENT_MODALITY", "An explicit finite sample space and event predicate allow exact zero, full, or partial event-count classification as impossible, certain, or possible."),
  excluded("MOET2018-G2-EXP-P028-001", 2, "OPEN_ENDED_OR_EXPERIENTIAL", "The outcome requires learners to collect, classify, record, and count objects in their own school or classroom rather than answer a closed deterministic candidate."),
  excluded("MOET2018-G2-EXP-P028-002", 2, "OPEN_ENDED_OR_EXPERIENTIAL", "The outcome requires hands-on measuring, estimating, clock/calendar use, and personal schedule organization in real contexts."),
  producible("MOET2018-G2-GEO-P026-004", 2, "G2_LABELED_MASS_COMPARISON", "Public integer masses in the same declared unit have a unique heavier/lighter relation verified by exact comparison."),
  producible("MOET2018-G2-GEO-P027-013", 2, "G2_DAY_HOUR_MINUTE_FACTS", "The declared curriculum identities one day equals 24 hours and one hour equals 60 minutes support exact lookup and integer-conversion oracles."),
  producible("MOET2018-G2-GEO-P026-003", 2, "G2_KILOGRAM_QUANTITY_LITERACY", "A public integer quantity within 1000 kg can be matched to or read from an exact numeral-and-unit representation."),
  producible("MOET2018-G2-GEO-P026-005", 2, "G2_LITRE_QUANTITY_LITERACY", "A public integer quantity within 1000 litres can be matched to or read from an exact numeral-and-unit representation."),
  excluded("MOET2018-G2-GEO-P027-016", 2, "OPEN_ENDED_OR_EXPERIENTIAL", "Using a physical scale, marked ruler, or vessel is a hands-on performance; the current candidate contract cannot observe correct tool use."),
  producible("MOET2018-G2-NUM-P024-003", 2, "G2_ROUND_HUNDRED_RECOGNITION", "Within the grade range, exact divisibility by 100 distinguishes a whole-hundred number and supports unique recognition and missing-digit forms."),
  producible("MOET2018-G2-NUM-P024-001", 2, "G2_NUMBER_READ_WRITE_TO_1000", "Canonical Vietnamese numeral tokens and integer parsing provide a bijective read/write oracle for values from 0 through 1000."),
  producible("MOET2018-G2-NUM-P024-002", 2, "G2_PREDECESSOR_SUCCESSOR_TO_1000", "For an interior integer in the declared range, predecessor and successor are uniquely computed by subtracting or adding one."),
  producible("MOET2018-G2-NUM-P024-004", 2, "G2_HUNDREDS_TENS_ONES_EXPANSION", "Base-ten decomposition into hundreds, tens, and ones is uniquely reconstructed and checked by an independent weighted-place sum."),
  producible("MOET2018-G2-GEO-P026-001", 2, "G2_TEXTUAL_SHAPE_PROPERTY_APPLICATION", "A closed scenario that publicly states all shape properties can ask one exact application question verified against a small explicit shape-property table."),
  excluded("MOET2018-G2-GEO-P026-006", 2, "VISUAL_EVIDENCE_REQUIRED", "Folding, cutting, joining, arranging, and creating a shape with personal manipulatives requires observable visual or physical evidence absent from the candidate."),
  excluded("MOET2018-G2-GEO-P026-009", 2, "VISUAL_EVIDENCE_REQUIRED", "Drawing a segment of a prescribed length requires inspection of the produced drawing and scale, which the current answer contract cannot capture."),
  excluded("MOET2018-G2-GEO-P026-002", 2, "VISUAL_EVIDENCE_REQUIRED", "The source explicitly requires recognition through visual images of points, lines, curves, polylines, and collinearity; substituting verbal definitions would not establish parity."),
  excluded("MOET2018-G2-GEO-P026-007", 2, "VISUAL_EVIDENCE_REQUIRED", "Quadrilateral recognition is specified through manipulatives or real objects, but no retained public visual is represented in the candidate contract."),
  excluded("MOET2018-G2-GEO-P026-008", 2, "VISUAL_EVIDENCE_REQUIRED", "Cylinder and sphere recognition is specified through manipulatives or real objects, but no retained public visual is represented in the candidate contract."),
  excluded("MOET2018-G2-GEO-P027-010", 2, "VISUAL_EVIDENCE_REQUIRED", "Reading an analogue clock at quarter- and half-hour positions requires a rendered clock face; describing hand positions in text would test a different skill."),
  producible("MOET2018-G2-GEO-P027-014", 2, "G2_CALENDAR_MONTH_DAY_FACTS", "Fixed month-length facts and a fully public calendar fragment provide exact date and day-count answers without personal or historical assertions."),
  excluded("MOET2018-G2-GEO-P027-015", 2, "VISUAL_EVIDENCE_REQUIRED", "The source requires recognition of Vietnamese banknotes through images; denomination text alone would not prove image-recognition parity."),

  excluded("MOET2018-G3-EXP-P034-001", 3, "OPEN_ENDED_OR_EXPERIENTIAL", "The outcome requires real-world calculation, measurement, weighing, pouring, and estimation activities whose observed performance is not a closed candidate response."),
  excluded("MOET2018-G3-EXP-P034-002", 3, "OPEN_ENDED_OR_EXPERIENTIAL", "Learners must collect, classify, and arrange data about objects in their own school or classroom, so the evidence is experiential rather than deterministic."),
  producible("MOET2018-G3-GEO-P032-019", 3, "G3_CALENDAR_MONTH_FACTS", "A fully public calendar fragment and fixed month ordering or month-length facts yield a unique answer under an explicit year contract."),
  excluded("MOET2018-G3-GEO-P032-020", 3, "OPEN_ENDED_OR_EXPERIENTIAL", "Correct use of a physical scale, millimetre ruler, thermometer, or measuring vessel cannot be observed through the current answer contract."),
  producible("MOET2018-G3-GEO-P033-023", 3, "G3_CLOSED_MEASUREMENT_APPLICATION", "A closed word problem with every quantity and unit stated publicly supports exact unit normalization and integer arithmetic."),
  excluded("MOET2018-G3-GEO-P033-024", 3, "AUTOMATED_VERIFICATION_INSUFFICIENT", "Real-world measurement estimates have no source-defined tolerance interval, leaving more than one defensible answer."),
  producible("MOET2018-G3-STA-P033-003", 3, "G3_SINGLE_TRIAL_OUTCOME_MODALITY", "An explicit finite one-trial sample space and event predicate allow exact enumeration and unique possible, certain, or impossible classification."),
  producible("MOET2018-G3-NUM-P030-014", 3, "G3_NUMERIC_EXPRESSION_GRAMMAR", "A restricted public grammar for numerals, operators, and parentheses permits deterministic expression recognition and independent exact evaluation."),
  excluded("MOET2018-G3-GEO-P031-007", 3, "VISUAL_EVIDENCE_REQUIRED", "Checking a right angle with a set square and drawing a circle with a compass require inspection of physical tool placement and the resulting figure."),
  excluded("MOET2018-G3-GEO-P031-008", 3, "VISUAL_EVIDENCE_REQUIRED", "Drawing a right angle, circle, or decoration requires visual validation of the learner-produced construction."),
  excluded("MOET2018-G3-GEO-P031-009", 3, "VISUAL_EVIDENCE_REQUIRED", "Drawing squares and rectangles on a grid requires a submitted visual with grid alignment and side constraints."),
  producible("MOET2018-G3-NUM-P030-015", 3, "G3_MULTIPLICATION_PROPERTIES_AND_INVERSE", "Exact integer identities verify commutative and associative transformations and multiplication-division inverse relationships."),
  producible("MOET2018-G3-NUM-P029-005", 3, "G3_ROMAN_NUMERALS_I_TO_XX", "A finite canonical mapping between integers 1 through 20 and Roman numerals gives a unique bidirectional oracle."),
  producible("MOET2018-G3-NUM-P029-006", 3, "G3_ROUND_THOUSAND_TEN_THOUSAND", "Exact divisibility by 1000 or 10000 verifies recognition and completion of round-thousand and round-ten-thousand numbers."),
  producible("MOET2018-G3-NUM-P029-009", 3, "G3_ORDER_UP_TO_FOUR_NUMBERS", "Sorting at most four public integers within 100000 yields a unique ordered sequence or requested position."),
  producible("MOET2018-G3-NUM-P029-011", 3, "G3_EXTREMA_UP_TO_FOUR_NUMBERS", "The minimum or maximum of at most four public integers within 100000 is independently enumerable and unique when inputs are constrained appropriately."),
  producible("MOET2018-G3-NUM-P029-001", 3, "G3_NUMBER_READ_WRITE_TO_100000", "Canonical Vietnamese numeral tokens and integer parsing provide a deterministic read/write oracle through 100000."),
  producible("MOET2018-G3-NUM-P029-002", 3, "G3_DECLARED_PLACE_ROUNDING", "A declared target place and explicit half-up tie rule produce a unique rounded integer at tens through ten-thousands."),
  producible("MOET2018-G3-NUM-P029-003", 3, "G3_COMPARE_TO_100000", "Exact integer comparison within 100000 uniquely determines less-than, equal-to, or greater-than."),
  producible("MOET2018-G3-NUM-P029-004", 3, "G3_DECIMAL_PLACE_VALUE_EXPANSION", "Base-ten digit extraction and a weighted-place sum independently verify expanded form and digit value."),
  producible("MOET2018-G3-GEO-P031-004", 3, "G3_PLANE_SHAPE_ELEMENT_FACTS", "Closed prompts that state the named rectangle, square, or circle support exact element-count and radius-diameter relationship checks without hidden imagery."),
  producible("MOET2018-G3-GEO-P031-005", 3, "G3_SOLID_ELEMENT_FACTS", "Closed cube and cuboid prompts support exact vertex, edge, and face counts using a finite explicit topology oracle."),
  excluded("MOET2018-G3-GEO-P031-006", 3, "VISUAL_EVIDENCE_REQUIRED", "Recognizing an arbitrary triangle or quadrilateral requires a public rendered figure; reducing it to a stated side count would not test visual recognition."),
  producible("MOET2018-G3-GEO-P032-014", 3, "G3_LITRE_MILLILITRE_RELATION", "The exact identity 1 litre equals 1000 millilitres supports integer conversions and equivalence checks."),
  producible("MOET2018-G3-GEO-P032-016", 3, "G3_KILOGRAM_GRAM_RELATION", "The exact identity 1 kilogram equals 1000 grams supports integer conversions and equivalence checks."),
  producible("MOET2018-G3-GEO-P032-017", 3, "G3_CELSIUS_QUANTITY_LITERACY", "Public integer temperatures with an explicit degrees-Celsius unit support exact reading, writing, and comparison."),
  excluded("MOET2018-G3-GEO-P032-018", 3, "VISUAL_EVIDENCE_REQUIRED", "The source requires recognition of Vietnamese banknote denominations, including 200000 and 500000 dong notes, which requires retained public images."),
  excluded("MOET2018-G3-GEO-P031-001", 3, "VISUAL_EVIDENCE_REQUIRED", "Folding, cutting, joining, arranging, drawing, and decorative construction require inspection of a visual or physical result."),
  producible("MOET2018-G3-GEO-P031-002", 3, "G3_MIDPOINT_FROM_EXPLICIT_CONSTRAINTS", "Public collinearity, betweenness, and equal-length constraints uniquely determine midpoint status or a missing segment length."),
  excluded("MOET2018-G3-GEO-P031-003", 3, "VISUAL_EVIDENCE_REQUIRED", "Recognizing right and non-right angles as figures requires a rendered angle; replacing the figure with its degree measure tests classification from numbers instead."),
  excluded("MOET2018-G3-GEO-P032-011", 3, "VISUAL_EVIDENCE_REQUIRED", "Reading an analogue clock to five minutes or one minute requires a rendered clock face and visible hand positions."),

  producible("MOET2018-G4-GEO-P037-002", 4, "G4_ANGLE_CLASSIFICATION_BY_MEASURE", "When the angle measure is public, exact interval and equality checks uniquely classify acute, obtuse, or straight angles without a hidden diagram."),
  excluded("MOET2018-G4-GEO-P037-003", 4, "VISUAL_EVIDENCE_REQUIRED", "Recognizing parallel and perpendicular line pairs at Grade 4 requires visible line geometry; textual declaration would reveal the answer."),
  excluded("MOET2018-G4-GEO-P038-012", 4, "VISUAL_EVIDENCE_REQUIRED", "Using a protractor to measure 60, 90, 120, or 180 degrees requires inspection of instrument alignment and a rendered angle."),
  producible("MOET2018-G4-NUM-P036-017", 4, "G4_DIRECT_TWO_THREE_STEP_PROBLEMS", "A closed scenario with all facts and units public supports a fixed two- or three-operation derivation and exact contextual answer."),
  producible("MOET2018-G4-GEO-P038-007", 4, "G4_CLOSED_MEASUREMENT_APPLICATION", "Closed length, area, mass, capacity, time, or money problems can declare all quantities and use exact conversion plus arithmetic oracles."),
  producible("MOET2018-G4-GEO-P038-008", 4, "G4_AREA_UNIT_RELATIONS", "Exact square-unit scale factors support deterministic conversions among square millimetres, square decimetres, and square metres."),
  excluded("MOET2018-G4-STA-P039-002", 4, "VISUAL_EVIDENCE_REQUIRED", "Reading and describing a bar chart requires the chart itself; a pre-transcribed number list would test data reading rather than chart reading."),
  producible("MOET2018-G4-STA-P039-004", 4, "G4_REPEATED_TRIAL_FREQUENCY", "A complete public sequence of trial results and event predicate yield an exact occurrence count and checked sample size."),
  excluded("MOET2018-G4-STA-P039-006", 4, "VISUAL_EVIDENCE_REQUIRED", "Drawing conclusions from a bar chart requires a public chart whose bars, labels, and scale can be validated against its data."),
  producible("MOET2018-G4-STA-P038-001", 4, "G4_STATISTICAL_SEQUENCE_RECOGNITION", "A fully public finite data sequence and collection context allow deterministic recognition, item count, and value lookup."),
  excluded("MOET2018-G4-STA-P039-003", 4, "VISUAL_EVIDENCE_REQUIRED", "Solving a problem from bar-chart data requires the candidate to carry a validated public chart, which the current question contract does not represent."),
  excluded("MOET2018-G4-STA-P039-005", 4, "VISUAL_EVIDENCE_REQUIRED", "Detecting a pattern by observing a bar chart requires validated chart geometry and labels rather than a substituted text sequence."),
  excluded("MOET2018-G4-EXP-P039-001", 4, "OPEN_ENDED_OR_EXPERIENTIAL", "The outcome combines hands-on real-world measurement, estimation, and external event research with locally variable observations."),
  excluded("MOET2018-G4-EXP-P040-002", 4, "OPEN_ENDED_OR_EXPERIENTIAL", "Practising real buying, selling, and money exchange is an experiential performance rather than a closed deterministic response."),
  excluded("MOET2018-G4-EXP-P040-003", 4, "OPEN_ENDED_OR_EXPERIENTIAL", "The outcome requires collecting, analysing, and presenting locally sourced real-world data and cannot be reduced to a supplied fixture without changing the outcome."),
  producible("MOET2018-G4-NUM-P035-006", 4, "G4_SUBSTITUTE_ONE_TO_THREE_VARIABLES", "Public variable values and a restricted integer expression grammar give one exact substitution and evaluation result."),
  producible("MOET2018-G4-NUM-P035-013", 4, "G4_CONVENIENT_CALCULATION_PROPERTIES", "Equivalent integer-expression evaluation verifies regrouping, compensation, and distributive strategies while structure tags distinguish methods."),
  producible("MOET2018-G4-NUM-P035-014", 4, "G4_ADDITION_PROPERTIES_AND_INVERSE", "Exact integer identities verify addition commutativity, associativity, and addition-subtraction inverse transformations."),
  producible("MOET2018-G4-NUM-P035-015", 4, "G4_MULTIPLICATION_PROPERTIES_AND_INVERSE", "Exact nonzero integer identities verify multiplication commutativity, associativity, and multiplication-division inverse transformations."),
  producible("MOET2018-G4-NUM-P036-016", 4, "G4_FRACTION_READ_WRITE", "Canonical numerator-denominator pairs with positive nonzero denominators provide deterministic numeral and verbal fraction matching."),
  producible("MOET2018-G4-NUM-P036-024", 4, "G4_FRACTION_EXTREMA_RESTRICTED_DENOMINATORS", "For at most four fractions with equal denominators or one denominator divisible by the others, exact rational comparison uniquely determines minimum or maximum."),
  excluded("MOET2018-G4-GEO-P037-001", 4, "VISUAL_EVIDENCE_REQUIRED", "The broad outcome requires measuring angles and drawing, assembling, or constructing figures, all of which need observable visual work."),
  excluded("MOET2018-G4-GEO-P037-004", 4, "VISUAL_EVIDENCE_REQUIRED", "Recognizing arbitrary parallelograms and rhombi requires a rendered figure with verifiable side and parallelism constraints."),
  excluded("MOET2018-G4-GEO-P037-005", 4, "VISUAL_EVIDENCE_REQUIRED", "Measuring, drawing, assembling, and constructing learned plane or solid figures requires inspection of the resulting visual object."),
  excluded("MOET2018-G4-GEO-P037-006", 4, "VISUAL_EVIDENCE_REQUIRED", "Drawing parallel and perpendicular lines with a ruler and set square requires visual validation of construction and tool use."),
  producible("MOET2018-G4-GEO-P038-009", 4, "G4_SECOND_CENTURY_TIME_RELATIONS", "Declared exact time identities, including 60 seconds per minute and 100 years per century, support integer conversion and equivalence oracles."),
  producible("MOET2018-G4-GEO-P038-010", 4, "G4_DEGREE_UNIT_LITERACY", "A public numeric angle measure and degree symbol support exact reading, writing, and unit recognition."),
  excluded("MOET2018-G4-GEO-P038-011", 4, "OPEN_ENDED_OR_EXPERIENTIAL", "Correct practical use of measuring, weighing, pouring, counting, and time instruments cannot be observed through the current answer contract."),
  excluded("MOET2018-G4-GEO-P038-014", 4, "AUTOMATED_VERIFICATION_INSUFFICIENT", "The source gives contextual real-world estimates but no accepted tolerance or unique estimation rule for an independent oracle."),
  producible("MOET2018-G4-NUM-P034-005", 4, "G4_EVEN_ODD_CLASSIFICATION", "Integer parity is uniquely determined by the remainder modulo two and supports recognition, completion, and constraint forms."),
  producible("MOET2018-G4-NUM-P035-007", 4, "G4_DECLARED_PLACE_ROUNDING", "A declared rounding place and explicit half-up tie rule yield a unique result from tens through hundred-thousands."),
  producible("MOET2018-G4-NUM-P035-010", 4, "G4_MULTIPLY_DIVIDE_POWERS_OF_TEN", "Exact integer multiplication or divisible-integer division by 10, 100, or 1000 supports direct and missing-value structures."),
  producible("MOET2018-G4-NUM-P035-012", 4, "G4_ARITHMETIC_MEAN", "The exact sum divided by the public count independently verifies the arithmetic mean, with non-integral fixtures represented rationally or excluded by blueprint."),
  producible("MOET2018-G4-NUM-P034-001", 4, "G4_NUMBER_READ_WRITE_TO_MILLIONS", "Canonical Vietnamese numeral tokens and integer parsing provide a deterministic read/write oracle through the millions class."),
  excluded("MOET2018-G4-NUM-P034-002", 4, "UNKNOWN_SOURCE_MAPPING", "The retained paraphrase only says to become familiar with the natural-number sequence and its characteristics; it does not identify which characteristics form a closed candidate skill."),
  producible("MOET2018-G4-NUM-P034-003", 4, "G4_COMPARE_TO_MILLIONS", "Exact integer comparison within the millions class uniquely determines order and requested extrema."),
  producible("MOET2018-G4-NUM-P034-004", 4, "G4_MILLIONS_PLACE_VALUE_EXPANSION", "Base-ten digit extraction and a weighted-place sum uniquely verify decimal composition and each digit's positional value."),
] as const satisfies readonly WaveKClassificationDecision[];

