import type {
  WaveKClassificationDecision,
  WaveKOutcomeClassification,
} from "./wave-k-types.ts";

type ProductionGrade = 5 | 6;

const decision = (
  outcomeId: string,
  grade: ProductionGrade,
  classification: WaveKOutcomeClassification,
  reason: string,
  templateFamily: string | null,
): WaveKClassificationDecision => ({
  outcomeId,
  grade,
  classification,
  reason,
  templateFamily,
  semanticAliasTargetSkillId: null,
});

const exactReason =
  "The retained outcome can be represented with complete public data and checked by a generator-independent exact oracle.";
const visualReason =
  "The retained outcome requires a diagram, construction, chart, pictogram, or other visual evidence channel that the deterministic candidate contract does not currently verify.";
const openReason =
  "The retained outcome assesses an activity, tool use, observation, collection, or subjective/open-ended practice rather than one exact deterministic response.";

export const waveKClassificationsG5G6: readonly WaveKClassificationDecision[] = [
  // Grade 5: 37 unique uncovered outcomes (34 source-verifiable rows plus 3 experiential rows).
  decision("MOET2018-G5-GEO-P043-001", 5, "OPEN_ENDED_OR_EXPERIENTIAL", openReason, null),
  decision("MOET2018-G5-GEO-P043-002", 5, "VISUAL_EVIDENCE_REQUIRED", visualReason, null),
  decision("MOET2018-G5-GEO-P043-003", 5, "PRODUCIBLE_DETERMINISTIC", exactReason, "AREA_UNIT_IDENTITY_CONVERSION"),
  decision("MOET2018-G5-GEO-P043-004", 5, "VISUAL_EVIDENCE_REQUIRED", visualReason, null),
  decision("MOET2018-G5-GEO-P043-005", 5, "VISUAL_EVIDENCE_REQUIRED", visualReason, null),
  decision("MOET2018-G5-GEO-P043-006", 5, "VISUAL_EVIDENCE_REQUIRED", visualReason, null),
  decision("MOET2018-G5-GEO-P043-007", 5, "VISUAL_EVIDENCE_REQUIRED", visualReason, null),
  decision("MOET2018-G5-GEO-P044-008", 5, "PRODUCIBLE_DETERMINISTIC", exactReason, "DIMENSIONAL_MOTION_EXACT"),
  decision("MOET2018-G5-GEO-P044-009", 5, "PRODUCIBLE_DETERMINISTIC", exactReason, "DIMENSIONAL_MEASUREMENT_CONTEXT"),
  decision("MOET2018-G5-GEO-P044-010", 5, "PRODUCIBLE_DETERMINISTIC", exactReason, "VELOCITY_UNIT_IDENTITY"),
  decision("MOET2018-G5-GEO-P044-011", 5, "OPEN_ENDED_OR_EXPERIENTIAL", openReason, null),
  decision("MOET2018-G5-GEO-P044-012", 5, "OPEN_ENDED_OR_EXPERIENTIAL", openReason, null),
  decision(
    "MOET2018-G5-GEO-P044-014",
    5,
    "AUTOMATED_VERIFICATION_INSUFFICIENT",
    "The retained estimation outcome does not declare an acceptable tolerance or a public measurement model, so semantic parity cannot be proved by an exact oracle.",
    null,
  ),
  decision("MOET2018-G5-GEO-P044-015", 5, "PRODUCIBLE_DETERMINISTIC", exactReason, "CIRCLE_MEASURE_DECLARED_PI"),
  decision("MOET2018-G5-GEO-P044-016", 5, "PRODUCIBLE_DETERMINISTIC", exactReason, "TRIANGLE_TRAPEZOID_AREA"),
  decision("MOET2018-G5-GEO-P044-017", 5, "PRODUCIBLE_DETERMINISTIC", exactReason, "RECTANGULAR_SOLID_MEASURE"),
  decision("MOET2018-G5-NUM-P040-001", 5, "PRODUCIBLE_DETERMINISTIC", exactReason, "NATURAL_REPRESENT_COMPARE_ORDER"),
  decision("MOET2018-G5-NUM-P040-003", 5, "PRODUCIBLE_DETERMINISTIC", exactReason, "NATURAL_OPERATION_AST"),
  decision("MOET2018-G5-NUM-P040-004", 5, "PRODUCIBLE_DETERMINISTIC", exactReason, "NATURAL_PROPERTY_REWRITE"),
  decision("MOET2018-G5-NUM-P041-006", 5, "PRODUCIBLE_DETERMINISTIC", exactReason, "APPLIED_FRACTION_RATIONAL"),
  decision("MOET2018-G5-NUM-P041-007", 5, "PRODUCIBLE_DETERMINISTIC", exactReason, "DECIMAL_FRACTION_MIXED_REPRESENTATION"),
  decision("MOET2018-G5-NUM-P042-016", 5, "PRODUCIBLE_DETERMINISTIC", exactReason, "SCALED_DECIMAL_ROUNDING"),
  decision("MOET2018-G5-NUM-P042-017", 5, "PRODUCIBLE_DETERMINISTIC", exactReason, "MAP_SCALE_RATIO"),
  decision("MOET2018-G5-NUM-P042-021", 5, "PRODUCIBLE_DETERMINISTIC", exactReason, "DECIMAL_POWER_OF_TEN_SCALE"),
  decision("MOET2018-G5-NUM-P042-022", 5, "PRODUCIBLE_DETERMINISTIC", exactReason, "DECIMAL_ORDER_UP_TO_FOUR"),
  decision("MOET2018-G5-NUM-P042-023", 5, "PRODUCIBLE_DETERMINISTIC", exactReason, "DECIMAL_PROPERTY_REWRITE"),
  decision(
    "MOET2018-G5-NUM-P043-024",
    5,
    "AUTOMATED_VERIFICATION_INSUFFICIENT",
    "An exact result cannot independently prove that the learner used a handheld calculator, so the source-bound performance outcome is not observable in this candidate model.",
    null,
  ),
  decision("MOET2018-G5-STA-P045-001", 5, "PRODUCIBLE_DETERMINISTIC", exactReason, "EMPIRICAL_FREQUENCY_RATIO"),
  decision("MOET2018-G5-STA-P045-002", 5, "VISUAL_EVIDENCE_REQUIRED", visualReason, null),
  decision("MOET2018-G5-STA-P045-003", 5, "VISUAL_EVIDENCE_REQUIRED", visualReason, null),
  decision("MOET2018-G5-STA-P045-004", 5, "VISUAL_EVIDENCE_REQUIRED", visualReason, null),
  decision(
    "MOET2018-G5-STA-P045-005",
    5,
    "AUTOMATED_VERIFICATION_INSUFFICIENT",
    "The source permits several valid data representations but supplies no exclusive selection criterion; asking for the most suitable form would not have one independently provable answer.",
    null,
  ),
  decision("MOET2018-G5-STA-P045-006", 5, "VISUAL_EVIDENCE_REQUIRED", visualReason, null),
  decision("MOET2018-G5-STA-P045-008", 5, "PRODUCIBLE_DETERMINISTIC", exactReason, "DATA_CLASSIFY_COMPARE_ORDER"),
  decision("MOET2018-G5-EXP-P046-001", 5, "OPEN_ENDED_OR_EXPERIENTIAL", openReason, null),
  decision("MOET2018-G5-EXP-P046-002", 5, "OPEN_ENDED_OR_EXPERIENTIAL", openReason, null),
  decision("MOET2018-G5-EXP-P046-003", 5, "OPEN_ENDED_OR_EXPERIENTIAL", openReason, null),

  // Grade 6: 72 unique uncovered outcomes (66 source-verifiable rows plus 6 experiential rows).
  decision("MOET2018-G6-GEO-P050-001", 6, "PRODUCIBLE_DETERMINISTIC", exactReason, "REGULAR_SHAPE_PROPERTY_ENUM"),
  decision("MOET2018-G6-GEO-P050-002", 6, "VISUAL_EVIDENCE_REQUIRED", visualReason, null),
  decision("MOET2018-G6-GEO-P051-004", 6, "PRODUCIBLE_DETERMINISTIC", exactReason, "QUADRILATERAL_PROPERTY_ENUM"),
  decision("MOET2018-G6-GEO-P051-005", 6, "VISUAL_EVIDENCE_REQUIRED", visualReason, null),
  decision("MOET2018-G6-GEO-P051-006", 6, "VISUAL_EVIDENCE_REQUIRED", visualReason, null),
  decision("MOET2018-G6-GEO-P051-007", 6, "VISUAL_EVIDENCE_REQUIRED", visualReason, null),
  decision("MOET2018-G6-GEO-P051-008", 6, "VISUAL_EVIDENCE_REQUIRED", visualReason, null),
  decision("MOET2018-G6-GEO-P051-009", 6, "VISUAL_EVIDENCE_REQUIRED", visualReason, null),
  decision("MOET2018-G6-GEO-P051-010", 6, "OPEN_ENDED_OR_EXPERIENTIAL", openReason, null),
  decision("MOET2018-G6-GEO-P051-011", 6, "VISUAL_EVIDENCE_REQUIRED", visualReason, null),
  decision("MOET2018-G6-GEO-P052-012", 6, "PRODUCIBLE_DETERMINISTIC", exactReason, "SEGMENT_MIDPOINT_LENGTH_EXACT"),
  decision("MOET2018-G6-GEO-P052-013", 6, "PRODUCIBLE_DETERMINISTIC", exactReason, "ANGLE_BAND_CLASSIFICATION"),
  decision("MOET2018-G6-GEO-P052-014", 6, "PRODUCIBLE_DETERMINISTIC", exactReason, "COORDINATE_COLLINEARITY"),
  decision("MOET2018-G6-GEO-P052-015", 6, "PRODUCIBLE_DETERMINISTIC", exactReason, "COORDINATE_BETWEENNESS"),
  decision("MOET2018-G6-GEO-P052-016", 6, "VISUAL_EVIDENCE_REQUIRED", visualReason, null),
  decision("MOET2018-G6-GEO-P052-017", 6, "VISUAL_EVIDENCE_REQUIRED", visualReason, null),
  decision("MOET2018-G6-GEO-P052-018", 6, "PRODUCIBLE_DETERMINISTIC", exactReason, "ANGLE_MEASURE_EXACT"),
  decision("MOET2018-G6-GEO-P052-019", 6, "VISUAL_EVIDENCE_REQUIRED", visualReason, null),
  decision("MOET2018-G6-GEO-P052-020", 6, "PRODUCIBLE_DETERMINISTIC", exactReason, "POINT_LINE_INCIDENCE"),
  decision("MOET2018-G6-GEO-P052-021", 6, "OPEN_ENDED_OR_EXPERIENTIAL", openReason, null),
  decision("MOET2018-G6-GEO-P052-022", 6, "OPEN_ENDED_OR_EXPERIENTIAL", openReason, null),
  decision("MOET2018-G6-NAA-P047-001", 6, "PRODUCIBLE_DETERMINISTIC", exactReason, "ROMAN_NUMERAL_CODEC_1_TO_30"),
  decision("MOET2018-G6-NAA-P047-002", 6, "PRODUCIBLE_DETERMINISTIC", exactReason, "NATURAL_DECIMAL_PLACE_REPRESENTATION"),
  decision("MOET2018-G6-NAA-P047-003", 6, "PRODUCIBLE_DETERMINISTIC", exactReason, "DIVISIBILITY_DIGIT_RULES"),
  decision("MOET2018-G6-NAA-P047-004", 6, "PRODUCIBLE_DETERMINISTIC", exactReason, "APPLIED_NATURAL_OPERATION_AST"),
  decision("MOET2018-G6-NAA-P047-005", 6, "PRODUCIBLE_DETERMINISTIC", exactReason, "NATURAL_ORDER_COMPARE"),
  decision("MOET2018-G6-NAA-P047-007", 6, "PRODUCIBLE_DETERMINISTIC", exactReason, "NATURAL_SET_MEMBERSHIP"),
  decision("MOET2018-G6-NAA-P047-008", 6, "PRODUCIBLE_DETERMINISTIC", exactReason, "OPERATION_PRECEDENCE_AST"),
  decision("MOET2018-G6-NAA-P047-009", 6, "PRODUCIBLE_DETERMINISTIC", exactReason, "SAME_BASE_POWER_PRODUCT_QUOTIENT"),
  decision("MOET2018-G6-NAA-P047-010", 6, "PRODUCIBLE_DETERMINISTIC", exactReason, "SET_NOTATION_MEMBERSHIP"),
  decision("MOET2018-G6-NAA-P047-011", 6, "PRODUCIBLE_DETERMINISTIC", exactReason, "NATURAL_OPERATION_AST"),
  decision("MOET2018-G6-NAA-P047-013", 6, "PRODUCIBLE_DETERMINISTIC", exactReason, "NATURAL_POWER_EXACT"),
  decision("MOET2018-G6-NAA-P047-014", 6, "PRODUCIBLE_DETERMINISTIC", exactReason, "NATURAL_DIVISIBILITY_RELATION"),
  decision("MOET2018-G6-NAA-P047-015", 6, "PRODUCIBLE_DETERMINISTIC", exactReason, "NATURAL_POWER_PROPERTY_REWRITE"),
  decision("MOET2018-G6-NAA-P047-016", 6, "PRODUCIBLE_DETERMINISTIC", exactReason, "NATURAL_PROPERTY_REWRITE"),
  decision("MOET2018-G6-NAA-P048-019", 6, "PRODUCIBLE_DETERMINISTIC", exactReason, "EUCLIDEAN_DIVISION_REMAINDER"),
  decision("MOET2018-G6-NAA-P048-020", 6, "PRODUCIBLE_DETERMINISTIC", exactReason, "INTEGER_OPPOSITE"),
  decision("MOET2018-G6-NAA-P048-021", 6, "PRODUCIBLE_DETERMINISTIC", exactReason, "INTEGER_SET_REPRESENTATION"),
  decision("MOET2018-G6-NAA-P048-022", 6, "PRODUCIBLE_DETERMINISTIC", exactReason, "INTEGER_ORDER_RELATION"),
  decision("MOET2018-G6-NAA-P048-023", 6, "PRODUCIBLE_DETERMINISTIC", exactReason, "SIGNED_CONTEXT_INTERPRETATION"),
  decision("MOET2018-G6-NAA-P048-028", 6, "PRODUCIBLE_DETERMINISTIC", exactReason, "APPLIED_NUMBER_THEORY"),
  decision("MOET2018-G6-NAA-P049-031", 6, "PRODUCIBLE_DETERMINISTIC", exactReason, "APPLIED_FRACTION_RATIONAL"),
  decision("MOET2018-G6-NAA-P049-032", 6, "PRODUCIBLE_DETERMINISTIC", exactReason, "APPLIED_INTEGER_AST"),
  decision("MOET2018-G6-NAA-P049-033", 6, "PRODUCIBLE_DETERMINISTIC", exactReason, "FRACTION_PROPERTY_IDENTITY"),
  decision("MOET2018-G6-NAA-P049-034", 6, "PRODUCIBLE_DETERMINISTIC", exactReason, "POSITIVE_MIXED_NUMBER_REPRESENTATION"),
  decision("MOET2018-G6-NAA-P049-035", 6, "PRODUCIBLE_DETERMINISTIC", exactReason, "FRACTION_EQUALITY_CROSS_PRODUCT"),
  decision("MOET2018-G6-NAA-P049-036", 6, "PRODUCIBLE_DETERMINISTIC", exactReason, "SIGNED_FRACTION_NORMALIZATION"),
  decision("MOET2018-G6-NAA-P049-037", 6, "PRODUCIBLE_DETERMINISTIC", exactReason, "INTEGER_DIVISIBILITY_RELATION"),
  decision("MOET2018-G6-NAA-P049-038", 6, "PRODUCIBLE_DETERMINISTIC", exactReason, "FRACTION_OPPOSITE"),
  decision("MOET2018-G6-NAA-P049-039", 6, "PRODUCIBLE_DETERMINISTIC", exactReason, "FRACTION_ORDER_CROSS_PRODUCT"),
  decision("MOET2018-G6-NAA-P049-043", 6, "PRODUCIBLE_DETERMINISTIC", exactReason, "FRACTION_PROPERTY_REWRITE"),
  decision("MOET2018-G6-NAA-P050-045", 6, "PRODUCIBLE_DETERMINISTIC", exactReason, "SIGNED_DECIMAL_OPPOSITE"),
  decision("MOET2018-G6-NAA-P050-046", 6, "PRODUCIBLE_DETERMINISTIC", exactReason, "SIGNED_DECIMAL_ORDER"),
  decision("MOET2018-G6-NAA-P050-048", 6, "PRODUCIBLE_DETERMINISTIC", exactReason, "SCALED_DECIMAL_ESTIMATE_ROUND"),
  decision("MOET2018-G6-NAA-P050-049", 6, "PRODUCIBLE_DETERMINISTIC", exactReason, "PERCENT_VALUE_AND_INVERSE"),
  decision("MOET2018-G6-NAA-P050-050", 6, "PRODUCIBLE_DETERMINISTIC", exactReason, "RATIO_PERCENT_EXACT"),
  decision("MOET2018-G6-NAA-P050-051", 6, "PRODUCIBLE_DETERMINISTIC", exactReason, "DECIMAL_PROPERTY_REWRITE"),
  decision("MOET2018-G6-STA-P053-001", 6, "VISUAL_EVIDENCE_REQUIRED", visualReason, null),
  decision("MOET2018-G6-STA-P053-002", 6, "VISUAL_EVIDENCE_REQUIRED", visualReason, null),
  decision("MOET2018-G6-STA-P053-003", 6, "PRODUCIBLE_DETERMINISTIC", exactReason, "FINITE_SAMPLE_SPACE_MODEL"),
  decision("MOET2018-G6-STA-P053-004", 6, "VISUAL_EVIDENCE_REQUIRED", visualReason, null),
  decision(
    "MOET2018-G6-STA-P053-005",
    6,
    "AUTOMATED_VERIFICATION_INSUFFICIENT",
    "The cross-subject and real-world relationship outcome has no retained factual dataset or exact contextual mapping from which a unique answer can be derived.",
    null,
  ),
  decision("MOET2018-G6-STA-P053-006", 6, "PRODUCIBLE_DETERMINISTIC", exactReason, "DATA_REASONABLENESS_CONSTRAINT"),
  decision("MOET2018-G6-STA-P053-007", 6, "VISUAL_EVIDENCE_REQUIRED", visualReason, null),
  decision("MOET2018-G6-STA-P053-008", 6, "OPEN_ENDED_OR_EXPERIENTIAL", openReason, null),
  decision("MOET2018-G6-STA-P054-009", 6, "PRODUCIBLE_DETERMINISTIC", exactReason, "EMPIRICAL_PROBABILITY_FRACTION"),
  decision("MOET2018-G6-EXP-P054-001", 6, "OPEN_ENDED_OR_EXPERIENTIAL", openReason, null),
  decision("MOET2018-G6-EXP-P054-002", 6, "OPEN_ENDED_OR_EXPERIENTIAL", openReason, null),
  decision("MOET2018-G6-EXP-P054-003", 6, "OPEN_ENDED_OR_EXPERIENTIAL", openReason, null),
  decision("MOET2018-G6-EXP-P055-001", 6, "OPEN_ENDED_OR_EXPERIENTIAL", openReason, null),
  decision("MOET2018-G6-EXP-P055-002", 6, "OPEN_ENDED_OR_EXPERIENTIAL", openReason, null),
  decision("MOET2018-G6-EXP-P055-003", 6, "OPEN_ENDED_OR_EXPERIENTIAL", openReason, null),
] as const;
