import type { CurriculumUnit, PreviewAudit, VisualRequirement } from "./types.ts";
import {
  buildCompletionArtifacts,
  generateCompletionQuestionSpecs,
  numberDistractors,
  type CompletionOutcomeSpec,
  type CompletionQuestionCore,
  type CompletionRandom,
  type CompletionUnitGroup,
} from "./completion-framework.ts";

const E = (
  id: string,
  title: string,
  concept: string,
  why: string,
  method: string,
  error: string,
  prompt: string,
  steps: readonly [string, string, string],
  answer: string,
): CompletionOutcomeSpec => ({ id, title, concept, why, method, error, example: { prompt, steps, answer } });

const specs = [
  E("MOET2018-G6-NAA-P047-001","Chữ số La Mã đến 30","I, V, X biểu diễn 1, 5, 10; quy tắc cộng/trừ theo vị trí tạo các số I–XXX.","Quy tắc vị trí phân biệt IV với VI và IX với XI.","Tách chục–đơn vị, viết X cho chục rồi mã hóa đơn vị.","Không lặp I bốn lần hoặc dùng kí hiệu ngoài phạm vi.","Viết 29 bằng La Mã.",["20 là XX.","9 là IX.","Ghép được XXIX."],"XXIX."),
  E("MOET2018-G6-NAA-P047-002","Hệ thập phân","Mỗi chữ số có giá trị bằng chữ số nhân lũy thừa 10 theo vị trí.","Mười đơn vị một hàng đổi thành một đơn vị hàng bên trái.","Viết số thành tổng các giá trị hàng hoặc ghép các hệ số 0–9.","Không nhầm chữ số với giá trị của nó.","Phân tích 305 072.",["3×100 000.","5×1 000 và 7×10.","Cộng thêm 2."],"300 000 + 5 000 + 70 + 2."),
  E("MOET2018-G6-NAA-P047-003","Dấu hiệu chia hết","Chữ số cuối kiểm tra chia hết 2,5; tổng chữ số kiểm tra chia hết 3,9.","Các số 10 và 9 tạo phần dư phụ thuộc đúng các dấu hiệu này.","Tính chữ số cuối hoặc tổng chữ số rồi kết luận từng ước.","Không dùng dấu hiệu 3 để kết luận chia hết 9.","4 536 chia hết cho những số nào trong 2,3,5,9?",["Chữ số cuối 6 nên chia hết 2.","Tổng chữ số 18 chia hết 3 và 9.","Không tận cùng 0 hoặc 5."],"2, 3 và 9."),
  E("MOET2018-G6-NAA-P047-005","Thứ tự số tự nhiên","Hai số tự nhiên được so bằng số chữ số rồi từng chữ số từ trái sang phải.","Hàng cao nhất khác nhau quyết định thứ tự.","So, dùng < > = và biểu diễn đúng vị trí trên tia số.","Không so bằng tổng chữ số.","So 120 305 và 120 350.",["Cùng sáu chữ số.","Khác ở hàng chục: 0<5.","120 305<120 350."],"120 305 < 120 350."),
  E("MOET2018-G6-NAA-P047-006","Quan hệ ước và bội","a là ước của b khi tồn tại số tự nhiên k sao cho b=a×k; b là bội của a.","Quan hệ chia hết liên kết phép nhân với phép chia không dư.","Thực hiện chia, kiểm tra dư 0 và nêu cả hai chiều quan hệ.","Không gọi 0 là ước; số chia phải khác 0.","6 có là ước của 42 không?",["42:6=7.","Dư 0.","6 là ước, 42 là bội của 6."],"Có."),
  E("MOET2018-G6-NAA-P047-007","Tập hợp số tự nhiên","N={0,1,2,...}; N* thường chỉ các số tự nhiên khác 0.","Dấu ba chấm thể hiện dãy tiếp tục không có số lớn nhất.","Kiểm tra phần tử là số nguyên không âm và dùng kí hiệu thuộc.","Không đưa số âm hay phân số không nguyên vào N.","−1, 0, 3/2, 5: số nào thuộc N?",["−1 âm.","3/2 không nguyên.","0 và 5 thuộc N."],"0 và 5."),
  E("MOET2018-G6-NAA-P047-010","Tập hợp và phần tử","Có thể cho tập hợp bằng liệt kê hoặc chỉ ra tính chất đặc trưng; ∈ và ∉ mô tả quan hệ phần tử.","Hai cách cho phải xác định cùng đúng các phần tử.","Chọn miền, liệt kê không lặp hoặc viết điều kiện rõ.","Không dùng ∈ giữa hai tập hợp hoặc liệt kê trùng.","A={x∈N | x<4}. Liệt kê A.",["Số tự nhiên nhỏ hơn 4.","Gồm 0,1,2,3.","Không lặp phần tử."],"A={0,1,2,3}."),
  E("MOET2018-G6-NAA-P047-011","Phép tính trong N","Cộng, nhân luôn cho số tự nhiên; trừ cần số bị trừ không nhỏ hơn số trừ; chia cần chia hết nếu kết quả trong N.","Điều kiện đóng xác định kết quả có còn trong tập hợp.","Thực hiện đúng thứ tự và kiểm tra số chia, phần dư.","Không chia cho 0 hoặc mặc định mọi phép trừ thuộc N.","Tính 360:12+25.",["360:12=30.","30+25=55.","Kết quả thuộc N."],"55."),
  E("MOET2018-G6-NAA-P047-014","Tính chia hết trong N","Nếu a,b cùng chia hết cho m thì tổng và hiệu thích hợp cũng chia hết cho m.","Viết a=mk, b=ml cho thấy a±b=m(k±l).","Phân tích các số theo m rồi áp dụng tính chất.","Không kết luận tích chia hết cho m nếu không có thừa số phù hợp.","84 và 36 chia hết 6; 84+36 có chia hết 6?",["84=6×14; 36=6×6.","Tổng=6×20.","Tổng chia hết 6."],"Có."),
  E("MOET2018-G6-NAA-P047-015","Lũy thừa và tính nhanh","a^n là tích n thừa số a; lũy thừa được tính trước nhân chia và cộng trừ.","Kí hiệu lũy thừa rút gọn phép nhân lặp.","Xác định cơ số/số mũ, tính lũy thừa rồi theo thứ tự.","Không hiểu 2^3 là 2×3; lưu ý −2^2 khác (−2)^2.","Tính 3+2^3×4.",["2^3=8.","8×4=32.","3+32=35."],"35."),
  E("MOET2018-G6-NAA-P047-016","Giao hoán, kết hợp, phân phối","a(b+c)=ab+ac; giao hoán/kết hợp áp dụng cho cộng và nhân.","Mô hình diện tích cho thấy tổng hai phần bằng toàn hình.","Nhóm số tròn hoặc đặt thừa số chung.","Không phân phối cho chỉ một số hạng.","Tính 25×17+25×3.",["Đặt 25 chung.","25×(17+3).","25×20=500."],"500."),
  E("MOET2018-G6-NAA-P048-017","Số nguyên trên trục số","Số nguyên âm nằm trái 0, số dương nằm phải; khoảng cách đơn vị bằng nhau.","Vị trí cho thấy thứ tự và số đối trực quan.","Chọn gốc 0, chiều dương, đếm đơn vị có dấu.","Không đặt −3 bên phải 0.","Điểm cách 0 ba đơn vị về trái biểu diễn số nào?",["Bên trái mang dấu âm.","Khoảng cách là 3.","Điểm biểu diễn −3."],"−3."),
  E("MOET2018-G6-NAA-P048-018","Số nguyên tố và hợp số","Số nguyên tố lớn hơn 1 có đúng hai ước dương; hợp số lớn hơn 1 có nhiều hơn hai ước.","Số 1 chỉ có một ước nên không thuộc hai loại.","Liệt kê ước hoặc thử ước đến căn bậc hai ở trường hợp nhỏ.","Không coi 1 là số nguyên tố.","29 là nguyên tố hay hợp số?",["29>1.","Không chia hết 2,3,5.","Chỉ có 1 và 29."],"Số nguyên tố."),
  E("MOET2018-G6-NAA-P048-019","Phép chia có dư","a=bq+r với b≠0 và 0≤r<b.","r là phần còn lại chưa đủ tạo thêm một nhóm b.","Tìm bội lớn nhất không vượt a, tính r và kiểm tra bất đẳng thức.","Không để r≥b hoặc b=0.","Chia 53 cho 7.",["7×7=49.","53−49=4.","53=7×7+4, 4<7."],"7 dư 4."),
  E("MOET2018-G6-NAA-P048-020","Số đối của số nguyên","Số đối của a là −a; tổng hai số đối bằng 0 và chúng đối xứng qua 0.","Hai vị trí có cùng khoảng cách tới 0 ở hai phía.","Đổi dấu và kiểm tra tổng bằng 0.","Số đối của 0 vẫn là 0.","Số đối của −8 là gì?",["Đổi dấu −8.","Được 8.","−8+8=0."],"8."),
  E("MOET2018-G6-NAA-P048-021","Số nguyên âm và Z","Z gồm số nguyên âm, 0 và số nguyên dương.","Số âm mô tả đại lượng dưới mốc như nhiệt độ, độ cao, nợ.","Xác định mốc, dấu và kiểm tra phần tử thuộc Z.","Không coi mọi số có dấu trừ là nhỏ hơn nếu đang nói khoảng cách.","Nhiệt độ 4 độ dưới 0 viết thế nào?",["Mốc là 0°C.","Dưới mốc dùng dấu âm.","Viết −4°C."],"−4°C."),
  E("MOET2018-G6-NAA-P048-024","So sánh số nguyên","Trên trục số, số nằm bên phải lớn hơn; trong hai số âm, số có giá trị tuyệt đối nhỏ hơn lại lớn hơn.","Thứ tự vị trí tránh quy tắc dấu máy móc.","Đặt/nhẩm vị trí trên trục rồi dùng < > =.","Không so riêng giá trị tuyệt đối mà bỏ dấu.","So −3 và −8.",["−3 gần 0 hơn.","−3 nằm bên phải −8.","−3>−8."],"−3 > −8."),
  E("MOET2018-G6-NAA-P048-027","Phân tích thừa số nguyên tố","Mọi số tự nhiên lớn hơn 1 viết được thành tích các thừa số nguyên tố.","Chia liên tiếp cho số nguyên tố làm giảm số đến 1.","Dùng cây thừa số hoặc phép chia, sắp thừa số và kiểm tra tích.","Không dừng ở một thừa số hợp số.","Phân tích 84.",["84=2×42=2×2×21.","21=3×7.","84=2^2×3×7."],"2²×3×7."),
  E("MOET2018-G6-NAA-P048-028","Số học trong thực tiễn","Ước, bội và bốn phép tính mô hình hóa đóng gói, lịch lặp và mua sắm.","Điều kiện nguyên và phần dư quyết định phương án có thể thực hiện.","Xác định đại lượng, chọn quan hệ, tính và kiểm tra tính nguyên/hợp lí.","Không bỏ phần dư hoặc đơn vị hàng hóa.","Xếp 48 chai thành các hộp 6 chai. Cần bao nhiêu hộp?",["48:6=8.","Phép chia hết.","Cần 8 hộp."],"8 hộp."),
  E("MOET2018-G6-NAA-P048-029","Quy tắc dấu ngoặc với số nguyên","Bỏ ngoặc có dấu + giữ dấu; có dấu − đổi dấu mọi số hạng trong ngoặc.","Phân phối −1 cho toàn bộ ngoặc giữ biểu thức tương đương.","Xử lí ngoặc trước, đổi đủ dấu rồi cộng trừ số nguyên.","Không đổi chỉ số hạng đầu.","Tính 7−(−3+5).",["Trong ngoặc −3+5=2.","7−2=5.","Hoặc bỏ ngoặc: 7+3−5."],"5."),
  E("MOET2018-G6-NAA-P048-030","ƯCLN, BCNN và phân số","ƯCLN dùng rút gọn; BCNN dùng quy đồng và cộng trừ phân số.","Phân tích nguyên tố cho số mũ nhỏ nhất/lớn nhất tương ứng.","Phân tích, chọn thừa số, tính rồi áp dụng.","Không dùng ƯCLN làm mẫu chung.","Tìm BCNN(12,18).",["12=2²×3; 18=2×3².","Lấy số mũ lớn nhất.","BCNN=2²×3²=36."],"36."),
  E("MOET2018-G6-NAA-P049-031","Bài toán thực tiễn phân số","Phân số mô tả phần, tốc độ hoặc thời gian; phép tính phải theo quan hệ đại lượng.","Mô hình và đơn vị giúp kiểm tra kết quả.","Tóm tắt, quy đồng/nhân chia và kiểm tra miền giá trị.","Không cộng số đo khác đơn vị.","Đi 2/3 km rồi 3/4 km. Tổng?",["Mẫu chung 12.","8/12+9/12=17/12.","Bằng 1 5/12 km."],"1 5/12 km."),
  E("MOET2018-G6-NAA-P049-032","Bài toán thực tiễn số nguyên","Số nguyên có dấu mô tả thu–chi, lãi–lỗ và biến đổi quanh mốc.","Dấu gắn với hướng thay đổi chứ không chỉ chữ số.","Chọn quy ước dấu, lập tổng đại số và diễn giải kết quả.","Không bỏ dấu âm của khoản lỗ.","Lãi 50 nghìn rồi lỗ 80 nghìn. Kết quả?",["Quy ước lãi +, lỗ −.","50+(−80)=−30.","Kết quả lỗ 30 nghìn."],"Lỗ 30 nghìn."),
  E("MOET2018-G6-NAA-P049-033","Hai tính chất cơ bản phân số","Nhân hoặc chia cả tử và mẫu cho cùng số nguyên khác 0 cho phân số bằng nó.","Tỉ số tử/mẫu không đổi khi cả hai cùng scale.","Áp dụng cùng một thừa số và kiểm tra mẫu khác 0.","Không chỉ biến đổi tử hoặc dùng thừa số 0.","Vì sao 3/5=12/20?",["Nhân cả tử và mẫu 4.","3×4=12; 5×4=20.","Giá trị không đổi."],"Nhân cả tử và mẫu với 4."),
  E("MOET2018-G6-NAA-P049-034","Hỗn số dương","Hỗn số a b/c gồm phần nguyên a và phân số dương nhỏ hơn 1.","Nó biểu diễn a toàn thể cộng b/c toàn thể.","Đổi sang phân số bằng (a×c+b)/c và đổi ngược bằng chia.","Không để b≥c trong dạng chuẩn.","Đổi 2 3/5 sang phân số.",["2×5+3=13.","Giữ mẫu 5.","Được 13/5."],"13/5."),
  E("MOET2018-G6-NAA-P049-036","Phân số có dấu âm","Dấu âm ở tử, mẫu hoặc trước phân số là tương đương; mẫu thường chuẩn hóa dương.","Nhân tử và mẫu với −1 giữ giá trị.","Đếm dấu âm, chuẩn hóa mẫu dương và rút gọn.","Mẫu không được 0; hai dấu âm cho phân số dương.","Chuẩn hóa 3/(−5).",["Có một dấu âm.","Chuyển dấu ra trước.","Được −3/5."],"−3/5."),
  E("MOET2018-G6-NAA-P049-037","Ước và bội trong Z","Với số nguyên a≠0, b chia hết cho a nếu b=ak với k nguyên; dấu không làm mất quan hệ.","Thừa số nguyên có thể âm hoặc dương.","Tìm thương nguyên và kiểm tra tích.","Không dùng 0 làm số chia.","−6 có là ước của 42?",["42:(−6)=−7.","−7 là số nguyên.","42=(−6)×(−7)."],"Có."),
  E("MOET2018-G6-NAA-P049-038","Số đối của phân số","Số đối của a/b là −a/b và tổng bằng 0, với b≠0.","Hai số đối nằm đối xứng qua 0 trên trục số.","Đổi đúng một dấu, giữ mẫu khác 0 và kiểm tra tổng.","Không đảo tử mẫu; đó là nghịch đảo, không phải số đối.","Số đối của −3/7?",["Đổi dấu.","Được 3/7.","−3/7+3/7=0."],"3/7."),
  E("MOET2018-G6-NAA-P049-042","Phân số của một số và bài toán ngược","a/b của N là N×a/b; biết phần M thì toàn thể M×b/a với a≠0.","Nhân và chia ngược phục hồi toàn thể.","Xác định chiều bài toán, tính và kiểm tra phần/toàn thể.","Không đảo sai tỉ lệ hoặc chia cho tử 0.","3/5 của một số là 24. Tìm số.",["Một phần là 24:3=8.","Năm phần là 8×5=40.","3/5 của 40 là 24."],"40."),
  E("MOET2018-G6-NAA-P049-043","Tính chất phép tính phân số","Giao hoán, kết hợp, phân phối và quy tắc ngoặc dùng được khi các mẫu khác 0.","Các phân số là số nên các đẳng thức đại số cơ bản vẫn đúng.","Nhóm phần bù thành 1 hoặc đặt thừa số chung rồi rút gọn.","Không giao hoán phép chia hay bỏ điều kiện mẫu.","Tính 2/7×3/5+2/7×2/5.",["Đặt 2/7 chung.","2/7×(3/5+2/5).","Bằng 2/7."],"2/7."),
  E("MOET2018-G6-NAA-P050-044","Thập phân, tỉ số và phần trăm thực tiễn","Số thập phân và phần trăm mô tả giá, nồng độ, lãi suất và tỉ lệ.","Đổi về cùng biểu diễn giúp lập phép tính đúng.","Xác định toàn thể, tỉ lệ, tính và kiểm tra 0–100% khi là thành phần.","Không tính phần trăm trên sai toàn thể.","Dung dịch 200 g chứa 5% muối. Khối lượng muối?",["5%=5/100.","200×5/100=10.","10 g không vượt 200 g."],"10 g."),
  E("MOET2018-G6-GEO-P050-001","Yếu tố của hình đều","Tam giác đều, hình vuông, lục giác đều có các cạnh và góc tương ứng bằng nhau; đường chéo có tính chất riêng.","Tính đều được bảo toàn qua quay và phản xạ phù hợp.","Đếm cạnh/góc, kiểm tra bằng nhau và nhận dạng.","Không gọi hình đều chỉ vì trông cân đối.","Lục giác đều có bao nhiêu cạnh bằng nhau?",["Lục giác có 6 cạnh.","Đều nghĩa là các cạnh bằng nhau.","Có 6 cạnh bằng nhau."],"6."),
  E("MOET2018-G6-NAA-P050-045","Số thập phân âm và số đối","Số thập phân âm nhỏ hơn 0; số đối đổi dấu và có cùng khoảng cách tới 0.","Vị trí đối xứng qua 0 xác định số đối.","Chuẩn hóa dấu, đặt trên trục số và kiểm tra tổng 0.","Số đối của 0 vẫn 0; không bỏ phần thập phân.","Số đối của −2,75?",["Đổi dấu âm.","Giữ độ lớn 2,75.","Tổng hai số bằng 0."],"2,75."),
  E("MOET2018-G6-NAA-P050-046","So sánh số thập phân có dấu","So dấu trước; cùng dấu dương so giá trị hàng, cùng âm thì thứ tự độ lớn đảo lại.","Trục số đặt số âm bên trái 0 và số lớn hơn ở bên phải.","Căn phần nguyên/phần thập phân, thêm 0 tận cùng nếu cần rồi xét dấu.","Không so độ dài chuỗi hoặc chỉ giá trị tuyệt đối.","So −1,2 và −1,15.",["Viết −1,20 và −1,15.","1,20>1,15.","Số âm có độ lớn lớn hơn thì nhỏ hơn."],"−1,2 < −1,15."),
  E("MOET2018-G6-NAA-P050-047","Bốn phép tính thập phân","Cộng trừ căn hàng; nhân đếm hàng thập phân; chia dịch dấu phẩy ở cả hai số để số chia tự nhiên.","Các quy tắc bảo toàn giá trị vị trí và thương.","Chọn quy tắc theo phép tính, kiểm tra số chia khác 0 và ước lượng.","Không chia cho 0 hoặc dịch một phía.","Tính 3,6:(−0,12).",["Hai số khác dấu nên thương âm.","Nhân cả hai với 100: 360:(−12).","Kết quả −30."],"−30."),
  E("MOET2018-G6-NAA-P050-048","Ước lượng và làm tròn thập phân","Làm tròn xét chữ số ngay bên phải; ước lượng dùng số gần để kiểm tra phép tính.","Mốc 5 và giá trị hàng cho kết quả gần nhất nhất quán.","Chọn hàng, làm tròn từng số và so kết quả chính xác với ước lượng.","Không làm tròn sớm quá nhiều trong chuỗi tính.","Làm tròn −3,46 đến một chữ số thập phân.",["Xét hàng phần trăm 6.","Tăng độ lớn hàng phần mười từ 4 lên 5.","Kết quả −3,5."],"−3,5."),
  E("MOET2018-G6-NAA-P050-049","Giá trị phần trăm và bài toán ngược","p% của N là Np/100; biết M=p% của N thì N=100M/p với p≠0.","Hai phép tính là quan hệ thuận nghịch theo cùng toàn thể.","Xác định phần, toàn thể, tỉ lệ rồi nhân hoặc chia đúng chiều.","Không chia cho p=0 trong bài toán ngược.","20% của số nào bằng 30?",["1% là 30:20=1,5.","100% là 150.","Kiểm tra 20%×150=30."],"150."),
  E("MOET2018-G6-NAA-P050-050","Tỉ số và tỉ số phần trăm","Tỉ số a:b=a/b với b≠0; tỉ số phần trăm là tỉ số nhân 100%.","Chuẩn hóa cùng đơn vị trước khi so hai đại lượng.","Đổi cùng đơn vị, chia đại lượng thứ nhất cho thứ hai rồi nhân 100%.","Không tính khi đại lượng thứ hai bằng 0.","15 trong 60 là bao nhiêu phần trăm?",["15/60=1/4.","1/4=0,25.","Nhân 100%=25%."],"25%."),
  E("MOET2018-G6-NAA-P050-051","Tính chất với số thập phân","Giao hoán, kết hợp, phân phối và ngoặc áp dụng cho thập phân trong miền xác định.","Đổi cách nhóm hợp lệ không đổi giá trị số.","Nhóm tạo số nguyên hoặc đặt thừa số chung và kiểm tra dấu.","Không giao hoán phép chia hoặc bỏ dấu âm.","Tính 1,25×8×0,4.",["1,25×8=10.","10×0,4=4.","Ước lượng xác nhận."],"4."),
  E("MOET2018-G6-GEO-P051-005","Hình có tâm đối xứng trong tự nhiên","Hình có tâm đối xứng trùng với chính nó sau phép quay 180° quanh một điểm.","Phép quay nửa vòng ghép mỗi điểm với điểm đối diện qua tâm.","Tìm điểm giữa, tưởng tượng quay 180° và so đường bao.","Không nhầm tâm đối xứng với mọi tâm hình tròn ngoại tiếp.","Bông hoa bốn cánh đều có tâm đối xứng không?",["Chọn tâm hoa.","Quay hình 180°.","Các cánh trùng vị trí."],"Có."),
  E("MOET2018-G6-GEO-P051-006","Hình có trục đối xứng trong tự nhiên","Trục đối xứng chia hình thành hai nửa chồng khít khi gấp.","Phản xạ qua trục bảo toàn khoảng cách vuông góc.","Dự đoán trục, gấp/so các điểm tương ứng.","Không kết luận từ màu sắc nếu đường bao không đối xứng.","Chiếc lá cân qua gân giữa có trục nào?",["Gân giữa chia hai nửa.","Gấp theo gân thì hai nửa trùng.","Gân giữa là trục."],"Gân giữa."),
  E("MOET2018-G6-GEO-P051-007","Tâm đối xứng của hình phẳng","Tâm đối xứng là điểm cố định của phép quay 180° đưa hình về chính nó.","Nó là trung điểm của các cặp điểm tương ứng.","Nối cặp điểm đối diện và tìm trung điểm chung.","Không chọn một điểm chỉ vì nằm trong hình.","Tâm đối xứng hình bình hành ở đâu?",["Nối hai đường chéo.","Chúng cắt nhau tại trung điểm mỗi đường.","Giao điểm là tâm."],"Giao điểm hai đường chéo."),
  E("MOET2018-G6-GEO-P051-008","Đối xứng trong ứng dụng","Đối xứng xuất hiện trong họa tiết, kiến trúc và chi tiết chế tạo để tạo cân bằng hoặc lắp ghép.","Tính lặp qua phép biến hình giúp kiểm tra thiết kế.","Xác định phép phản xạ/quay, trục/tâm và kiểm tra các phần tương ứng.","Không gọi mọi mẫu lặp là đối xứng.","Logo trùng sau quay 180° có loại đối xứng nào?",["Phép biến đổi là quay nửa vòng.","Có một điểm quay cố định.","Đó là đối xứng tâm."],"Đối xứng tâm."),
  E("MOET2018-G6-GEO-P051-009","Trục đối xứng của hình phẳng","Trục đối xứng là đường mà phép phản xạ qua đó giữ nguyên hình.","Mỗi điểm và ảnh cách trục bằng nhau theo phương vuông góc.","Gấp hoặc dựng đường trung trực các cặp điểm tương ứng.","Không đếm đường chéo bất kỳ là trục.","Hình vuông có bao nhiêu trục đối xứng?",["Hai đường qua trung điểm cạnh đối.","Hai đường chéo.","Tổng 4 trục."],"4."),
  E("MOET2018-G6-GEO-P051-010","Vẻ đẹp đối xứng tự nhiên","Đối xứng tạo nhịp điệu và cân bằng có thể mô tả bằng trục hoặc tâm cụ thể.","Mô tả toán học giải thích cấu trúc thay vì chỉ đánh giá cảm tính.","Chỉ ra đối tượng, trục/tâm và cặp phần tương ứng.","Không khẳng định đối xứng hoàn hảo nếu chỉ gần giống.","Bướm nhìn từ trên thường thể hiện đối xứng gì?",["Thân bướm là đường giữa.","Hai cánh trái–phải tương ứng.","Có đối xứng trục gần đúng."],"Đối xứng trục qua thân."),
  E("MOET2018-G6-GEO-P051-011","Ghép lục giác đều","Sáu tam giác đều bằng nhau ghép chung một đỉnh tạo lục giác đều.","Mỗi góc tại tâm 60° và sáu góc đủ 360°.","Xếp sáu tam giác quanh tâm, cạnh kề trùng nhau và kiểm tra đường bao.","Không để hở, chồng hoặc dùng tam giác không bằng nhau.","Cần bao nhiêu tam giác đều để ghép lục giác đều?",["Mỗi góc ở tâm 60°.","360°:60°=6.","Cần 6 tam giác."],"6."),
  E("MOET2018-G6-GEO-P052-012","Đoạn thẳng, trung điểm và độ dài","Đoạn AB gồm A, B và các điểm giữa; trung điểm M thỏa M nằm giữa và AM=MB.","Hai điều kiện vị trí và độ dài cùng cần thiết.","Đo AB, chia đôi, kiểm tra thẳng hàng và hai đoạn bằng nhau.","Không gọi điểm ở giữa là trung điểm nếu độ dài khác.","AB=10 cm, M là trung điểm. AM?",["M nằm giữa A,B.","AM=MB.","AM=10:2=5 cm."],"5 cm."),
  E("MOET2018-G6-GEO-P052-014","Ba điểm thẳng hàng","Ba điểm thẳng hàng khi cùng nằm trên một đường thẳng; nếu không thì xác định một tam giác.","Qua hai điểm phân biệt có duy nhất một đường thẳng.","Kẻ đường qua hai điểm và kiểm tra điểm thứ ba có thuộc.","Không suy từ hình vẽ gần thẳng.","A,B,C cùng thuộc đường d. Quan hệ?",["A thuộc d.","B và C cũng thuộc d.","Ba điểm thẳng hàng."],"Thẳng hàng."),
  E("MOET2018-G6-GEO-P052-015","Điểm nằm giữa hai điểm","B nằm giữa A,C khi ba điểm thẳng hàng và B thuộc phần đoạn AC; khi đó AB+BC=AC.","Quan hệ độ dài xác nhận thứ tự vị trí.","Kiểm tra thẳng hàng rồi kiểm tra tổng hai đoạn.","Không dùng chỉ AB+BC nếu các điểm không thẳng hàng.","AB=3, BC=5, AC=8 và thẳng hàng. B ở đâu?",["3+5=8.","B cùng đường với A,C.","B nằm giữa A và C."],"B nằm giữa A và C."),
  E("MOET2018-G6-GEO-P052-016","Góc và điểm trong góc","Góc gồm hai tia chung gốc; điểm trong nằm giữa hai tia trong miền góc không lõm.","Hai tia chia mặt phẳng và xác định miền trong.","Xác định đỉnh, hai cạnh và kiểm tra tia qua điểm nằm giữa.","Không nhầm độ dài tia với độ lớn góc.","Trong góc xOy, điểm M nằm giữa hai tia. M ở đâu?",["Ox,Oy là hai cạnh.","Tia OM nằm giữa chúng.","M là điểm trong góc."],"Trong góc xOy."),
  E("MOET2018-G6-GEO-P052-017","Hai đường cắt nhau và song song","Hai đường cắt nhau có một điểm chung; song song cùng mặt phẳng không có điểm chung.","Số điểm chung phân biệt hai quan hệ.","Kéo dài về hai phía hoặc dùng tính chất/hình dựng để kiểm tra.","Không kết luận song song từ đoạn vẽ chưa giao.","Hai đường có đúng một điểm chung gọi là gì?",["Điểm đó thuộc cả hai đường.","Chúng gặp nhau.","Hai đường cắt nhau."],"Cắt nhau."),
  E("MOET2018-G6-GEO-P052-019","Tia","Tia Ox gồm gốc O và các điểm về một phía trên đường thẳng; hai tia đối nhau chung gốc tạo đường thẳng.","Gốc giới hạn một phía nhưng tia kéo dài vô hạn phía kia.","Xác định gốc trước rồi điểm chỉ hướng.","Không đổi thứ tự tên tia tùy ý.","Tia AB có gốc nào?",["Tên tia viết gốc trước.","A đứng trước B.","Gốc là A."],"A."),
  E("MOET2018-G6-GEO-P052-020","Điểm và đường thẳng","Dùng ∈/∉ mô tả điểm thuộc đường; qua hai điểm phân biệt có duy nhất một đường thẳng.","Hai điểm xác định hướng và vị trí của đường.","Kiểm tra quan hệ thuộc và áp dụng tiên đề đúng điều kiện phân biệt.","Không nói có nhiều đường qua cùng hai điểm phân biệt.","Qua A≠B có bao nhiêu đường thẳng?",["A,B phân biệt.","Áp dụng tiên đề.","Có duy nhất một đường."],"1."),
  E("MOET2018-G6-GEO-P052-021","Phần mềm hỗ trợ hình học","Phần mềm hình học động tạo, đo và kéo thả hình trong khi giữ quan hệ đã dựng.","Biến đổi động giúp kiểm tra tính chất có bền vững hay chỉ do hình mẫu.","Dựng bằng công cụ quan hệ, kéo thử và ghi nhận bất biến.","Không coi hình nhìn đúng là đã dựng đúng ràng buộc.","Muốn kiểm tra trung điểm động, cần giữ gì?",["M thuộc AB.","AM=MB.","Kéo A hoặc B và kiểm tra hai điều kiện."],"M thuộc AB và AM=MB."),
  E("MOET2018-G6-GEO-P052-022","Vẽ và thiết kế bằng phần mềm","Thiết kế số dùng các công cụ đoạn, đa giác, vuông góc, song song và đối xứng theo đúng ràng buộc.","Quan hệ hình học giúp bản vẽ vẫn đúng khi chỉnh kích thước.","Dựng yếu tố nền, áp ràng buộc, đo và lưu phiên bản.","Không vẽ tự do thay cho công cụ quan hệ.","Dựng hình vuông từ một cạnh AB cần gì?",["Dựng vuông góc tại A,B.","Lấy hai đoạn bằng AB.","Nối hai đầu còn lại song song AB."],"Hai đường vuông góc và các cạnh bằng nhau."),
  E("MOET2018-G6-STA-P053-002","Giải bài toán từ bảng và biểu đồ","Bảng, tranh, cột và cột kép mã hóa giá trị theo nhãn, chú giải và thang đo.","Đọc đúng thang chuyển hình biểu diễn thành dữ liệu số.","Xác định nhóm, đơn vị mỗi vạch, đọc số rồi tính tổng/hiệu/tỉ lệ.","Không đếm ô/vạch như 1 khi thang khác 1.","Cột A=24, B=18. A hơn B?",["Cùng thang đo.","24−18=6.","A hơn 6."],"6."),
  E("MOET2018-G6-STA-P053-003","Mô hình xác suất đơn giản","Mô hình xác suất liệt kê các kết quả có thể của trò chơi hoặc thí nghiệm và sự kiện là tập con kết quả.","Không gian kết quả đầy đủ ngăn bỏ sót khả năng.","Xác định phép thử, liệt kê kết quả không trùng và mô tả sự kiện.","Không coi kết quả không thể là một khả năng.","Tung đồng xu một lần có kết quả nào?",["Phép thử là tung một đồng xu.","Hai mặt có thể xuất hiện.","Kết quả: sấp, ngửa."],"Sấp hoặc ngửa."),
  E("MOET2018-G6-STA-P053-004","Chọn và biểu diễn dữ liệu","Bảng phù hợp tra cứu; biểu đồ tranh/cột phù hợp so sánh; cột kép so hai dãy cùng nhóm.","Câu hỏi phân tích quyết định kiểu biểu diễn.","Xác định biến, nhóm, số dãy, chọn biểu diễn và đặt thang/chú giải.","Không dùng cột kép khi các nhóm không tương ứng.","So nam–nữ ở từng lớp nên dùng gì?",["Mỗi lớp có hai dãy.","Cần so trong từng nhóm.","Dùng biểu đồ cột kép."],"Biểu đồ cột kép."),
  E("MOET2018-G6-STA-P053-005","Thống kê liên môn và thực tiễn","Dữ liệu khí hậu, dân số, giá cả hoặc thí nghiệm kết nối thống kê với môn học khác.","Ngữ cảnh cung cấp ý nghĩa cho biến và giới hạn kết luận.","Đọc nguồn/đơn vị/thời gian, phân tích và nêu kết luận đúng phạm vi.","Không so dữ liệu khác đơn vị hoặc khác kỳ.","Nhiệt độ 7 ngày thuộc môn nào và dùng gì?",["Dữ liệu thuộc Khoa học tự nhiên/Địa lí.","Ghi theo ngày.","Dùng bảng hoặc biểu đồ cột."],"Bảng hoặc biểu đồ theo ngày."),
  E("MOET2018-G6-STA-P053-006","Tính hợp lí của dữ liệu","Dữ liệu hợp lí phải đúng kiểu, đơn vị, phạm vi và quan hệ tổng theo ngữ cảnh.","Ràng buộc thực tế giúp phát hiện lỗi nhập hoặc đo.","Kiểm tra miền giá trị, tổng, đơn vị và ngoại lệ trước phân tích.","Không xóa ngoại lệ thật chỉ vì khác biệt.","Tuổi học sinh lớp 6 ghi 120. Hợp lí không?",["Đơn vị là năm.","120 vượt xa phạm vi học sinh.","Dữ liệu không hợp lí."],"Không hợp lí."),
  E("MOET2018-G6-STA-P053-008","Thu thập và phân loại dữ liệu","Thu thập từ bảng biểu hoặc môn học khác cần nguồn, tiêu chí và quy tắc phân loại nhất quán.","Quy trình rõ làm dữ liệu có thể kiểm tra lại.","Ghi nguồn, trích từng quan sát, phân loại và kiểm tra tổng.","Không đổi tiêu chí hoặc đếm lặp.","Phân loại 20 ngày thành mưa 6, không mưa 14.",["Cùng tiêu chí thời tiết.","6+14=20.","Hai nhóm không chồng."],"Tổng 20 ngày."),
  E("MOET2018-G6-EXP-P054-001","Tiết kiệm, vay, lãi và dư nợ","Lãi đơn theo kỳ bằng vốn×lãi suất; dư nợ giảm khi trả gốc và tăng theo khoản vay/lãi.","Dòng tiền có dấu và thời điểm quyết định số dư.","Lập bảng vốn–lãi suất–thời gian–thanh toán và kiểm tra đơn vị tiền.","Không cộng phần trăm trực tiếp vào tiền hoặc tính trên sai gốc.","Gửi 1 000 000 đồng lãi 5% một kỳ. Lãi?",["5%=0,05.","1 000 000×0,05=50 000.","Số dư mới 1 050 000."],"50 000 đồng."),
  E("MOET2018-G6-STA-P054-011","Xác suất thực nghiệm","Xác suất thực nghiệm của sự kiện = số lần xảy ra/số lần thử, nằm từ 0 đến 1.","Tần suất tương đối mô tả mức xuất hiện trong dữ liệu thử nghiệm.","Đếm số lần sự kiện và tổng thử, lập phân số, kiểm tra giới hạn.","Không dùng tổng thử bằng 0 hoặc kết luận chắc chắn từ mẫu nhỏ.","Tung xu 40 lần, ngửa 22. Xác suất thực nghiệm?",["Sự kiện xảy ra 22 lần.","Tổng 40 lần.","Tỉ số 22/40=0,55."],"0,55."),
  E("MOET2018-G6-EXP-P054-002","Hóa đơn, tiền thừa và sổ chi tiêu","Hóa đơn ghi từng khoản, tổng; tiền thừa=tiền trả−tổng; sổ thu chi theo dõi số dư.","Phép cộng ngược kiểm tra giao dịch và chứng từ.","Đối chiếu dòng hàng, cộng tổng, tính thừa và cập nhật số dư.","Không bỏ khoản hoặc để tiền trả nhỏ hơn tổng mà vẫn tính thừa.","Hóa đơn 135 000, trả 200 000. Tiền thừa?",["200 000−135 000=65 000.","Kiểm tra 135 000+65 000.","Giữ hóa đơn đối chiếu."],"65 000 đồng."),
  E("MOET2018-G6-EXP-P054-003","Đọc bảng Lịch sử và Địa lí","Bảng liên môn có biến, địa điểm/thời gian và đơn vị cần đọc trước khi so sánh.","Bối cảnh xác định ý nghĩa của số liệu và phép so.","Đọc tiêu đề, hàng/cột, đơn vị rồi tính chênh lệch/tỉ lệ.","Không so số khác năm hoặc khác đơn vị.","Dân số A=2,4 triệu, B=1,8 triệu. Chênh?",["Cùng đơn vị triệu người.","2,4−1,8=0,6.","Kết luận 0,6 triệu."],"0,6 triệu người."),
  E("MOET2018-G6-EXP-P055-001","Diện tích và thể tích thực tiễn","Công thức hình phẳng/khối dùng kích thước cùng đơn vị và kết quả đơn vị vuông/khối.","Số chiều nhân quyết định loại đại lượng và đơn vị.","Mô hình hình, đổi đơn vị, áp công thức và kiểm tra độ lớn.","Không dùng chu vi thay diện tích hoặc diện tích thay thể tích.","Hộp 5×4×3 dm có thể tích?",["Ba kích thước dương cùng dm.","V=5×4×3=60.","Ghi dm³."],"60 dm³."),
  E("MOET2018-G6-EXP-P055-002","Ba điểm thẳng hàng trong thực tiễn","Căng dây hoặc ngắm thẳng tạo một đường chuẩn để đặt nhiều điểm thẳng hàng.","Đường qua hai mốc phân biệt là duy nhất.","Chọn hai mốc, căng dây, đặt điểm thứ ba trên dây và kiểm tra.","Không chỉ ước nhìn khi cần độ thẳng chính xác.","Trồng ba cây thẳng hàng cần làm gì?",["Chọn vị trí cây đầu và cuối.","Căng dây qua hai mốc.","Đặt cây giữa trên dây."],"Căng dây qua hai mốc."),
  E("MOET2018-G6-EXP-P055-003","Đối xứng trong thực hành","Gấp giấy, sưu tầm và thiết kế dùng phép phản xạ hoặc quay 180° để tạo/kiểm tra đối xứng.","Thao tác vật lí cho thấy các phần tương ứng chồng khít.","Chọn trục/tâm, tạo một phần, phản chiếu/quay và kiểm tra.","Không chỉ trang trí giống nhau mà bỏ vị trí tương ứng.","Gấp giấy tạo hình có trục đối xứng thế nào?",["Gấp theo đường dự kiến làm trục.","Cắt xuyên hai lớp.","Mở ra, hai nửa chồng khít."],"Gấp theo trục rồi cắt hai lớp."),
] as const;

const ids = specs.map((spec) => spec.id);
const groups: readonly CompletionUnitGroup[] = [
  { slug:"grade-6-natural-representation-p1",title:"Tập hợp và biểu diễn số tự nhiên",code:"G6-P1-NAA-A",domain:"NUMBERS_AND_OPERATIONS",visual:"PLACE_VALUE_CHART",prerequisiteSlugs:["grade-5-natural-number-fluency-p1"],outcomeIds:[ids[0],ids[1],ids[3],ids[5]] },
  { slug:"grade-6-sets-divisibility-p1",title:"Tập hợp, ước bội và dấu hiệu chia hết",code:"G6-P1-NAA-B",domain:"NUMBERS_AND_OPERATIONS",visual:"DATA_DISPLAY",prerequisiteSlugs:["grade-5-natural-number-fluency-p1"],outcomeIds:[ids[2],ids[4],ids[6],ids[8]] },
  { slug:"grade-6-natural-operations-powers-p1",title:"Phép tính, lũy thừa và tính chất trong N",code:"G6-P1-NAA-C",domain:"ALGEBRA_AND_PREALGEBRA",visual:"BALANCE_MODEL",prerequisiteSlugs:["grade-5-natural-number-fluency-p1"],outcomeIds:[ids[7],ids[9],ids[10],ids[13]] },
  { slug:"grade-6-primes-gcd-lcm-p1",title:"Số nguyên tố, phân tích, ƯCLN và BCNN",code:"G6-P1-NAA-D",domain:"NUMBERS_AND_OPERATIONS",visual:"DATA_DISPLAY",prerequisiteSlugs:["grade-5-fraction-decimal-foundations-p1"],outcomeIds:[ids[12],ids[17],ids[20],ids[18]] },
  { slug:"grade-6-integer-foundations-p1",title:"Số nguyên, số đối và thứ tự",code:"G6-P1-NAA-E",domain:"ALGEBRA_AND_PREALGEBRA",visual:"NUMBER_LINE",prerequisiteSlugs:["grade-5-natural-number-fluency-p1"],outcomeIds:[ids[11],ids[14],ids[15],ids[16]] },
  { slug:"grade-6-integer-calculation-context-p1",title:"Tính toán và ứng dụng số nguyên",code:"G6-P1-NAA-F",domain:"ALGEBRA_AND_PREALGEBRA",visual:"NUMBER_LINE",prerequisiteSlugs:["grade-5-natural-number-fluency-p1"],outcomeIds:[ids[19],ids[22],ids[26]] },
  { slug:"grade-6-signed-fraction-representation-p1",title:"Biểu diễn phân số có dấu và hỗn số",code:"G6-P1-NAA-G",domain:"NUMBERS_AND_OPERATIONS",visual:"FRACTION_BAR",prerequisiteSlugs:["grade-5-fraction-decimal-foundations-p1"],outcomeIds:[ids[23],ids[24],ids[25],ids[27]] },
  { slug:"grade-6-fraction-reasoning-application-p1",title:"Tính toán và ứng dụng phân số",code:"G6-P1-NAA-H",domain:"APPLIED_PROBLEM_SOLVING",visual:"FRACTION_BAR",prerequisiteSlugs:["grade-5-fraction-decimal-foundations-p1"],outcomeIds:[ids[21],ids[28],ids[29]] },
  { slug:"grade-6-signed-decimal-operations-p1",title:"Số thập phân có dấu và phép tính",code:"G6-P1-NAA-I",domain:"ALGEBRA_AND_PREALGEBRA",visual:"NUMBER_LINE",prerequisiteSlugs:["grade-5-decimal-operations-p1"],outcomeIds:[ids[32],ids[33],ids[34],ids[35]] },
  { slug:"grade-6-ratio-percent-decimal-p1",title:"Tỉ số, phần trăm và tính chất thập phân",code:"G6-P1-NAA-J",domain:"ALGEBRA_AND_PREALGEBRA",visual:"RATIO_TABLE",prerequisiteSlugs:["grade-5-decimal-relations-map-p1"],outcomeIds:[ids[30],ids[36],ids[37],ids[38]] },
  { slug:"grade-6-regular-shapes-symmetry-p1",title:"Hình đều và đối xứng trong tự nhiên",code:"G6-P1-GEO-A",domain:"GEOMETRY",visual:"SHAPE_SCENE",prerequisiteSlugs:["grade-5-volume-area-nets-p1"],outcomeIds:[ids[31],ids[45],ids[39],ids[40]] },
  { slug:"grade-6-symmetry-identification-p1",title:"Tâm, trục và ứng dụng đối xứng",code:"G6-P1-GEO-B",domain:"GEOMETRY",visual:"SHAPE_SCENE",prerequisiteSlugs:["grade-5-volume-area-nets-p1"],outcomeIds:[ids[41],ids[42],ids[43],ids[44]] },
  { slug:"grade-6-point-line-ray-segment-p1",title:"Điểm, tia, đoạn thẳng và thẳng hàng",code:"G6-P1-GEO-C",domain:"GEOMETRY",visual:"MEASUREMENT_SCALE",prerequisiteSlugs:["grade-5-volume-area-nets-p1"],outcomeIds:[ids[46],ids[47],ids[48],ids[51]] },
  { slug:"grade-6-angle-line-relations-p1",title:"Góc và quan hệ điểm–đường",code:"G6-P1-GEO-D",domain:"GEOMETRY",visual:"ANGLE_DIAGRAM",prerequisiteSlugs:["grade-5-volume-area-nets-p1"],outcomeIds:[ids[49],ids[50],ids[52],ids[66]] },
  { slug:"grade-6-dynamic-geometry-experience-p1",title:"Phần mềm hình học và thực hành đối xứng",code:"G6-P1-GEO-E",domain:"APPLIED_PROBLEM_SOLVING",visual:"SHAPE_SCENE",prerequisiteSlugs:["grade-5-volume-area-nets-p1"],outcomeIds:[ids[53],ids[54],ids[67]] },
  { slug:"grade-6-statistical-interpretation-p1",title:"Biểu diễn và kiểm tra dữ liệu",code:"G6-P1-STA-A",domain:"STATISTICS_AND_PROBABILITY",visual:"DATA_DISPLAY",prerequisiteSlugs:["grade-5-statistical-representations-p1"],outcomeIds:[ids[55],ids[57],ids[58],ids[59]] },
  { slug:"grade-6-probability-data-collection-p1",title:"Thu thập dữ liệu và xác suất thực nghiệm",code:"G6-P1-STA-B",domain:"STATISTICS_AND_PROBABILITY",visual:"DATA_DISPLAY",prerequisiteSlugs:["grade-5-data-finance-experience-p1"],outcomeIds:[ids[56],ids[60],ids[62]] },
  { slug:"grade-6-finance-interdisciplinary-p1",title:"Tài chính, liên môn và đo lường thực tiễn",code:"G6-P1-EXP-A",domain:"APPLIED_PROBLEM_SOLVING",visual:"DATA_DISPLAY",prerequisiteSlugs:["grade-5-data-finance-experience-p1"],outcomeIds:[ids[61],ids[63],ids[64],ids[65]] },
] as const;

const artifacts = buildCompletionArtifacts({
  grade:6,kind:"GRADE6_OUTCOME_COMPLETION",specs,groups,
  restrictions:["Miền xác định phải được nêu: số chia và mẫu khác 0.","Dấu âm, lũy thừa và ngoặc tuân theo thứ tự phép tính THCS.","Dữ liệu, hình và đơn vị phải khớp typed visual; không suy từ hình không theo tỉ lệ."],
});
export const grade6CompletionOutcomes=artifacts.outcomes;
export const grade6CompletionUnitSeeds=artifacts.unitSeeds;
export const grade6CompletionTargetOutcomeIds=ids;

const p=(name:string,value:string|number)=>({name,value});
const money=(value:number)=>value.toLocaleString("vi-VN");
const n=(prompt:string,answer:number,steps:readonly string[],feedback:string,parameters:PreviewAudit["parameters"],visualRequirement?:VisualRequirement):CompletionQuestionCore=>({prompt,answer:String(answer),distractors:numberDistractors(answer),steps,feedback,inputType:"NUMBER_INPUT",parameters,visualRequirement});
const t=(prompt:string,answer:string,distractors:[string,string,string],steps:readonly string[],feedback:string,parameters:PreviewAudit["parameters"],visualRequirement?:VisualRequirement):CompletionQuestionCore=>({prompt,answer,distractors,steps,feedback,inputType:"TEXT_INPUT",parameters,visualRequirement});
const gcd=(x:number,y:number)=>{let a=Math.abs(x),b=Math.abs(y);while(b)[a,b]=[b,a%b];return a||1;};
const lcm=(a:number,b:number)=>Math.abs(a*b)/gcd(a,b);

function scenario(id:string,o:number,r:CompletionRandom):CompletionQuestionCore {
  const ix=ids.indexOf(id);
  switch(ix){
    case 0:{const vals=[14,19,24,29],rom=["XIV","XIX","XXIV","XXIX"],k=o%4;return t(`Viết ${vals[k]} bằng chữ số La Mã.`,rom[k],[String(vals[k]),"IIII","VIX"],["Tách chục và đơn vị.","Dùng quy tắc IV/IX.","Ghép kí hiệu."],"Không lặp I bốn lần.",[p("value",vals[k])],"PLACE_VALUE_CHART");}
    case 1:{const a=r.integer(2,8),b=r.integer(1,9),c=r.integer(1,9),v=a*10000+b*100+c;return n(`Số gồm ${a} chục nghìn, ${b} trăm, ${c} đơn vị là bao nhiêu?`,v,[`${a}×10 000.`,`${b}×100 và ${c}.`,"Cộng các giá trị hàng."],"Phải giữ các hàng có chữ số 0.",[p("tenThousands",a),p("hundreds",b),p("ones",c)],"PLACE_VALUE_CHART");}
    case 2:{const v=[4536,7245,8910][o%3],div=[2,3,5,9].filter(d=>v%d===0);return t(`${v} chia hết cho những số nào trong 2,3,5,9?`,div.join(", "),["chỉ 2","chỉ 3","cả bốn"],["Xét chữ số cuối.","Tính tổng chữ số.","Kết luận từng dấu hiệu."],"Dấu hiệu 3 không tự suy ra 9.",[p("value",v)]);}
    case 3:{const a=r.integer(10000,80000),b=a+r.integer(1,999);return t(`Điền dấu: ${a} … ${b}.`,"<",[">","=","không xác định"],["Cùng số chữ số.","So từ trái.","Số bên trái nhỏ hơn."],"Không so tổng chữ số.",[p("left",a),p("right",b)],"NUMBER_LINE");}
    case 4:{const a=[4,6,8][o%3],k=r.integer(3,9),b=a*k;return t(`${a} có là ước của ${b} không?`,"có",["không","chỉ là bội","không xác định"],[`${b}:${a}=${k}.`,"Thương nguyên.","Phép chia dư 0."],"Ước phải khác 0.",[p("divisor",a),p("multiple",b)]);}
    case 5:{const v=o===0?0:o===1?5:-2;return t(`${v} có thuộc tập N không?`,v>=0?"có":"không",[v>=0?"không":"có","thuộc Z nhưng không N","không xác định"],["N gồm số nguyên không âm.","Kiểm tra dấu và tính nguyên.","Kết luận quan hệ thuộc."],"Không đưa số âm vào N.",[p("value",v)]);}
    case 6:{const limit=3+o;return t(`Liệt kê A={x∈N | x<${limit}}.`,`{${Array.from({length:limit},(_,i)=>i).join(",")}}`,[`{1,...,${limit}}`,`{0,...,${limit}}`,"∅"],["Bắt đầu từ 0.","Dừng trước giới hạn.","Không lặp phần tử."],"Phân biệt < với ≤.",[p("limit",limit)]);}
    case 7:{const d=r.integer(3,9),q=r.integer(20,80);return n(`Tính ${d*q}:${d}+7.`,q+7,["Chia trước.",`${d*q}:${d}=${q}.`,`Cộng 7 được ${q+7}.`],"Số chia phải khác 0.",[p("dividend",d*q),p("divisor",d),p("add",7)]);}
    case 8:{const m=[3,6,9][o%3],a=m*r.integer(3,8),b=m*r.integer(2,7);return t(`${a}+${b} có chia hết cho ${m} không?`,"có",["không","chỉ một số hạng","không xác định"],["Hai số hạng cùng chia hết.","Đặt m làm thừa số chung.","Tổng chia hết m."],"Phải kiểm tra cả hai số hạng.",[p("a",a),p("b",b),p("m",m)]);}
    case 9:{const base=[2,3,4][o%3],exp=3;return n(`Tính 5+${base}^${exp}×2.`,5+base**exp*2,[`Tính ${base}^${exp}.`,"Nhân 2.","Cộng 5 cuối."],"Lũy thừa trước nhân và cộng.",[p("base",base),p("exponent",exp)]);}
    case 10:{const a=r.integer(5,12),b=r.integer(10,20),c=r.integer(2,9);return n(`Tính ${a}×(${b}+${c}).`,a*(b+c),["Phân phối cho cả hai số hạng.",`${a*b}+${a*c}.`,"Cộng kết quả."],"Không bỏ một số hạng.",[p("a",a),p("b",b),p("c",c)],"AREA_MODEL");}
    case 11:{const v=-r.integer(1,9);return n(`Điểm cách 0 ${Math.abs(v)} đơn vị về trái biểu diễn số nào?`,v,["Bên trái 0 mang dấu âm.","Khoảng cách là giá trị tuyệt đối.","Gắn dấu âm."],"Không đặt số âm bên phải 0.",[p("value",v)],"NUMBER_LINE");}
    case 12:{const vals=[21,29,31,33,37],v=vals[(o+r.integer(0,4))%vals.length],prime=[29,31,37].includes(v);return t(`${v} là số nguyên tố hay hợp số?`,prime?"nguyên tố":"hợp số",[prime?"hợp số":"nguyên tố","số 1","không xác định"],["Số lớn hơn 1.","Kiểm tra các ước nhỏ.","Đếm số ước."],"Số 1 không thuộc hai loại.",[p("value",v)]);}
    case 13:{const d=r.integer(3,8),q=r.integer(4,9),rem=(o+1)%d,v=d*q+rem;return t(`Chia ${v} cho ${d}.`,`${q} dư ${rem}`,[String(q+1),`${q} dư ${d}`,String(q)],["Tìm bội gần nhất.",`Viết ${v}=${d}×${q}+${rem}.`,`Kiểm tra ${rem}<${d}.`],"Số dư phải nhỏ hơn số chia.",[p("dividend",v),p("divisor",d),p("quotient",q),p("remainder",rem)]);}
    case 14:{const v=[-8,5,0][o%3];return n(`Số đối của ${v} là gì?`,-v,["Đổi dấu.","Giữ khoảng cách tới 0.","Kiểm tra tổng bằng 0."],"Số đối của 0 là 0.",[p("value",v)],"NUMBER_LINE");}
    case 15:{const v=-r.integer(2,12);return t(`Nhiệt độ ${Math.abs(v)}°C dưới 0 được viết thế nào?`,`${v} °C`,[`${-v} °C`,"0 °C",`${v} m`],["Chọn mốc 0°C.","Dưới mốc dùng dấu âm.","Giữ đơn vị °C."],"Dấu biểu diễn hướng so với mốc.",[p("value",v)],"NUMBER_LINE");}
    case 16:{const a=-r.integer(1,5),b=-r.integer(6,10);return t(`So ${a} và ${b}.`,`${a} > ${b}`,[`${a} < ${b}`,`${a} = ${b}`,"không so sánh"],["Cả hai âm.","Số gần 0 hơn lớn hơn.","Dùng vị trí trên trục."],"Không so riêng giá trị tuyệt đối.",[p("left",a),p("right",b)],"NUMBER_LINE");}
    case 17:{const v=[60,84,90][o%3],facts=v===60?"2²×3×5":v===84?"2²×3×7":"2×3²×5";return t(`Phân tích ${v} thành thừa số nguyên tố.`,facts,[String(v/2),"2×"+v/2,"không phân tích được"],["Chia liên tiếp cho số nguyên tố.","Dừng khi thương 1.","Kiểm tra tích."],"Không dừng ở thừa số hợp số.",[p("value",v)]);}
    case 18:{const total=[48,60,72][o%3],per=[6,5,8][o%3];return n(`${total} vật xếp mỗi hộp ${per}. Cần bao nhiêu hộp?`,total/per,["Chia tổng cho số mỗi hộp.","Phép chia hết.","Kiểm tra bằng nhân."],"Không bỏ phần dư nếu có.",[p("total",total),p("perGroup",per)]);}
    case 19:{const a=r.integer(3,9),b=r.integer(1,5),c=r.integer(2,7),ans=a-(-b+c);return n(`Tính ${a}−(−${b}+${c}).`,ans,[`Trong ngoặc ${-b+c}.`,`Lấy ${a} trừ kết quả.`,"Kiểm tra bằng bỏ ngoặc."],"Dấu trừ trước ngoặc đổi mọi dấu.",[p("a",a),p("b",-b),p("c",c)]);}
    case 20:{const a=[12,18,24][o%3],b=[18,30,36][o%3],ans=lcm(a,b);return n(`Tìm BCNN(${a},${b}).`,ans,["Phân tích nguyên tố.","Lấy số mũ lớn nhất.","Nhân các thừa số."],"Không dùng ƯCLN thay BCNN.",[p("a",a),p("b",b)]);}
    case 21:{const a=r.integer(1,4),b=r.integer(2,7),c=r.integer(1,4),d=r.integer(2,7),den=lcm(b,d),num=a*(den/b)+c*(den/d);return t(`Tính ${a}/${b}+${c}/${d}.`,`${num}/${den}`,[`${a+c}/${b+d}`,`${a*c}/${b*d}`,`${num}/${b*d}`],["Tìm BCNN hai mẫu.","Quy đồng.","Cộng tử."],"Mẫu khác 0 và không cộng mẫu.",[p("a",a),p("b",b),p("c",c),p("d",d),p("common",den)]);}
    case 22:{const gain=r.integer(20,60),loss=r.integer(gain+10,90);return n(`Lãi ${gain} rồi lỗ ${loss} (nghìn đồng). Kết quả có dấu?`,gain-loss,["Quy ước lãi dương.","Lỗ âm.","Cộng hai số có dấu."],"Không bỏ dấu của khoản lỗ.",[p("gain",gain),p("loss",loss)]);}
    case 23:{const scale=[2,3,4][o%3];return t(`Điền phân số bằng 3/5 khi nhân cả tử và mẫu với ${scale}.`,`${3*scale}/${5*scale}`,[`${3*scale}/5`,`3/${5*scale}`,`${3+scale}/${5+scale}`],["Nhân cả tử.","Nhân cả mẫu cùng số.","Mẫu vẫn khác 0."],"Không chỉ đổi một thành phần.",[p("scale",scale)]);}
    case 24:{const whole=r.integer(1,4),den=[3,4,5][o%3],rem=r.integer(1,den-1);return t(`Đổi ${whole} ${rem}/${den} thành phân số.`,`${whole*den+rem}/${den}`,[`${whole+rem}/${den}`,`${whole*den}/${den}`,`${den}/${whole*den+rem}`],["Nhân phần nguyên với mẫu.","Cộng tử.","Giữ mẫu."],"Tử phần lẻ phải nhỏ hơn mẫu.",[p("whole",whole),p("numerator",rem),p("denominator",den)]);}
    case 25:{const a=r.integer(1,6),b=r.integer(a+1,9);return t(`Chuẩn hóa ${a}/(−${b}).`,`−${a}/${b}`,[`${a}/${b}`,`−${b}/${a}`,`${a}/0`],["Có một dấu âm.","Chuyển dấu ra trước.","Giữ mẫu dương."],"Mẫu không được 0.",[p("numerator",a),p("denominator",-b)]);}
    case 26:{const d=-[3,6,7][o%3],q=-r.integer(2,8),v=d*q;return t(`${d} có là ước của ${v} trong Z không?`,"có",["không","chỉ trong N","không xác định"],[`${v}:${d}=${q}.`,"Thương là số nguyên.","Quan hệ chia hết đúng."],"Số chia phải khác 0.",[p("divisor",d),p("value",v)]);}
    case 27:{const a=-r.integer(1,6),b=r.integer(2,9);return t(`Số đối của ${a}/${b}?`,`${-a}/${b}`,[`${b}/${-a}`,`${a}/${b}`,"0"],["Đổi dấu phân số.","Không đảo tử mẫu.","Kiểm tra tổng 0."],"Phân biệt số đối và nghịch đảo.",[p("numerator",a),p("denominator",b)],"NUMBER_LINE");}
    case 28:{const num=[2,3,4][o%3],den=[5,5,7][o%3],part=r.integer(4,9),whole=part*den;return n(`${num}/${den} của một số là ${part*num}. Tìm số.`,whole,[`Một phần ${part*num}:${num}=${part}.`,`Toàn thể ${part}×${den}.`,"Thay lại kiểm tra."],"Tử phải khác 0 trong bài toán ngược.",[p("numerator",num),p("denominator",den),p("partValue",part*num)]);}
    case 29:{const a=r.integer(1,5),b=r.integer(2,8),c=b-a;return t(`Tính ${a}/${b}×3/7+${c}/${b}×3/7.`,"3/7",[`${a+c}/${b+7}`,`${3*(a+c)}/${b*14}`,"1"],["Đặt 3/7 chung.",`(${a}/${b}+${c}/${b})=1.`,"Kết quả 3/7."],"Phân phối và mẫu phải khác 0.",[p("a",a),p("b",b),p("c",c)]);}
    case 30:{const total=r.integer(10,30)*10,percent=[5,10,20][o%3];return n(`${percent}% của ${total} là bao nhiêu?`,total*percent/100,[`Đổi ${percent}/100.`,"Nhân với toàn thể.","Kiểm tra không vượt tổng."],"Phần trăm dựa trên đúng toàn thể.",[p("total",total),p("percent",percent)],"RATIO_TABLE");}
    case 31:return n("Lục giác đều có bao nhiêu cạnh bằng nhau?",6,["Lục giác có 6 cạnh.","Đều nghĩa là bằng nhau.","Đếm đủ sáu cạnh."],"Không nhận dạng chỉ theo hướng.",[p("sides",6)],"SHAPE_SCENE");
    case 32:{const v=-[125,250,375][o%3];return n(`Số đối của số có ${v} phần trăm đơn vị?`,-v,["Đổi dấu.","Giữ độ lớn.","Tổng bằng 0."],"Số đối của 0 vẫn 0.",[p("scaledHundredths",v)],"NUMBER_LINE");}
    case 33:{const a=-[120,205,315][o%3],b=a+5;return t(`So hai số scale phần trăm ${a} và ${b}.`,`${a} < ${b}`,[`${a} > ${b}`,"=","không xác định"],["So dấu.","Căn giá trị hàng.","Số bên trái nhỏ hơn."],"Với số âm, gần 0 hơn lớn hơn.",[p("leftHundredths",a),p("rightHundredths",b)],"NUMBER_LINE");}
    case 34:{const d=[25,40,50][o%3],q=-r.integer(2,8),v=d*q;return n(`Tính ${v} phần trăm : ${d} phần trăm.`,q,["Số chia khác 0.","Hai scale triệt tiêu.","Xác định dấu thương."],"Không chia cho 0.",[p("dividendHundredths",v),p("divisorHundredths",d)]);}
    case 35:{const v=-[346,1255,2995][o%3],scale=10,rounded=-Math.round(Math.abs(v)/scale)*scale;return n(`Làm tròn scale phần trăm ${v} đến scale ${scale}.`,rounded,["Xét chữ số kế bên.","Từ 5 làm tròn tăng độ lớn của hàng giữ.","Giữ dấu âm."],"Kiểm tra ranh giới và dấu.",[p("value",v),p("scale",scale),p("rounded",rounded)]);}
    case 36:{const pct=[10,20,25][o%3],value=r.integer(2,8)*10;return n(`${pct}% của số nào bằng ${value}?`,value*100/pct,[`Một phần trăm ${value}:${pct}.`,"Nhân 100.","Thay lại kiểm tra."],"Tỉ lệ phần trăm phải khác 0.",[p("percent",pct),p("part",value)]);}
    case 37:{const part=r.integer(2,8),total=part*4;return n(`${part} trong ${total} bằng bao nhiêu phần trăm?`,25,[`${part}/${total}=1/4.`,"1/4=0,25.","Nhân 100."],"Tổng phải khác 0.",[p("part",part),p("total",total)],"RATIO_TABLE");}
    case 38:{const c=[25,40,75][o%3];return n(`Tính nhanh 1,25×8×${c} phần trăm đơn vị.`,10*c,["1,25×8=10.","Nhân phần còn lại.","Giữ scale phần trăm."],"Chỉ nhóm phép nhân.",[p("cHundredths",c)]);}
    case 39:{const petals=[4,6,8][o%3];return t(`Một họa tiết có ${petals} cánh giống nhau, cách đều quanh tâm. Quay 180° thì hình có trùng khít không?`,"có",["không","chỉ trùng khi quay 90°","không đủ dữ kiện"],["Số cánh là số chẵn.","Mỗi cánh ghép với cánh đối diện.","Quay nửa vòng làm hình trùng khít."],"Tâm đối xứng phải được kiểm tra bằng phép quay 180°.",[p("petals",petals)],"SHAPE_SCENE");}
    case 40:{const objects=["chiếc lá cân đối","con bướm nhìn từ trên","biển báo hình tam giác cân"],object=objects[o%3];return t(`${object} có một đường chia hai nửa chồng khít khi gấp. Đường đó là gì?`,"trục đối xứng",["tâm đối xứng","đường chéo bất kỳ","tia phân giác bất kỳ"],["Xác định đường gấp.","Hai nửa tương ứng chồng khít.","Kết luận đó là trục đối xứng."],"Trục đối xứng cần phép phản xạ, không chỉ là đường đi qua tâm.",[p("object",object)],"SHAPE_SCENE");}
    case 41:{const shape=["hình chữ nhật","hình thoi","hình bình hành"][o%3];return t(`Tâm đối xứng của ${shape} nằm ở đâu?`,"giao điểm hai đường chéo",["một đỉnh bất kỳ","trung điểm một cạnh","ngoài hình"],["Vẽ hai đường chéo.","Xác định giao điểm.","Quay 180° quanh điểm đó để kiểm tra."],"Tâm đối xứng là một điểm, không phải một đường.",[p("shape",shape)],"SHAPE_SCENE");}
    case 42:{const axis=["d","m","n"][r.integer(0,2)];return t(`Trong thiết kế viền qua đường ${axis}, cách nào tạo hai họa tiết đối xứng?`,"phản chiếu họa tiết qua đường đó",["quay 90° quanh điểm bất kỳ","phóng to một họa tiết","dịch chuyển không giữ khoảng cách"],["Chọn đường làm trục.","Mỗi điểm ảnh và ảnh cách trục bằng nhau.","Nối tương ứng vuông góc trục."],"Không chỉ sao chép: vị trí tương ứng phải đúng qua trục.",[p("transformation","reflection"),p("axis",axis)],"SHAPE_SCENE");}
    case 43:{const shapes=["hình vuông","hình chữ nhật","tam giác đều"],counts=[4,2,3],k=o%3;return n(`${shapes[k]} có bao nhiêu trục đối xứng?`,counts[k],["Dùng phép gấp qua từng đường ứng viên.","Chỉ đếm đường làm hai nửa chồng khít.","Loại đường không bảo toàn hình."],"Không mặc định mọi đường qua tâm đều là trục.",[p("shape",shapes[k])], "SHAPE_SCENE");}
    case 44:return t("Vì sao đối xứng thường tạo cảm giác cân đối trong hoa văn?","các phần tương ứng lặp lại có quy luật",["mọi điểm đều nằm trên một đường","hình luôn có diện tích bằng 1","đối xứng làm mất màu"],["Xác định trục hoặc tâm.","Ghép các phần tương ứng.","Nhận ra quy luật lặp được bảo toàn."],"Vẻ đẹp đối xứng đến từ quan hệ hình học, không chỉ từ màu giống nhau.",[p("context","ornament")],"SHAPE_SCENE");
    case 45:{const hexagons=r.integer(2,6);return n(`Ghép ${hexagons} lục giác đều rời nhau, mỗi hình có 6 cạnh. Nếu chưa ghép cạnh chung thì có tổng bao nhiêu cạnh?`,hexagons*6,["Mỗi lục giác có 6 cạnh.","Các hình đang rời nhau nên chưa trừ cạnh chung.","Nhân số hình với 6."],"Chỉ trừ cạnh khi đề cho hai hình dùng chung cạnh.",[p("hexagons",hexagons)],"SHAPE_SCENE");}
    case 46:{const length=2*r.integer(3,9);return n(`Đoạn AB dài ${length} cm. M là trung điểm AB. AM dài bao nhiêu cm?`,length/2,["Trung điểm nằm trên đoạn AB.","AM=MB.","Chia độ dài AB thành hai phần bằng nhau."],"Điểm cách đều A, B nhưng không thuộc AB chưa chắc là trung điểm.",[p("lengthCm",length)],"MEASUREMENT_SCALE");}
    case 47:return t("Ba điểm A, B, C cùng nằm trên một đường thẳng. Ta gọi chúng là gì?","ba điểm thẳng hàng",["ba điểm trùng nhau","ba điểm đối xứng","ba đỉnh của một tam giác"],["Xác định một đường thẳng.","Kiểm tra cả ba điểm cùng thuộc đường.","Kết luận thẳng hàng."],"Không dựa vào hình vẽ gần thẳng; phải cùng thuộc một đường.",[p("points","A,B,C")],"MEASUREMENT_SCALE");
    case 48:{const ab=[3,5,7][o%3],bc=[2,4,6][o%3];return n(`A, B, C thẳng hàng và B nằm giữa A, C. AB=${ab} cm, BC=${bc} cm. AC bằng bao nhiêu?`,ab+bc,["B nằm giữa nên AC=AB+BC.",`Cộng ${ab}+${bc}.`,"Giữ đơn vị cm."],"Chỉ dùng phép cộng đoạn khi điểm giữa đã được xác định.",[p("abCm",ab),p("bcCm",bc)],"MEASUREMENT_SCALE");}
    case 49:{const angle=r.integer(3,16)*5;return t(`Góc xOy có số đo ${angle}°. Tia Oz nằm bên trong góc khi nào?`,"tia Oz nằm giữa hai cạnh Ox và Oy",["tia Oz đối tia Ox","Oz không chung gốc O","Oz nằm ngoài cả hai cạnh"],["Kiểm tra chung gốc O.","Xác định miền giữa hai cạnh.","Tia trong phải thuộc miền đó."],"Hình không theo tỉ lệ không thay thế điều kiện nằm trong.",[p("angleDegrees",angle)],"ANGLE_DIAGRAM");}
    case 50:{const relation=o%2===0?"song song":"cắt nhau";return t(`Hai đường thẳng ${relation==="song song"?"không có điểm chung":"có đúng một điểm chung"} trong mặt phẳng được gọi là gì?`,relation,[relation==="song song"?"cắt nhau":"song song","trùng nhau","vuông góc trong mọi trường hợp"],["Đếm số điểm chung.","Đối chiếu định nghĩa.","Gọi đúng quan hệ."],"Vuông góc là trường hợp đặc biệt của cắt nhau, không phải mọi cặp cắt nhau.",[p("commonPointCount",relation==="song song"?0:1)],"ANGLE_DIAGRAM");}
    case 51:return t("Tia Ox được xác định bởi dữ kiện nào?","gốc O và một điểm X khác O",["chỉ điểm O","hai điểm không phân biệt","một độ dài không có hướng"],["Chọn gốc O.","Chọn điểm X xác định hướng.","Lấy phần đường thẳng từ O theo hướng X."],"Tia có gốc và kéo dài vô hạn theo một hướng.",[p("origin","O"),p("directionPoint","X")],"MEASUREMENT_SCALE");
    case 52:return t("Qua hai điểm phân biệt A và B có bao nhiêu đường thẳng?","một",["không có","hai","vô số"],["A và B phân biệt.","Dựng đường đi qua cả hai.","Tính duy nhất bảo đảm không có đường thứ hai khác."],"Nếu hai điểm trùng nhau thì dữ kiện không còn xác định duy nhất.",[p("distinctPoints",2)],"MEASUREMENT_SCALE");
    case 53:{const trials=r.integer(2,6);return t(`Trong phần mềm hình học động, sau ${trials} lần kéo thử, cách kiểm tra M luôn là trung điểm AB là gì?`,"kéo A hoặc B và kiểm tra M thuộc AB, AM=MB",["chỉ nhìn hình ban đầu","đo AM một lần rồi xóa B","vẽ M gần giữa bằng tay"],["Dựng quan hệ M thuộc AB.","Ràng buộc AM=MB.","Kéo các điểm tự do và quan sát bất biến."],"Một ảnh chụp đúng không chứng minh quan hệ động.",[p("invariant","M_on_AB_and_AM_equals_MB"),p("dragTrials",trials)],"MEASUREMENT_SCALE");}
    case 54:return t("Muốn dựng hình vuông từ cạnh AB trong phần mềm, bộ ràng buộc nào cần thiết?","các cạnh bằng nhau và hai cạnh kề vuông góc",["chỉ bốn điểm bất kỳ","hai đường chéo bất kỳ","chỉ một cặp cạnh song song"],["Dựng vuông góc tại A và B.","Lấy các cạnh bằng AB.","Nối cạnh còn lại và kiểm tra song song."],"Vẽ gần giống hình vuông không đủ nếu thiếu ràng buộc.",[p("base","AB")],"SHAPE_SCENE");
    case 55:{const a=r.integer(18,30),b=r.integer(10,17);return n(`Biểu đồ cột cho nhóm A=${a}, nhóm B=${b}. A hơn B bao nhiêu?`,a-b,["Đọc cùng thang đo.",`Tính ${a}−${b}.`,"Diễn giải chênh lệch."],"Không đếm số vạch như giá trị nếu mỗi vạch có scale khác 1.",[p("a",a),p("b",b),p("scale",1)],"DATA_DISPLAY");}
    case 56:{const experiment=["tung đồng xu","rút một thẻ từ {đỏ, xanh, vàng}","gieo một xúc xắc"],spaces=["sấp hoặc ngửa","đỏ, xanh hoặc vàng","1, 2, 3, 4, 5 hoặc 6"],k=o%3;return t(`Không gian kết quả của phép thử ${experiment[k]} là gì?`,spaces[k],["chỉ một kết quả thuận lợi","mọi số tự nhiên","không có kết quả"],["Xác định phép thử.","Liệt kê mọi kết quả có thể không trùng.","Không thêm kết quả không thể."],"Sự kiện chỉ là tập con; không được thay cho toàn bộ không gian kết quả.",[p("experiment",experiment[k])],"DATA_DISPLAY");}
    case 57:return t("Muốn so sánh số học sinh nam và nữ ở từng lớp, biểu diễn nào phù hợp nhất?","biểu đồ cột kép",["một cột không chia nhóm","đoạn thẳng không có nhãn","bảng chỉ ghi tổng toàn trường"],["Mỗi lớp là một nhóm.","Mỗi nhóm có hai dãy nam–nữ.","Cột kép cho phép so trong và giữa nhóm."],"Hai dãy phải dùng cùng thang đo.",[p("series",2)],"DATA_DISPLAY");
    case 58:return t("Bảng nhiệt độ theo 7 ngày cần ghi thêm thông tin nào để có ý nghĩa?","đơn vị nhiệt độ và ngày đo",["chỉ màu nền","tên người nhập duy nhất","một số không có nhãn"],["Xác định biến nhiệt độ.","Ghi thời điểm từng quan sát.","Ghi đơn vị °C."],"Không so dữ liệu khác đơn vị hoặc khác kỳ.",[p("days",7),p("unit","°C")],"DATA_DISPLAY");
    case 59:{const age=[12,120,-3][o%3],valid=age===12;return t(`Dữ liệu “tuổi học sinh lớp 6 là ${age} năm” có hợp lí không?`,valid?"có":"không",[valid?"không":"có","không đủ phép tính","chỉ đúng nếu đổi sang mét"],["Kiểm tra đơn vị năm.","So với phạm vi tuổi thực tế.","Kết luận và giữ lại dấu hiệu ngoại lệ để kiểm tra."],"Không xóa ngoại lệ trước khi xác minh nguồn.",[p("ageYears",age)]);}
    case 60:{const rainy=r.integer(4,10),dry=20-rainy;return n(`Phân loại 20 ngày thành mưa ${rainy} ngày và không mưa ${dry} ngày. Tổng kiểm tra là bao nhiêu?`,20,[`Cộng ${rainy}+${dry}.`,"Hai nhóm không chồng nhau.","Tổng phải bằng số ngày quan sát."],"Không đổi tiêu chí phân loại giữa chừng.",[p("rainy",rainy),p("dry",dry)],"DATA_DISPLAY");}
    case 61:{const capital=r.integer(5,20)*100000,rate=r.integer(4,8);return n(`Gửi ${money(capital)} đồng với lãi đơn ${rate}% một kỳ. Tiền lãi là bao nhiêu đồng?`,capital*rate/100,["Đổi phần trăm thành phân số trên 100.","Nhân với vốn gốc.","Phân biệt tiền lãi với số dư mới."],"Không cộng trực tiếp tỉ lệ vào số tiền.",[p("capital",capital),p("ratePercent",rate)],"RATIO_TABLE");}
    case 62:{const trials=[20,40,50][o%3],success=[8,22,30][o%3];return t(`Một sự kiện xảy ra ${success} lần trong ${trials} lần thử. Xác suất thực nghiệm là bao nhiêu?`,String(success/trials).replace(".",","),[String(trials/success).replace(".",","),String(success),String(trials)],["Lấy số lần xảy ra chia tổng số lần thử.",`Tính ${success}/${trials}.`,"Kiểm tra kết quả trong [0;1]."],"Tổng số lần thử phải dương; mẫu nhỏ không chứng minh chắc chắn.",[p("success",success),p("trials",trials)],"DATA_DISPLAY");}
    case 63:{const total=[135000,168000,245000][o%3],paid=[200000,200000,300000][o%3];return n(`Hóa đơn ${money(total)} đồng, khách trả ${money(paid)} đồng. Tiền thừa là bao nhiêu?`,paid-total,["Lấy tiền trả trừ tổng hóa đơn.","Kiểm tra kết quả không âm.","Cộng tiền thừa với hóa đơn để đối chiếu."],"Không bỏ khoản hàng và không tính tiền thừa nếu tiền trả thiếu.",[p("bill",total),p("paid",paid)],"DATA_DISPLAY");}
    case 64:{const a=[24,32,45][o%3],b=[18,27,36][o%3];return n(`Bảng cùng đơn vị ghi địa phương A=${a}, B=${b}. Chênh lệch là bao nhiêu?`,a-b,["Đọc tiêu đề và đơn vị.","Hai số cùng kỳ nên có thể trừ.","Lấy số lớn trừ số nhỏ."],"Không so dữ liệu khác năm hay khác đơn vị.",[p("a",a),p("b",b)],"DATA_DISPLAY");}
    case 65:{const length=[4,5,6][o%3],width=[3,4,5][o%3],height=[2,3,4][o%3];return n(`Hộp chữ nhật dài ${length} dm, rộng ${width} dm, cao ${height} dm có thể tích bao nhiêu dm³?`,length*width*height,["Ba kích thước dương và cùng đơn vị.","Nhân dài×rộng×cao.","Ghi đơn vị khối dm³."],"Không dùng công thức diện tích hoặc đơn vị dm².",[p("lengthDm",length),p("widthDm",width),p("heightDm",height)],"SOLID_NET");}
    case 66:return t("Để trồng ba cây thẳng hàng chính xác, nên làm gì?","căng dây qua vị trí cây đầu và cây cuối rồi đặt cây giữa trên dây",["ước nhìn từng cây riêng","đo ba khoảng cách bất kỳ","vẽ một đường cong qua ba cây"],["Chọn hai mốc phân biệt.","Căng dây tạo đường thẳng duy nhất.","Đặt mốc còn lại trên dây."],"Ước nhìn không phải kiểm chứng thẳng hàng.",[p("method","string_line")],"MEASUREMENT_SCALE");
    case 67:return t("Gấp giấy để cắt một hình có trục đối xứng, đường gấp đóng vai trò gì?","trục đối xứng",["tâm đối xứng","một cạnh bất kỳ","đường không liên quan"],["Gấp hai nửa chồng lên nhau.","Cắt xuyên hai lớp.","Mở giấy, các điểm tương ứng đối xứng qua nếp gấp."],"Phải cắt hai lớp cùng lúc để giữ quan hệ phản xạ.",[p("activity","paper_fold")],"SHAPE_SCENE");
    default: throw new Error(`No Grade 6 semantic strategy for ${id}.`);
  }
}

export function generateGrade6QuestionSpecs(unit: CurriculumUnit, seed: string) {
  return generateCompletionQuestionSpecs({
    unit,
    seed,
    kind: "GRADE6_OUTCOME_COMPLETION",
    scenario,
  });
}
